package.json
packages/forma-36-react-components/src/components/Button/Button.css
packages/forma-36-react-components/src/components/Card/Card/Card.css
packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.css
packages/forma-36-react-components/src/components/Modal/Modal/Modal.css
packages/forma-36-react-components/src/components/Select/Select/Select.css
packages/forma-36-react-components/src/components/TextInput/TextInput.css
packages/forma-36-react-components/src/components/Textarea/Textarea.css
packages/forma-36-react-components/src/components/ToggleButton/ToggleButton.css
packages/forma-36-react-components/src/styles/settings/a11y.css
packages/forma-36-react-components/src/styles/settings/shadows.css
packages/forma-36-react-components/tools/.storybook/tokens/boxshadows.stories.js
packages/forma-36-react-components/tools/.storybook/tokens/tokens.js
packages/forma-36-react-components/yarn.lock
yarn.lock

feat(BoxShadowTokens): Added box shadow tokens

---

packages/forma-36-react-components/src/styles/settings/animations.css
packages/forma-36-react-components/tools/.storybook/tokens/tokens.js
packages/forma-36-react-components/tools/.storybook/tokens/transitions.css
packages/forma-36-react-components/tools/.storybook/tokens/transitions.stories.js

This PR will add the transition and animation tokens

docs(Transitions): Added transition tokens

---

packages/forma-36-react-components/src/components/Checkbox/Checkbox.css
packages/forma-36-react-components/src/components/RadioButton/RadioButton.css

This PR will remove unused Radio Buttons styles

fix(RadioButton): Removed unused code

---

packages/forma-36-react-components/tools/plop-templates/components/component.js.hbs

This PR will add the use of classnames in the plop templates.

chore(Plop Template): Use classnames in plop template

---

packages/forma-36-react-components/src/components/List/List/List.css
packages/forma-36-react-components/src/components/List/List/List.js
packages/forma-36-react-components/src/components/List/List/List.stories.js
packages/forma-36-react-components/src/components/List/List/List.test.js
packages/forma-36-react-components/src/components/List/List/__snapshots__/List.test.js.snap
packages/forma-36-react-components/src/components/List/List/index.js
packages/forma-36-react-components/src/components/List/ListItem/ListItem.css
packages/forma-36-react-components/src/components/List/ListItem/ListItem.js
packages/forma-36-react-components/src/components/List/ListItem/ListItem.test.js
packages/forma-36-react-components/src/components/List/ListItem/__snapshots__/ListItem.test.js.snap
packages/forma-36-react-components/src/components/List/ListItem/index.js
packages/forma-36-react-components/src/index.js

This PR will add the List and List Item component.

feat(List): Added List and List Item Component

---

packages/forma-36-fcss/package.json

This PR will change the name of the FCSS package

fix(FCSS): Changed package name

---

netlify.toml
packages/forma-36-fcss/README.md
packages/forma-36-fcss/scss/spacing.scss
packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbar/EditorToolbar.css
packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarDivider/EditorToolbarDivider.css
packages/forma-36-react-components/src/components/Note/Note.css
packages/forma-36-react-components/src/components/Notification/NotificationItem.css
packages/forma-36-react-components/src/components/Notification/NotificationsManager.css
packages/forma-36-react-components/tools/.storybook/tokens/spacing.stories.js
packages/forma-36-react-components/tools/.storybook/tokens/tokens.js
packages/forma-36-react-components/yarn.lock
packages/forma-36-tokens/src/tokens/spacing.js
packages/forma-36-website/README.md

Updated yarn lock to resolve css tokens in stylesheets. I also updated the vertical spacing tokens to use the new tokens in storybook

fix(React Components): Updated yarn lock to resolve tokens

---

packages/forma-36-react-components/src/components/IconButton/IconButton.css
packages/forma-36-react-components/src/components/IconButton/IconButton.js
packages/forma-36-react-components/src/components/IconButton/IconButton.stories.js

This PR will add the white button type for the icon button

fix(IconButton): Added white icon button type

---

packages/forma-36-fcss/package.json
packages/forma-36-tokens/package.json

This PR will add prepublish scripts to all packages

chore(Packages): Added prepublish scripts for all packages

---

packages/forma-36-react-components/src/components/Asset/Asset.css
packages/forma-36-react-components/yarn.lock

This PR will fix overflowing asset cards in the rich text field

fix(AssetCard): Fix overflowing asset cards

---

packages/forma-36-fcss/scss/spacing.scss

This PR will fix vertical spacing helpers

fix(FCSS): fix vertical spacing helpers

---

packages/forma-36-website/package.json

This PR will make the website private

fix(Website): Website should not be published to npm

---

packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.js

Otherwise, it can interfere with a potential form in the modal.

Add type to close button

---

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.js
packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.js.snap

fix(AssetCard): Fixed overflowing images

---

packages/forma-36-react-components/yarn.lock
packages/forma-36-tokens/src/tokens/colors-coral.js
packages/forma-36-website/yarn.lock

The value for `color-coral-mid` was missing a the hash character which resulted in an invalid colour being used in the components and fcss packages.

Update broken colour token

---

packages/forma-36-react-components/index.d.ts
packages/forma-36-react-components/package.json

This PR adds typescript type definition for all of the forma-36 components

Add typescript type def

---

packages/forma-36-react-components/src/components/Table/Table/Table.stories.js
packages/forma-36-react-components/src/components/Table/TableCell/TableCell/TableCell.js
packages/forma-36-react-components/src/components/Table/TableHead/TableHead.css
packages/forma-36-react-components/src/components/Table/TableHead/TableHead.js
packages/forma-36-react-components/src/components/Table/TableHead/TableHead.test.js
packages/forma-36-react-components/src/components/Table/TableHead/__snapshots__/TableHead.test.js.snap

This pr will add a property to the table header to make it sticky.

feat(Table): add sticky prop to table header

---

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.stories.js

Force reinitialization to apply dropdown position via knobs

fix(Dropdown Story): Force reinitialization

---

bin/before-deploy

This PR fixes a typo in the deploy script

fix(CI): fixed token typo

---

packages/forma-36-react-components/src/components/Note/Note.stories.js
packages/forma-36-react-components/tools/.storybook/tokens/spacing.stories.js
packages/forma-36-react-components/yarn.lock

Some misc fixes
- Removing a leftover console.log
- Generating a yarn.lock file (had some changes when installing packages from master)
- Fix the Note story to show the Info button

Misc fixes

---

packages/forma-36-react-components/yarn.lock

Fix previous broken yarn lockfile

Fix yarn lockfile

---

packages/forma-36-fcss/README.md
packages/forma-36-fcss/scss/colors.scss

This PR will add the missing text color light to FCSS

fix(FCSS): Add missing color light

---

bin/build
package.json
packages/forma-36-tokens/yarn.lock
yarn.lock

This PR removed Commitlint from CI build step since merge commits and commits triggered through lerna could cause failings.

ci(Commitlint): Removed Commitlint from CI

---

package.json
packages/forma-36-react-components/package.json
packages/forma-36-react-components/yarn.lock
yarn.lock

build: Fix failing ESLint on CI

---

packages/forma-36-react-components/src/components/Checkbox/Checkbox.stories.tsx

Fixes broken storybook for Checkbox component.

docs(Checkbox): Fixed broken story for Checkbox component

---

packages/forma-36-react-components/index.d.ts

Fixes incorrect state of `index.d.ts` file introduced by merge artifacts.

fix(Typings): Fix index.d.ts exports

---

bin/before-deploy

chore(CI): Log possible changes

---

bin/before-deploy

chore(CI): Diff CI changes

---

.travis.yml
bin/before-deploy

Set the yarn version to 1.13.0

chore(CI): Set Yarn version

---

.travis.yml
packages/forma-36-react-components/yarn.lock

This PR will disable the creation of a lock file in ci

chore(CI): No lockfile creation

---

packages/forma-36-react-components/tools/plop-templates/components/component.tsx.hbs

Add prop descriptions to component template to encourage better self-documentation in components

Add prop descriptions to component template

---

package.json
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.stories.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.test.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.stories.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.test.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap
packages/forma-36-react-components/src/components/Card/CardActions/index.ts
packages/forma-36-react-components/src/components/Card/InlineReferenceCard/InlineReferenceCard.css
packages/forma-36-react-components/src/components/Card/InlineReferenceCard/InlineReferenceCard.stories.tsx
packages/forma-36-react-components/src/components/Card/InlineReferenceCard/InlineReferenceCard.test.tsx
packages/forma-36-react-components/src/components/Card/InlineReferenceCard/InlineReferenceCard.tsx
packages/forma-36-react-components/src/components/Card/InlineReferenceCard/__snapshots__/InlineReferenceCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/ReferenceCard/ReferenceCard.css
packages/forma-36-react-components/src/components/Card/ReferenceCard/ReferenceCard.stories.tsx
packages/forma-36-react-components/src/components/Card/ReferenceCard/ReferenceCard.test.tsx
packages/forma-36-react-components/src/components/Card/ReferenceCard/ReferenceCard.tsx
packages/forma-36-react-components/src/components/Card/ReferenceCard/__snapshots__/ReferenceCard.test.tsx.snap
packages/forma-36-react-components/src/index.ts

This is a breaking change to the ReferenceCard component which changes how actions are passed and rendered in ReferenceCard.

Refactor ReferenceCard actions

---

packages/forma-36-tokens/tools/build.js

This PR will add the default export to the tokens.

fix(Tokens): Default export tokens

---

README.md
packages/forma-36-react-components/README.md

Use "suffix" instead of "prefix" phere applicable and add links to the Contentful website.

Some minor README updates

---

packages/forma-36-react-components/MIGRATION.md

Add migration notes to help users migrating from Forma 36 React Components v2.x.x to v3.x.x

chore(Migration): Add migration notes

---

README.md

Updated the sections Commits & Releases and Reach out to us

chore(Readme): Updated sections Commits & Releases and Reach out to us

---

packages/forma-36-tokens/tools/build.js

PR adds the value of the token to the description.

Improve tokens in v3

---

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardActions.stories.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.test.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/__snapshots__/CardDragHandle.test.tsx.snap
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx

This PR fixes lint issues for the CardDragHandle and AssetCard components

fix(CardDragHandle): fixed lint issues

---

packages/forma-36-react-components/src/components/Button/Button.css

This PR will specify the transition of background colors on the Button component.

fix(Button): Specify button background transitions

---

packages/forma-36-react-components/package.json
packages/forma-36-react-components/tsconfig.json
packages/forma-36-react-components/yarn.lock

fix(typescript): Fixed non produced .d.ts files

---

packages/forma-36-react-components/tools/plop-templates/components/stories.tsx.hbs
packages/forma-36-react-components/tools/plopfile.js

There were a couple of bugs from the TypeScript left in our Plopfile and a Plop template. This PR fixes them.

Plopfile fixes

---

packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/src/components/EntityList/EntityList/EntityList.css
packages/forma-36-react-components/src/components/EntityList/EntityList/EntityList.md
packages/forma-36-react-components/src/components/EntityList/EntityList/EntityList.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityList/EntityList.test.tsx
packages/forma-36-react-components/src/components/EntityList/EntityList/EntityList.tsx
packages/forma-36-react-components/src/components/EntityList/EntityList/__snapshots__/EntityList.test.tsx.snap
packages/forma-36-react-components/src/components/EntityList/EntityList/index.ts
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.css
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.md
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.test.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
packages/forma-36-react-components/src/components/EntityList/EntityListItem/index.ts
packages/forma-36-react-components/src/index.ts
packages/forma-36-react-components/src/styles/settings/helpers.css

This PR adds EntityList and EntityListItem components. This is to render lists of entities (entries or assets).

EntityList and EntityListItem components

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/pages/components/form-label/index.mdx
packages/forma-36-website/src/pages/components/help-text/index.mdx
packages/forma-36-website/src/pages/components/text-field/index.mdx
packages/forma-36-website/src/pages/components/text-input/index.mdx
packages/forma-36-website/src/pages/components/validation-message/index.mdx
packages/forma-36-website/yarn.lock

TextField component documentation.

WIP: docs(TextField): Add TextField component documenation

---

packages/forma-36-react-components/src/index.ts

fix(CardDragHandle): Add CardDragHandle to export

---

.travis.yml
package.json
packages/forma-36-fcss/package.json
packages/forma-36-fcss/yarn.lock
yarn.lock

Resolve vulnerable tar version

fix(packages): resolve vulnerable tar version

---

packages/forma-36-react-components/src/components/InViewport/InViewport.tsx

This PR will fix an Issue causing the application to crash when the overflow handler got stuck in an infinite overflow loop

fix(InViewport): Prevent Infinite handle overflow

---

packages/forma-36-react-components/src/components/Switch/Switch.css
packages/forma-36-react-components/src/components/Switch/Switch.stories.tsx
packages/forma-36-react-components/src/components/Switch/Switch.test.tsx
packages/forma-36-react-components/src/components/Switch/Switch.tsx
packages/forma-36-react-components/src/components/Switch/__snapshots__/Switch.test.tsx.snap
packages/forma-36-react-components/src/components/Switch/index.ts
packages/forma-36-react-components/src/index.ts
packages/forma-36-react-components/yarn.lock

Adds a Switch button. To see my motivation to add Switch to Forma36, please see following document:
[Checkboxes vs Switches](https://docs.google.com/document/d/1Iu1E0RzvsSa9UzaOgEwoWw0f7NRoHjFDQqE5pKIw05g/edit?usp=sharing)
Enabled:
Disabled:

Add switch button

---

packages/forma-36-react-components/src/components/Switch/__snapshots__/Switch.test.tsx.snap

fix(Switch): snapshot tests

---

packages/forma-36-website/src/pages/foundation/typography/index.mdx

This PR will add Typography tokens and scale to the design systems docs

feat(Typography): Added type scale

---

packages/forma-36-website/package.json
packages/forma-36-website/src/components/ColorSwatch.js
packages/forma-36-website/src/components/ColorSwatchGroup.js
packages/forma-36-website/src/pages/foundation/color/index.mdx
packages/forma-36-website/yarn.lock

This PR will add the color docs

feat(Colors): Added color tokens

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/pages/foundation/layout/index.mdx
packages/forma-36-website/src/pages/foundation/layout/spacing/index.mdx

This PR will add the spacing tokens to the documentation website

feat(Spacing): Added spacing scale

---

packages/forma-36-fcss/package.json
packages/forma-36-fcss/yarn.lock
packages/forma-36-react-components/yarn.lock
yarn.lock

This PR will add a resolution for fstream

fix(Fstream): Add Fstream resolution

---

packages/forma-36-website/src/pages/components/form-label/index.mdx
packages/forma-36-website/src/pages/components/help-text/index.mdx
packages/forma-36-website/src/pages/components/note/index.mdx
packages/forma-36-website/src/pages/components/text-field/index.mdx
packages/forma-36-website/src/pages/components/text-input/index.mdx
packages/forma-36-website/src/pages/components/validation-message/index.mdx

Doc website components

---

yarn.lock

fix(Yarn): Generate new lockfile

---

bin/deploy

chore(CI): Reenable verify

---

bin/before-deploy

Reset master to origin master before deploy

chore(Ci): Fix failing CI

---

package.json

chore(Commitlint): Reenable commitlint

---

packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/src/components/Pill/Pill.css
packages/forma-36-react-components/src/components/Pill/Pill.stories.tsx
packages/forma-36-react-components/src/components/Pill/Pill.tsx
packages/forma-36-react-components/src/components/Pill/__snapshots__/Pill.test.tsx.snap

Added ability to override drag handle in Pill component
Added ability to set fixed width for Pill component without breaking markup.

feat(Pill): Added dragHandleComponent property to Pill component

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/package.json
packages/forma-36-website/yarn.lock

chore(Website): Add GA

---

packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx
packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/__snapshots__/DropdownListItem.test.tsx.snap

This PR makes sure otherProps are accessible to all render variations of the DropdownListItem component

fix(DropdownListItem): fix otherProps

---

packages/forma-36-react-components/package.json
packages/forma-36-react-components/yarn.lock

This PR will bump handlebars to 4.1.0

fix(Dependency): Bump handlebars to 4.1.0

---

packages/forma-36-website/package.json
packages/forma-36-website/yarn.lock

This Pr bumps webpack dev server and js yaml

fix(Dependencies): bump webpack dev server and js-yaml

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/components/Container.js
packages/forma-36-website/src/pages/guidelines/index.mdx
packages/forma-36-website/src/pages/guidelines/keyboard-shortcuts/index.mdx

This PR adds guidelines for keyboard shortcuts. These guidelines do not prescribe specific shortcuts, but are intended to help teams building Contentful products who want to implement keyboard shortcuts.

Add Keyboard shortcut guidelines

---

packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx

This PR fixes otherProps overriding className in some cases.

fix(DropdownListItem): fix overriding classNames of interactive element

---

packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx

prevent override of data-test-id and className

fix(DropdownListItem): Prevent overriding props of interactive element

---

packages/forma-36-react-components/package.json
packages/forma-36-react-components/yarn.lock

This PR upgrades packages dependant on handlebars as there is currently a security warning about the version of handlebars in our package lock file

Update packages dependant on handlebars

---

packages/forma-36-react-components/src/components/CopyButton/CopyButton.stories.tsx
packages/forma-36-react-components/src/components/CopyButton/CopyButton.tsx
packages/forma-36-react-components/src/components/CopyButton/__snapshots__/CopyButton.test.tsx.snap
packages/forma-36-react-components/src/components/InViewport/InViewport.tsx
packages/forma-36-react-components/src/components/TextInput/__snapshots__/TextInput.test.tsx.snap
packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx

This PR will extend the props of the CopyButton to allow changing the tooltipPosition, text and copied text.

feat(CopyButton): Added props for tooltipPlace and tooltipText

---

packages/forma-36-react-components/src/components/Modal/ModalContent/ModalContent.css

This PR will prevent overflow of the modal content

fix(ModalContent): Prevent horizontal overflow scroll

---

packages/forma-36-react-components/src/components/Workbench/Workbench.css

This PR will fix the width and alignment of the workbench actions.

fix(Workbench): Fix width and alignment of workbench actions

---

packages/forma-36-react-components/src/components/Tooltip/Tooltip.stories.tsx
packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx

This PR will fix the positioning of the tooltip on initial render when isVisible is set.

fix(Tooltip): fix initial positioning on isVisible

---

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css

This PR will fix the width of the InViewport component when the dropdown container is full width

fix(DropdownContainer): expand inviewport to full width of the container

---

packages/forma-36-react-components/src/components/Workbench/Workbench.css
packages/forma-36-react-components/src/components/Workbench/Workbench.stories.tsx
packages/forma-36-react-components/src/components/Workbench/Workbench.tsx

The description was missing in the Workbench.Header component. This PR will add it.

fix(Workbench): Add description to Workbench.Header

---

packages/forma-36-react-components/src/components/TextInput/TextInput.stories.tsx
packages/forma-36-react-components/src/components/TextInput/TextInput.tsx

Add `onKeyPress` event on text input element to get the keys pressed.
I have also opened the issue #287

fix(TextInput): Ajusted text input to have the event on key press

---

README.md

Add local testing notes to documentation

Add local testing notes

---

packages/forma-36-react-components/src/components/Switch/Switch.stories.tsx
packages/forma-36-react-components/src/components/Switch/Switch.test.tsx
packages/forma-36-react-components/src/components/Switch/Switch.tsx
packages/forma-36-react-components/src/components/Switch/__snapshots__/Switch.test.tsx.snap

Switch label

---

packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.css

Unify dropdown list link color

fix(DropdownList): Unify dropdown list link color

---

packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.css
packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.css

This PR will unify the DropdownlistItem color

fix(DropdownListItem): Unify list item color

---

packages/forma-36-website/src/pages/components/example/index.mdx
packages/forma-36-website/src/pages/components/index.mdx
packages/forma-36-website/src/pages/components/note/index.mdx

This PR will add documentation for the Note component to storybook

Docs Note component

---

packages/forma-36-website/src/components/Layout.css

Whilst our audience aren't mobile users, this PR introduces some fixes to at least make the website render a little better on mobile and tablets.

Mobile Site Improvements

---

packages/forma-36-tokens/README.md

Small bug in README

---

packages/components/forma-36-react-datepicker/yarn.lock
packages/components/forma-36-react-timepicker/test/Timepicker.test.tsx
packages/components/forma-36-react-timepicker/yarn.lock

This Pr will update the dependencies of the datepicker component

fix(Datepicker): Update dependencies

---

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx

Fix a lint error of the EntryCard

fix(EntryCard): Fix lint error

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/pages/foundation/z-index/index.mdx

This PR will add the Z-Index tokens documentation

docs(Z-Index): Add Z-Index Docs

---

packages/forma-36-react-components/src/components/Form/Form/Form.css
packages/forma-36-react-components/src/components/Form/Form/Form.stories.tsx
packages/forma-36-react-components/src/components/Form/Form/Form.test.tsx
packages/forma-36-react-components/src/components/Form/Form/Form.tsx
packages/forma-36-react-components/src/components/Form/Form/__snapshots__/Form.test.tsx.snap

This PR will remove the not used condensed form spacing setting.
Since it is a breaking change this PR will be merged into next.

fix(Form): Remove condensed spacing setting

---

package.json
yarn.lock

fix(Lerna): Update lerna

---

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.css
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx

Autocomplete client code should be able to reach/configure the underlying dropdown
Reach Dropdown API parity by adding namespace `dropdownProps` which is responsible for configuring the underlying Dropdown.

improvement(autocomplete): allow underlying dropdown configuration

---

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.test.tsx

This PR fixes some complaints from es-lint around usage of `type` rather than `interface`.

fix(autocomplete): fix typing in tests

---

packages/forma-36-website/src/pages/components/button/index.mdx
packages/forma-36-website/src/pages/components/form-label/index.mdx
packages/forma-36-website/src/pages/components/form/index.mdx
packages/forma-36-website/src/pages/components/help-text/index.mdx
packages/forma-36-website/src/pages/components/icon/index.mdx
packages/forma-36-website/src/pages/components/modal/index.mdx
packages/forma-36-website/src/pages/components/note/index.mdx
packages/forma-36-website/src/pages/components/table/index.mdx
packages/forma-36-website/src/pages/components/text-field/index.mdx
packages/forma-36-website/src/pages/components/text-input/index.mdx
packages/forma-36-website/src/pages/components/text-link/index.mdx
packages/forma-36-website/src/pages/components/typography/index.mdx
packages/forma-36-website/src/pages/components/validation-message/index.mdx

The purpose of this PR is to improve and streamline the copy, example snippets and data, headings, and layout of component pages. It makes components pages a bit more consistent.

Copy improvements for docs

---

packages/forma-36-react-components/src/alpha.ts
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx
packages/forma-36-react-components/src/index.ts

This PR will mark the Autocomplete component as an alpha component

Mark Autocomplete as an alpha component

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/pages/components/dropdown/index.mdx
packages/forma-36-website/src/pages/components/help-text/index.mdx
packages/forma-36-website/src/pages/components/notification/index.mdx

This PR adds documentation for the Dropdown component. It replaces an existing PR here: https://github.com/contentful/forma-36/pull/373

Dropdown Documentation

---

packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap

Fix `testId` propagation in `CardActions` component

fix(cardactions): fix testId propagation

---

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.test.tsx
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx

This PR will allow the entry card to accept react nodes as content type

fix(EntryCard): Allow react node for entry card content type

---

packages/forma-36-react-components/package.json
packages/forma-36-react-components/tools/.storybook/main.js
packages/forma-36-react-components/tools/.storybook/preview.js
packages/forma-36-react-components/yarn.lock

This PR adds the JSX addon to Storybook. This allows users to configure components using knobs, then copy the resulting JSX needed to implement the component.
This works pretty well, however, there are a few places where it doesn’t work quite as nicely such as:
- https://deploy-preview-395--forma-36-react-components.netlify.com/?path=/story/components-checkbox--default (shouldn’t show the classname prop as it’s empty, shouldn’t show the onChange function as it’s coming from the Storybook actions add-on)
- https://deploy-preview-395--forma-36-react-components.netlify.com/?path=/story/components-checkboxfield--default (story has been written in a way where it’s wrapped in another component)

Add JSX addon to Storybook

---

packages/forma-36-react-components/src/components/Icon/Icon.tsx

fix(Icon): Remove unused ReactElement to fix lint errors

---

packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.tsx

This Pr will merge styles provided via props with exisiting styles.

fix(DropdownList): Merge styles

---

packages/forma-36-react-components/src/alpha.ts
packages/forma-36-react-components/src/index.ts

This pr will make the Workbench component generally available.

feat(Workbench): Make Workbench generally available

---

packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/src/index.ts

This PR exports the RadioButton component 😳

Export RadioButton component

---

packages/components/forma-36-react-datepicker/src/Datepicker.tsx
packages/components/forma-36-react-datepicker/yarn.lock
packages/components/forma-36-react-timepicker/package.json
packages/components/forma-36-react-timepicker/src/Timepicker.tsx
packages/components/forma-36-react-timepicker/yarn.lock

Refactor date and time picker components
A bit of refactoring to adopt the component in the future. WIP, please, add any feedback.

refactor(datepicker, timepicker): refactoring

---

packages/components/forma-36-react-datepicker/yarn.lock
packages/components/forma-36-react-timepicker/yarn.lock
packages/forma-36-react-components/yarn.lock
packages/forma-36-website/yarn.lock

Yarn lockfiles are looking a little out of sync, will test to see if there are any issues with the component library Storybook or the documentation website before merging.

Update yarn lockfiles

---

packages/forma-36-react-components/yarn.lock
packages/forma-36-website/yarn.lock
yarn.lock

This PR will upgrade several dependencies.

chore(Dependencies): upgrade dependencies

---

packages/forma-36-react-components/src/alpha.ts
packages/forma-36-react-components/src/components/Grid/Grid.css
packages/forma-36-react-components/src/components/Grid/Grid.md
packages/forma-36-react-components/src/components/Grid/Grid.stories.tsx
packages/forma-36-react-components/src/components/Grid/Grid.test.tsx
packages/forma-36-react-components/src/components/Grid/Grid.tsx
packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.md
packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.stories.tsx
packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.test.tsx
packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.tsx
packages/forma-36-react-components/src/components/Grid/GridItem/__snapshots__/GridItem.test.tsx.snap
packages/forma-36-react-components/src/components/Grid/GridItem/index.ts
packages/forma-36-react-components/src/components/Grid/__snapshots__/Grid.test.tsx.snap
packages/forma-36-react-components/src/components/Grid/index.ts
packages/forma-36-react-components/src/index.ts

feat: Grid Components

---

packages/forma-36-react-components/src/components/Tabs/Tab.tsx
packages/forma-36-react-components/src/components/Tabs/Tabs.css
packages/forma-36-react-components/src/components/Tabs/Tabs.stories.tsx
packages/forma-36-react-components/src/components/Tabs/Tabs.test.tsx
packages/forma-36-react-components/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap

This PR fixes the disabled state of the tab component that had no impact visually on the component.

fix(Tab): Add disabled state for tab

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/proposal.md

This proposal adds some issue templates for the repo

chore(templates): Add Issue Templates

---

packages/forma-36-react-components/src/components/Button/Button.css
packages/forma-36-tokens/src/tokens/box-shadows/glows.js

This fixes the variable references bug discovered in [#441 ](https://github.com/contentful/forma-36/issues/441)

fix(button): CSS variable references in Button.css

---

packages/forma-36-react-components/src/components/Button/Button.css

Hey lovely people!
Just a small fix for Button in the focus state

fix(newColors): fix issue focus button

---

packages/forma-36-react-components/src/components/Notification/NotificationItem.css
packages/forma-36-react-components/src/components/Notification/NotificationItem.tsx
packages/forma-36-react-components/src/components/Notification/__snapshots__/NotificationItem.test.tsx.snap

fix: notification html semantic markup

fix: notification html semantic markup

---

packages/forma-36-react-components/README.md

This PR adds a section on how to use alpha components and sets some expectations on the usage of these.
Resolves #479

Add instructions for alpha components to readme

---

packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.stories.tsx
packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.tsx
packages/forma-36-react-components/src/components/Grid/GridItem/__snapshots__/GridItem.test.tsx.snap

GridItem:
- fix className
- fix stories
- add htmlTag prop

fix: GridItem className, stories, and add htmlTag prop

---

packages/components/forma-36-react-datepicker/yarn.lock
packages/components/forma-36-react-timepicker/yarn.lock
packages/forma-36-fcss/yarn.lock
packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/package.json
packages/forma-36-react-components/src/components/CopyButton/__snapshots__/CopyButton.test.tsx.snap
packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/__snapshots__/EditorToolbarButton.test.tsx.snap
packages/forma-36-react-components/src/components/Tooltip/README.md
packages/forma-36-react-components/src/components/Tooltip/Tooltip.css
packages/forma-36-react-components/src/components/Tooltip/Tooltip.stories.tsx
packages/forma-36-react-components/src/components/Tooltip/Tooltip.test.tsx
packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
packages/forma-36-react-components/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
packages/forma-36-react-components/yarn.lock
packages/forma-36-website/yarn.lock

Following up with some requests this PR is implementing [Popper.js ](https://popper.js.org/) to our Tooltip component so we don't need to deal with it's positioning
I feel disclaimers:
1. We needed to update storybook to an alpha version because apparently `usePopper` does not work with the latest stable version of storybook, more on this [here](https://github.com/storybookjs/storybook/issues/12475)
2. Popper.js documentation around react-popper and usePopper is... inexistent basically. [I'm not the only one complaining about this](https://github.com/popperjs/react-popper/issues/359)
So, I used other two sources to help me on this implementation. You can check them [here](https://davidcosta.com.br/en/using-popper-as-tooltip-typeScript-and-styled-component/) and [here behind Medium …

Refactor Tooltip component to use Popper.js

---

packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx

Add missing `...otherProps` to the tooltip

fix(tooltip): spread otherProps

---

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx

Introduce `size=auto` to EntryCard to achieve minimal height based on the props provided. This will maintain previous behaviour and gives us the opportunity to render long lists in a more narrow fashion.

feat(EntryCard): add size=auto to EntryCard

---

packages/forma-36-tokens/src/tokens/border-radius/border-radius.js

F36!
🤦‍♀️ 
Just fixing my own bug here

fix: namespace for new border-radius tokens

---

packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx

Add Release icon to entity list item icons

feat(EntityListItem): Add Release icon to entity type icon

---

packages/forma-36-react-components/src/components/Workbench/README.md
packages/forma-36-react-components/src/components/Workbench/Workbench.stories.tsx
packages/forma-36-react-components/src/components/Workbench/Workbench.tsx
packages/forma-36-react-components/src/components/Workbench/__snapshots__/Workbench.test.tsx.snap

Hey F36!
Just a refactor of the Workbench component story into the new format. Plus REAMDE - which is mainly taken from the website
Plus one small change in the component - this is I think what is breaking current storybook of this component. I've checked against prod and it works without problems after this change `WorkbenchHeader` to `Workbench.Header`

fix: update Workbench component

---

packages/forma-36-react-components/.eslintrc.js
packages/forma-36-react-components/package.json
packages/forma-36-react-components/yarn.lock

Add [`eslint-plugin-react-hooks`](https://reactjs.org/docs/hooks-rules.html#eslint-plugin) to help avoid common mistakes using hooks when developing.

build(eslint): add eslint-plugin-react-hooks

---

packages/forma-36-react-components/package.json
packages/forma-36-react-components/yarn.lock

Leverage the latest fixes from `react-modal` dependency.

chore: update react-modal to the latest

---

packages/components/forma-36-react-timepicker/yarn.lock
packages/forma-36-react-components/src/components/List/ListItem/ListItem.css

Adds a `list-style-type` to the `ListItem` component, which should resolve #549

fix(ListItem): specify list-style-type initial

---

packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx

I got the order wrong last time. Sorry 😓

fix(DropdownListItem): Change prop order again

---

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/__snapshots__/DropdownContainer.test.tsx.snap
packages/forma-36-react-components/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap

🤦‍♀️ `undefined` would disable the portal as well

fix(dropdowncontainer): explicitly check usePortal for false

---

packages/forma-36-react-components/package.json

[React 17 has no relevant breaking changes](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#other-breaking-changes), we should add it to Forma 36's allowed `peerDependencies` 😎

chore(deps): add support for React 17 peer dependency

---

README.md
package.json
packages/forma-36-react-components/package.json
yarn.lock

Clean up the old Travis stuff.

chore: remove Travis CI remnants

---

README.md

docs: fix CircleCI shield

---

packages/forma-36-react-components/tools/postcss.config.js
packages/forma-36-react-components/tsdx.config.js

Fix missing CSS variables
Fixes https://github.com/contentful/forma-36/issues/663

fix: proper styles.css build

---

packages/forma-36-react-components/src/components/Workbench/Workbench.css

Fixes https://github.com/contentful/create-contentful-app/issues/160

fix(Workbench-css): Wrap calc in parenthesis

---

packages/forma-36-react-components/src/components/Autocomplete/README.mdx

Fix a type in example code snippets.

Fix type in example code

---

.circleci/config.yml
package.json
yarn.lock

Installs https://www.chromatic.com/ for a visual regression testing

ci: install chromatic for visual regression testing

---

.circleci/config.yml
README.md

Simplifies and speeds up Circle CI configuration

ci: simplify and speed up CI

---

packages/forma-36-react-components/src/components/Dropdown/README.mdx

Just some typo in the Dropdown example code

fix(dropdown): typo in example

---

packages/forma-36-react-components/src/components/EmptyState/EmptyState.tsx
packages/forma-36-react-components/src/components/HelpText/HelpText.tsx
packages/forma-36-react-components/src/components/Icon/Icon.tsx
packages/forma-36-react-components/src/components/Illustration/Illustration.tsx
packages/forma-36-react-components/src/components/List/List.tsx
packages/forma-36-react-components/src/components/List/ListItem/ListItem.tsx
packages/forma-36-react-components/src/components/Modal/Modal.tsx
packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.tsx
packages/forma-36-react-components/src/components/Modal/ModalContent/ModalContent.tsx
packages/forma-36-react-components/src/components/Modal/ModalControls/ModalControls.tsx
packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.tsx
packages/forma-36-react-components/src/components/Note/Note.tsx
packages/forma-36-react-components/src/components/Pill/Pill.tsx
packages/forma-36-react-components/src/components/Skeleton/SkeletonContainer/SkeletonContainer.tsx
packages/forma-36-react-components/src/components/Skeleton/SkeletonDisplayText/SkeletonDisplayText.tsx
packages/forma-36-react-components/src/components/Skeleton/SkeletonImage/SkeletonImage.tsx
packages/forma-36-react-components/src/components/Skeleton/SkeletonText/SkeletonText.tsx
packages/forma-36-react-components/src/components/TabFocusTrap/TabFocusTrap.tsx
packages/forma-36-react-components/src/components/Tabs/Tab.tsx
packages/forma-36-react-components/src/components/Tabs/TabPanel.tsx
packages/forma-36-react-components/src/components/Tabs/Tabs.tsx
packages/forma-36-react-components/src/components/Tag/Tag.tsx
packages/forma-36-react-components/src/components/TextLink/TextLink.tsx
packages/forma-36-react-components/src/components/Typography/DisplayText/DisplayText.tsx
packages/forma-36-react-components/src/components/Typography/Heading/Heading.tsx
packages/forma-36-react-components/src/components/Typography/Paragraph/Paragraph.tsx
packages/forma-36-react-components/src/components/Typography/SectionHeading/SectionHeading.tsx
packages/forma-36-react-components/src/components/Typography/Subheading/Subheading.tsx
packages/forma-36-react-components/src/components/Typography/Typography/Typography.tsx
packages/forma-36-react-components/src/components/ValidationMessage/ValidationMessage.tsx

Refactors EmptyState, HelpText, Icon, Illustration, List, Modal, Note, Skeleton components, TabFocusTrap, Tabs, Tag, TextLink, Typography components, and ValidationMessage to function components as part of #651.
- Notification components

refactor: function components

---

packages/forma-36-website/src/components/DocFormatter.js

Frontmatter for GitHub and Storybook URLs were switched.

fix: fix storybook and github frontmatter url

---

packages/forma-36-react-components/src/components/Notification/NotificationItem.tsx
packages/forma-36-react-components/src/components/Notification/NotificationItemContainer.tsx
packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx
packages/forma-36-react-components/src/utils/useAsyncState.ts

Refactors notification components to function components.
Closes #651

refactor: notification function components

---

packages/forma-36-react-components/tools/plop-templates/components/readme.mdx.hbs

Small fix about the readme template

fix: update readme template

---

packages/components/forma-36-react-datepicker/src/Datepicker.tsx
packages/forma-36-react-components/src/components/Asset/AssetIcon/AssetIcon.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx
packages/forma-36-react-components/src/components/Workbench/Workbench.tsx

Refactor missed components to function components

refactor missed components to function components

---

.circleci/config.yml

Faster builds and proper cache reset between commits

ci: more optimized ci workflow

---

packages/forma-36-react-components/README.md
yarn.lock

chore: update yarn and update README

---

.nvmrc

This should let us update the nvmrc file less. What do you think?

chore: widen to LTS 14 in nvmrc

---

.circleci/config.yml

ci: fix pushing tags while publishing package

---

lerna.json

* Don't run CI after publishing for no reason. 
* Don't publish new package if the change is only in story, tests, or documentation

ci: don't run ci after publish and ignore non-code changes

---

packages/components/datepicker/package.json
packages/components/datepicker/src/Datepicker.tsx
packages/components/timepicker/package.json
packages/components/timepicker/src/Timepicker.tsx
yarn.lock

It turned out that emotion@11 and emotion@10 don't work well in one application, so we rollback to v10 until all our application want to use v11

fix: fallback to emotion@10 in timepicker and datepicker

---

packages/forma-36-react-components/src/components/Button/Button.css
packages/forma-36-react-components/src/components/Button/Button.stories.tsx
yarn.lock

Fix the issue with full width buttons
before:
after:
P.s.: I committed my yarn.lock because after pulling the last v3-visual-changes and running `yarn`, the lock file got updated so I think we forgot to commit it at some point

fix: aligment in full width buttons

---

packages/forma-36-react-components/src/components/Button/Button.css
packages/forma-36-react-components/src/components/Button/Button.stories.tsx
yarn.lock

Oops! My bad, I merged the other PR before @fabe taking a look on it
This is how the full-width button should look:

fix: full width button with centered content

---

packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx
packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx

Looks like a leftover that should've been removed already.

fix(dropdown-container): remove position prop

---

packages/forma-36-react-components/src/components/Button/Button.tsx
packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
packages/forma-36-react-components/src/components/Spinner/Spinner.css
packages/forma-36-react-components/src/components/Spinner/Spinner.tsx
packages/forma-36-react-components/src/components/Spinner/__snapshots__/Spinner.test.tsx.snap

refactor: make spinner three dots again

---

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.css
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx

Small fixes with the alignment of new tags and new borders

fix: small visual fixes in card components

---

packages/forma-36-react-components/src/components/Modal/Modal.tsx

Fix a regression introduced by #728

fix: return previous modal size logic

---

packages/forma-36-react-components/src/components/Notification/NotificationItemContainer.tsx

revert(notification-item-container): change back to class component

---

packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx
packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css
packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.css
packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.css

A refreshed look for dropdown - update borders, padding and add a small offset between container and trigger.

feat: dropdown visual updates

---

packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/src/components/TextLink/TextLink.css
packages/forma-36-react-components/src/components/TextLink/TextLink.stories.tsx

Proper hover states for all link colors.

fix: Text link v3 visual changes

---

packages/forma-36-react-components/src/components/CopyButton/CopyButton.tsx
packages/forma-36-react-components/src/components/Icon/Icon.tsx
packages/forma-36-react-components/src/components/IconButton/IconButton.stories.tsx
packages/forma-36-react-components/src/components/IconButton/IconButton.tsx

This PR, for now, has only changes in the documentation since IconButton is waiting for some decisions in the design part to be made

IconButton documentation updates

---

.github/CODEOWNERS

Add @nikazawila to code owners

chore: add Nika to code owners

---

packages/forma-36-react-components/src/components/ToggleButton/ToggleButton.css
packages/forma-36-react-components/src/components/ToggleButton/ToggleButton.stories.tsx
packages/forma-36-react-components/src/components/ToggleButton/ToggleButton.tsx
packages/forma-36-react-components/src/components/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap

* New borders, active & focus styles for ToggleButton component
* New `ToggleButton.Group` to group toggle buttons toghether

feat: toggle v3 changes

---

packages/forma-36-react-components/src/components/Card/Card.css

Small adjustment for Card selection.

fix: align Card focus, hover and selected states with the rest of new focused styles.

---

packages/forma-36-react-components/src/components/ControlledInputField/ControlledInputField.css
packages/forma-36-react-components/src/components/Pill/Pill.css

* Fix missing margin-right in production build (due to broken order in CSS)
* Apply proper borders to Pill component

fix: small v3 fixes

---

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap

* Design only changes for entry cards in v3

feat: entry card header

---

packages/forma-36-react-components/src/components/Tabs/Tabs.css
packages/forma-36-react-components/src/components/Tabs/Tabs.stories.tsx
packages/forma-36-react-components/src/components/Tabs/Tabs.tsx

feat(tabs): visual changes

---

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCardSkeleton.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCardSkeleton.tsx

Fixes EntryCard and AssetCard size issues that are found when testing latest `v3-visual-changes` in our main web application.

fix: entry card and asset card sizes

---

packages/forma-36-react-components/src/components/Button/Button.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap
packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap
packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/__snapshots__/EditorToolbarButton.test.tsx.snap
packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
packages/forma-36-react-components/src/components/IconButton/IconButton.css
packages/forma-36-react-components/src/components/IconButton/IconButton.stories.tsx
packages/forma-36-react-components/src/components/IconButton/IconButton.test.tsx
packages/forma-36-react-components/src/components/IconButton/IconButton.tsx
packages/forma-36-react-components/src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
packages/forma-36-react-components/src/components/Modal/__snapshots__/Modal.test.tsx.snap
packages/forma-36-react-components/src/components/Notification/__snapshots__/NotificationItem.test.tsx.snap

feat(icon-button): new visual styles

---

packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap
packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap
packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/__snapshots__/EditorToolbarButton.test.tsx.snap
packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
packages/forma-36-react-components/src/components/IconButton/IconButton.test.tsx
packages/forma-36-react-components/src/components/IconButton/IconButton.tsx
packages/forma-36-react-components/src/components/IconButton/__snapshots__/IconButton.test.tsx.snap
packages/forma-36-react-components/src/components/Modal/__snapshots__/Modal.test.tsx.snap
packages/forma-36-react-components/src/components/Notification/__snapshots__/NotificationItem.test.tsx.snap

Proper test id should be passed down from `IconButton` component

fix: update IconButton testId regression and update tests

---

packages/forma-36-react-components/src/components/Tabs/Tabs.css

fix(tabs): vertical text centering regardless of height

---

packages/forma-36-react-components/src/components/Table/Table.stories.tsx
packages/forma-36-react-components/src/components/Table/TableRow/TableRow.css
packages/forma-36-react-components/src/components/Table/TableRow/TableRow.tsx

fix(table-row): hover and select styling

---

packages/forma-36-react-components/src/components/Tabs/Tabs.css

fix(tabs): switch border-color to color-element-light

---

packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx

chore(tooltip): remove commented line

---

.github/ISSUE_TEMPLATE/proposal.md

Hey!
Just a small update to the proposal template.

docs: update proposal template

---

.github/ISSUE_TEMPLATE/proposal.md
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.stories.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.stories.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardActions.stories.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx
packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.stories.tsx
packages/forma-36-react-components/src/components/EmptyState/EmptyState.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityList.md
packages/forma-36-react-components/src/components/EntityList/EntityList.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.md
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/README.mdx
packages/forma-36-react-components/src/components/EntityList/README.mdx

Hey there Forma 36
Just a small refactor of a couple of components to the new stories format.

docs: refactor stories into the new format vol.1

---

packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/tools/postcss.config.js

Breaking change: use [`@contentful/browserslist-config`](https://github.com/contentful/browserslist-config/)

v4 feat(postcss): use @contentful/browserslist-config

---

packages/forma-36-react-components/src/components/ValidationMessage/ValidationMessage.stories.tsx

The ValidationMessage story seemed to be misconfigured and is erroring currently on the website. This PR fixes that.

chore(storybook): fix broken story

---

packages/forma-36-react-components/src/components/Checkbox/Checkbox.tsx
packages/forma-36-react-components/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap

fix(checkbox): change testId to match "cf" namespace

fix(checkbox): change testId to match "cf" namespace

---

packages/forma-36-react-components/.size-limit
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.stories.tsx
packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.tsx
packages/forma-36-react-components/src/components/Checkbox/Checkbox.tsx
packages/forma-36-react-components/src/components/CheckboxField/CheckboxField.tsx
packages/forma-36-react-components/src/components/ControlledInput/ControlledInput.tsx
packages/forma-36-react-components/src/components/ControlledInputField/ControlledInputField.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx
packages/forma-36-react-components/src/components/RadioButton/RadioButton.tsx
packages/forma-36-react-components/src/components/RadioButtonField/RadioButtonField.tsx

Breaking change: align prop interface names so we use the same naming everywhere.

v4 feat: align prop interface names

---

packages/forma-36-react-components/src/components/Portal/Portal.stories.tsx
packages/forma-36-react-components/src/components/Portal/Portal.tsx
packages/forma-36-react-components/src/components/Portal/README.mdx
packages/forma-36-react-components/src/components/Portal/__snapshots__/Portal.test.tsx.snap
packages/forma-36-react-components/src/index.ts
scripts/.storybook/preview.js

feat(portal): export for external consumption

feat(portal): export for external consumption

---

packages/forma-36-react-components/src/components/Flex/Flex.tsx

chore(flex): fix typo

---

packages/forma-36-react-components/src/components/Pill/Pill.css
packages/forma-36-react-components/src/components/Pill/Pill.stories.tsx
packages/forma-36-react-components/src/components/Pill/Pill.test.tsx
packages/forma-36-react-components/src/components/Pill/Pill.tsx
packages/forma-36-react-components/src/components/Pill/README.mdx
packages/forma-36-react-components/src/components/Pill/__snapshots__/Pill.test.tsx.snap

Adding `variant` property to `Pill` component. 
Implementation of https://github.com/contentful/forma-36/issues/585 (see comments from this year).

feat(pill): add pill states

---

packages/components/datepicker/package.json
packages/components/datepicker/src/Datepicker.tsx
packages/components/timepicker/package.json
packages/components/timepicker/src/Timepicker.tsx
packages/forma-36-react-components/src/components/Flex/Flex.stories.tsx
yarn.lock

Bring the `<Datepicker />` and `<Timepicker />` up to v4.

v4 feat: stable Timepicker and Datepicker

---

packages/components/datepicker/CHANGELOG.md
packages/components/timepicker/CHANGELOG.md
packages/forma-36-react-components/CHANGELOG.md
packages/forma-36-react-components/src/components/Card/Card.tsx
packages/forma-36-react-components/src/components/Card/__snapshots__/Card.test.tsx.snap

Add `rel` prop to card component

feat: add rel prop to card component

---

packages/components/badge/src/Badge.tsx
packages/components/badge/src/EntityStatusBadge.tsx
packages/components/badge/src/types.ts
packages/core/src/index.ts
packages/core/src/types.ts
packages/forma-36-react-components/src/components/Asset/Asset.tsx
packages/forma-36-react-components/src/components/Asset/index.ts
packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx
packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx

Adds common types to `@contentful/f36-core`. This could potentially be expanded to organization wide types at a later point.

feat: shared types

---

packages/components/badge/src/README.mdx
packages/components/badge/src/getBadgeStyles.ts
packages/components/badge/src/types.ts
packages/components/badge/stories/Badge.stories.tsx

Corresponding PR to bring featured variant to the Badge component for v4

feat: add featured variant to Badge

---

packages/core/src/types.ts
packages/forma-36-tokens/tools/build.js

Automatically generate token-based typescript types.

chore: generate token types

---

packages/components/datepicker/CHANGELOG.md
packages/components/timepicker/CHANGELOG.md
packages/forma-36-react-components/CHANGELOG.md
packages/forma-36-react-components/src/components/Button/README.mdx

Added clarification for button alignment to the section 'How to use Buttons'. These clarifications have been agreed upon with the design guild.

docs: Update README.mdx

---

packages/forma-36-react-components/src/components/Modal/Modal.stories.tsx
packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.stories.tsx

This fixes the issue mentioned in https://github.com/contentful/forma-36/issues/915

fix: storybook stories for Modal

---

packages/forma-36-react-components/src/components/Textarea/README.mdx

Updating incomplete README for Textarea, as part of @burakukula's documentation initiative.

docs: update README for Textarea

---

packages/forma-36-react-components/src/components/RadioButton/README.mdx
packages/forma-36-react-components/src/components/RadioButton/RadioButton.stories.tsx

Updating incomplete README for RadioButton, as part of @burakukula's documentation initiative.
-- unrelated to the PR: should we think about deprecating this component in v4?

docs: refine README for RadioButton

---

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx

fix(autocomplete): Disable chevron when autocomplete is disabled

---

packages/forma-36-react-components/src/components/IconButton/IconButton.tsx

Hey!
A little issue that I face on the client side.

fix: allow target for IconButton

---

packages/components/button/README.mdx
packages/components/button/index.ts
packages/components/button/package.json
packages/components/button/src/Button.tsx
packages/components/button/src/index.ts
packages/components/button/src/styles.ts
packages/components/button/src/types.ts
packages/components/button/stories/Button.stories.tsx
packages/components/button/test/Button.test.tsx
packages/forma-36-react-components/src/components/Button/Button.stories.tsx
packages/forma-36-react-components/src/components/Button/Button.tsx

refactor: button component

---

packages/forma-36-website/src/pages/index.jsx

docs: fix GitHub format

---

packages/components/timepicker/stories/Timepicker.stories.tsx

This looks completely unstyled by the way, is there some kind of import missing like with the Datepicker?

v4: add Timepicker to Storybook

---

packages/forma-36-react-components/src/components/Illustration/README.mdx

Adding some docs to `Illustration`

docs: add documentation for Illustration

---

packages/forma-36-react-components/src/components/Tabs/README.mdx

docs: add documentation for Tabs

---

packages/forma-36-react-components/src/components/Checkbox/README.mdx

docs: Checkbox README

---

packages/forma-36-react-components/src/components/Table/README.mdx

Small adjustment for the Table README

docs: adjust table README to the new template structure

---

.github/dependabot.yml

Removes link to a broken NPM registry

chore: fix dependabot configuration

---

packages/components/icons/src/Table.tsx

feat(icons v4): add table icon

---

.github/dependabot.yml

build(dependabot): remove nonexistent label

build(dependabot): remove nonexistent label

---

package.json
yarn.lock

chore(dependencies): remove babel-plugin-inline-react-svg

---

packages/components/icon/README.mdx
packages/components/icons/README.mdx
packages/forma-36-react-components/src/components/Card/Card.stories.tsx

docs: Fix icons README and card story

---

packages/components/button/package.json
packages/components/button/src/Button.tsx
packages/components/button/stories/Button.stories.tsx

fix(button): rename disabled prop to align with style guide

fix(button): rename disabled prop to align with style guide

---

packages/forma-36-react-components/src/components/Tag/Tag.css

Fix background and text color for Tags.

fix: fix issue with Tags

---

packages/forma-36-react-components/src/components/Card/Card.stories.tsx

docs: remove Text margin from Card stories

---

packages/forma-36-tokens/MIGRATION.md

Migration notes for tokens. WDYT?

feat: migration notes

---

packages/forma-36-react-components/src/components/Icon/Icon.css
packages/forma-36-react-components/src/components/IconButton/IconButton.css
packages/forma-36-react-components/src/components/TextLink/TextLink.css

Fixing issue with icons in Toggle and Link.
In order to do it I needed to update Icon.
I also fixed issue with broken hover for IconButton.

fix: fix issue with icons for IconButton, Toggle and Link

---

babel.config.js
packages/forma-36-react-components/.babelrc
packages/forma-36-react-components/package.json
yarn.lock

- fix: add `@contentful/f36-note` to dependencies
- chore: update lockfile
- build: don't use loose mode

build: fix noise from babel in v4 branch

---

packages/components/drag-handle/README.mdx
packages/components/drag-handle/index.ts
packages/components/drag-handle/package.json
packages/components/drag-handle/src/DragHandle.styles.ts
packages/components/drag-handle/src/DragHandle.tsx
packages/components/drag-handle/src/index.ts
packages/components/drag-handle/stories/DragHandle.stories.tsx
packages/components/drag-handle/test/DragHandle.test.tsx
packages/forma-36-react-components/package.json
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.css
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
packages/forma-36-react-components/src/index.ts

Extracted `CardDragHandle` to a separate package since it's also being used in `EntityListItem`.

feat: extract DragHandle component

---

packages/components/forms/package.json
packages/components/inputs/package.json
packages/components/inputs/src/controlled-input/ControlledInput.tsx
packages/components/note/package.json
packages/components/note/src/Note.styles.tsx
packages/components/note/src/Note.tsx

fix: add missing deps to packages

---

packages/forma-36-website/package.json

chore(deps): fix website build by upgrading tokens

---

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx

fix(dropdown-container): check for ref before calling focus

---

docs/code-style-guide.md
packages/forma-36-react-components/README.md

- Move our new code style guide to github, in order to get more visibility and contribution. 
- I've also introduced some changes so discussions are highly welcomed!

docs: move/update code style guide

---

packages/components/badge/src/Badge.tsx
packages/components/badge/src/getBadgeStyles.ts
packages/components/drag-handle/src/DragHandle.tsx
packages/components/empty-state/src/EmptyState.tsx
packages/forma-36-react-components/src/components/Table/TableHead/TableHead.css

Small clean up for code and approach consistency

chore: clean up for consistency

---

.eslintrc.js
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
packages/forma-36-react-components/src/components/Modal/Modal.tsx
packages/forma-36-react-components/src/components/Notification/NotificationItemContainer.tsx
packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx

According to our code style, all event handlers should start from 'handle' and properties should start from 'on'.
This PR introduces an ESLint rule that verifies that.

chore: enforce callback codestyle

---

packages/components/badge/src/README.mdx
packages/components/button/README.mdx
packages/components/icon/README.mdx
packages/f36-docs-utils/src/Props/Props.tsx
packages/f36-docs-utils/src/Props/PropsProvider.tsx
packages/f36-docs-utils/src/Props/types.ts

When showing the properties table on the documentation site, filter out all native HTML attributes.

feat: filter out all polymorphic props

---

.eslintrc.js
.prettierignore
packages/forma-36-codemod/README.md
packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/package.json
packages/forma-36-codemod/transforms/__testfixtures__/v4-text-link.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-text-link.output.js
packages/forma-36-codemod/transforms/__tests__/v4-text-link.test.js
packages/forma-36-codemod/transforms/v4-text-link.js
packages/forma-36-codemod/utils/__tests__/getComponentLocalName.test.js
packages/forma-36-codemod/utils/addImport.js
packages/forma-36-codemod/utils/addProperty.js
packages/forma-36-codemod/utils/changeImport.js
packages/forma-36-codemod/utils/changeProperties.js
packages/forma-36-codemod/utils/deleteProperty.js
packages/forma-36-codemod/utils/getComponentLocalName.js
packages/forma-36-codemod/utils/getProperty.js
packages/forma-36-codemod/utils/hasProperty.js
packages/forma-36-codemod/utils/index.js
packages/forma-36-codemod/utils/removeComponentImport.js
packages/forma-36-codemod/utils/renameProperties.js
packages/forma-36-codemod/utils/updateIcons.js
packages/forma-36-codemod/utils/updatePropertyValue.js
yarn.lock

Adds a codemod to migrate TextLink component to v4.
Adds reusable functions that can be used in other codemods.

feat: text link codemod 

---

packages/components/button/package.json
packages/components/copybutton/package.json
packages/components/drag-handle/package.json
packages/components/empty-state/package.json
packages/components/helptext/package.json
packages/components/list/package.json
packages/components/note/package.json
packages/components/pill/package.json
packages/components/skeleton/package.json
packages/components/spinner/package.json
packages/components/table/package.json
packages/components/tabs/package.json
packages/components/text-link/package.json
packages/components/tooltip/package.json
packages/components/validation-message/package.json
scripts/plop-templates/package/package.json.hbs

chore: remove private labels for publishable packages

---

packages/forma-36-codemod/bin/cli.js
packages/forma-36-codemod/transforms/__tests__/v4-text-link.test.js
packages/forma-36-codemod/transforms/v4-text-link.js
packages/forma-36-codemod/utils/config.js

To be able to skip some steps (that we don't need internally in Compose) using env variables.

feat: improve TextLink codemod

---

packages/forma-36-react-components/src/components/DateTime/README.mdx
packages/forma-36-website/src/components/Container.js
packages/forma-36-website/src/components/StaticSource.js

We are providing this in v4, I guess we could do it in v3 already to some errors on the website? WDYT?

docs: provide StaticSource component to solve some issues in docs

---

packages/components/icons/src/Gift.tsx
packages/components/text-link/TextLink.mdx
packages/components/text-link/src/TextLink.styles.ts
packages/components/text-link/src/TextLink.tsx
packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap
packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/components/DocFormatter.js

Fixes small regressions that were found while integrating the TextLink component.

fix: small text link adjustments

---

packages/forma-36-codemod/transforms/__testfixtures__/v4-badge.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-badge.output.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-text-link.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-text-link.output.js
packages/forma-36-codemod/transforms/v4-badge.js

Finishes codemod for Badge component to cover all the cases.

feat(codemod): Migrate Badge with entityStatus

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-pill.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-pill.output.js
packages/forma-36-codemod/transforms/__tests__/v4-pill.test.js
packages/forma-36-codemod/transforms/v4-pill.js

Adds codemod to be used to migrate `Pill` component, since it had no breaking change and only style changes, we only need to update the import

feat(codemod): pill codemod

---

packages/forma-36-website/src/components/Navigation.js

Quality of life improvement, which scrolls the navigation into view when navigating. Previous behaviour reset the scroll position to the top, so the active item was not in view.

feat: scroll navigation into view in f36 website

---

packages/forma-36-react-components/src/components/Skeleton/SkeletonRow/__snapshots__/SkeletonRow.test.tsx.snap
packages/forma-36-react-components/src/components/Table/TableCell/TableCellContext.ts
packages/forma-36-react-components/src/components/Table/TableCell/__snapshots__/TableCell.test.tsx.snap
packages/forma-36-react-components/src/components/Table/TableHead/TableHead.tsx
packages/forma-36-react-components/src/components/Table/TableHead/__snapshots__/TableHead.test.tsx.snap

Only sets `offsetTop` on `th` elements when `isSticky` is `true`. 
Closes #1113

fix(table-head): only set offsetTop for th when isSticky is true

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-list.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-list.output.js
packages/forma-36-codemod/transforms/__tests__/v4-list.test.js
packages/forma-36-codemod/transforms/v4-list.js

This PR creates codemod for List component

chore(codemod-v4-list): add codemod for transforming List component from v3 to v4

---

packages/forma-36-website/gatsby-node.js
packages/forma-36-website/src/components/Container.js
packages/forma-36-website/src/components/Layout.css
packages/forma-36-website/src/components/Layout.js

It removes some unnecessary html tags from Layout component and it styles the `code` tag to look more like Github inline code
before:
after:

docs: v4 website UI improvements

---

packages/components/button/src/Button.tsx
packages/components/pill/package.json
packages/components/pill/src/Pill.tsx
packages/components/pill/src/styles.ts
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap

Removes TabFocusTrap from `Pill` component.
Updates focused style to match `<Button variant="transparent" />`

fix(pill): small visual improvements

---

packages/components/skeleton/stories/SkeletonRow.stories.tsx
packages/components/table/Table.mdx
packages/components/table/src/CompoundTable.tsx
packages/components/table/src/index.ts
packages/components/table/stories/Table.stories.tsx
packages/components/table/test/Table.test.tsx
packages/f36-docs-utils/src/Props/Props.tsx

* Export Table component as a compound component and update stories, tests, and examples.
* Still export all components separately for backward compatible reasons.

feat: Table compound

---

packages/components/accordion/Accordion.mdx
packages/components/accordion/src/CompoundAccordion.tsx
packages/components/accordion/src/index.ts
packages/components/accordion/stories/Accordion.stories.tsx
packages/components/accordion/test/Accordion.test.tsx
packages/components/list/List.mdx
packages/components/list/src/CompoundList.tsx
packages/components/list/src/index.ts
packages/components/list/stories/List.stories.tsx
packages/components/tabs/src/CompoundTabs.tsx
packages/components/tabs/src/Tabs.mdx
packages/components/tabs/src/index.ts
packages/components/tabs/stories/Tabs.stories.tsx
packages/components/tabs/test/Tabs.test.tsx
packages/core/src/Grid/CompoundGrid.tsx
packages/core/src/Grid/Grid.mdx
packages/core/src/Grid/index.ts
packages/core/stories/Grid.stories.tsx
packages/core/stories/GridItem.stories.tsx
packages/forma-36-codemod/transforms/__testfixtures__/v4-list.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-list.output.js
packages/forma-36-website/src/components/Container.js

Makes `Grid`, `Tabs`, `List`, and `Accordion` to follow a compound component pattern.

refactor: compound components

---

packages/components/popover/Popover.mdx
packages/components/popover/src/CompoundPopover.tsx
packages/components/popover/src/index.ts
packages/components/popover/stories/Popover.stories.tsx
packages/components/popover/test/Popover.test.tsx

chore(Popover): make Popover compound

---

packages/forma-36-react-components/src/components/Workbench/Workbench.tsx
packages/forma-36-react-components/src/components/Workbench/__snapshots__/Workbench.test.tsx.snap

feat: add default id to workbench [SPA-237]

---

packages/components/forms/src/base-checkbox/BaseCheckbox.tsx
packages/components/forms/src/checkbox/Checkbox.tsx
packages/components/forms/src/form-control/FormControl.tsx
packages/components/forms/src/form-label/FormLabel.tsx
packages/components/forms/src/radio/Radio.tsx
packages/components/forms/src/switch/Switch.tsx
packages/components/forms/stories/FormControl.stories.tsx
packages/forma-36-react-components/src/components/Form/FieldGroup/__snapshots__/FieldGroup.test.tsx.snap

Use `useFormControl` in Radio, Checkbox and Switch components

feat: Form control checkbox

---

packages/components/accordion/src/AccordionHeader/AccordionHeader.styles.ts
packages/components/forms/src/help-text/HelpText.tsx
packages/components/list/src/ListItem/ListItem.tsx
packages/components/modal/src/ModalContent/ModalContent.styles.ts
packages/components/table/src/TableCell.tsx
packages/components/tooltip/src/Tooltip.styles.ts
packages/components/typography/src/Text.tsx
packages/core/package.json
packages/core/src/GlobalStyles/GlobalStyles.tsx
packages/core/src/GlobalStyles/index.ts
packages/core/src/index.ts
packages/core/stories/Box.stories.tsx
packages/core/stories/Flex.stories.tsx
packages/core/stories/Grid.stories.tsx
packages/forma-36-react-components/src/components/Card/Card.stories.tsx
packages/forma-36-tokens/src/tokens/typography/font-base.js
packages/forma-36-website/src/components/Layout.css
packages/forma-36-website/src/components/Layout.js
packages/forma-36-website/src/content/foundation/typography/index.mdx
scripts/.storybook/preview.js
yarn.lock

Introduces a GlobalStyles component that allows to override all default styles in the browser and set a correct default font-size and font-family.

feat: add GlobalStyles

---

packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.test.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/README.mdx
packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
packages/forma-36-react-components/src/components/EntityList/README.mdx

Use Menu in EntityList component.
EnitityList component will be migrated to a separate package in another PR.

feat: Use Menu in EntityList

---

packages/components/modal/src/CompoundModal.tsx
packages/components/modal/src/Modal.tsx
packages/components/modal/src/ModalConfirm/ModalConfirm.tsx
packages/components/modal/src/index.ts
packages/components/modal/stories/Modal.stories.tsx
packages/components/modal/stories/ModalLauncher.stories.tsx

Previous compound implementation produced wrong types and typescript was complaining on the consumer side.

fix: proper compound modal

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-modal.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-modal.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/common/pipe.js
packages/forma-36-codemod/transforms/v4-list.js
packages/forma-36-codemod/transforms/v4-modal.js

Implements Modal codemod for v3 => v4 migration

feat: Modal codemod

---

packages/components/forms/package.json
packages/components/forms/src/base-checkbox/BaseCheckboxGroup.tsx
packages/components/forms/src/base-checkbox/BaseCheckboxGroupContext.tsx
packages/components/forms/src/checkbox/Checkbox.tsx
packages/components/forms/src/checkbox/CheckboxGroup.tsx
packages/components/forms/src/radio/Radio.tsx
packages/components/forms/src/radio/RadioGroup.tsx
packages/components/forms/stories/ReactHookForm.stories.tsx
packages/components/forms/stories/ReactHookFormControlledInputs.stories.tsx
packages/components/forms/test/ReactHookForm.test.tsx
yarn.lock

Integrates our Form Elements with react-hook-form and creates tests for them
I will add documentation in the Website in another PR

docs: add react-hook-form examples in storybook

---

packages/components/forms/package.json
packages/components/forms/src/checkbox/Checkbox.mdx
packages/components/forms/src/radio/Radio.mdx
packages/components/forms/stories/Formik.stories.tsx
packages/components/forms/test/Formik.test.tsx
packages/components/forms/test/ReactHookForm.test.tsx
yarn.lock

Integrates our Form Elements with Formik and creates tests for them
I will add documentation in the Website in another PR

docs: add Formik examples in storybook 

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/content/integrations/formik/index.mdx

This PR adds a small example on how to implement Formik with Forma 36

docs: add formik integration page in f36 website

---

packages/forma-36-website/gatsby-browser.js

This PR enables hotjar to Forma 36’s website so we can get heatmaps information to improve the website UX

feat: enable hotjar in production via Segment

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-typography.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-typography.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/common/modify-props-codemod.js
packages/forma-36-codemod/transforms/v4-flex.js
packages/forma-36-codemod/transforms/v4-spinner.js
packages/forma-36-codemod/transforms/v4-typography.js
packages/forma-36-codemod/utils/changeProperties.js

Codemod for Typography v3 => v4 migration.

feat: Typography codemod

---

packages/components/table/src/TableRow.tsx
packages/components/table/stories/Table.stories.tsx
packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-grid.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-grid.output.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-skeleton.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-skeleton.output.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-table.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-table.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-grid.js
packages/forma-36-codemod/transforms/v4-skeleton.js
packages/forma-36-codemod/transforms/v4-table.js

Codemods for Table, Grid, and Skeleton components.

feat: codemods for Table, Grid and Skeleton

---

packages/components/button/src/IconButton/IconButton.tsx
packages/components/button/src/IconButton/README.mdx
packages/components/button/src/IconButton/index.ts
packages/components/button/src/index.ts
packages/components/button/stories/ButtonGroup.stories.tsx
packages/components/button/stories/IconButton.stories.tsx
packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap
packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap
packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap
packages/forma-36-website/gatsby-config.js

feat(iconbutton): create IconButton component

---

packages/forma-36-codemod/transforms/__testfixtures__/v4-icon.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-icon.output.js
packages/forma-36-codemod/transforms/v4-icon.js
packages/forma-36-codemod/utils/updateIcons.js

feat: Icons codemod

---

packages/components/forms/src/base-input/BaseInput.tsx

Call original `onFocus` event for TextInput and TextArea component

fix(TextInput): call original onFocus

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-text-inputs.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-text-inputs.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-text-inputs.js
packages/forma-36-codemod/utils/renameProperties.js

`TextInput` and `Textarea` codemods.

feat: TextInput & Textarea codemods

---

packages/components/menu/src/MenuList/MenuList.tsx

More relaxed types to allow one Menu.Item as a child of Menu.List

fix(Menu): Allow single menu item

---

packages/components/autocomplete/src/Autocomplete.tsx

refactoring suggestions for Autocomplete component

v4/autocomplete PR suggestions

---

packages/components/button/stories/IconButton.stories.tsx
packages/forma-36-codemod/transforms/__testfixtures__/v4-icon-button.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-icon-button.output.js
packages/forma-36-codemod/transforms/v4-icon-button.js

Fix missing rename of prop on IconButton codemod

fix(codemod): fix iconbutton codemod

---

packages/components/forms/src/form/Form.mdx
packages/components/forms/src/text-input/TextInput.mdx
packages/components/modal/src/Modal.mdx
packages/forma-36-react-components/src/components/Dropdown/README.mdx
packages/forma-36-website/src/components/DocSearch.jsx

Fixes some issues on the documentation website.

fix: some issues on f36 website

---

packages/components/card/package.json
packages/components/card/src/asset-card/AssetCard.styles.ts
packages/components/card/src/asset-card/AssetCard.tsx
packages/components/card/src/base-card/BaseCard.styles.ts
packages/components/card/src/base-card/BaseCard.tsx
packages/components/card/src/entry-card/EntryCard.tsx
packages/components/card/src/inline-entry-card/InlineEntryCard.styles.ts
packages/components/card/src/inline-entry-card/InlineEntryCard.tsx
packages/components/card/stories/AssetCard.stories.tsx
packages/components/card/stories/Card.stories.tsx
packages/components/card/stories/EntryCard.stories.tsx
packages/components/card/stories/InlineEntryCard.stories.tsx

Add `isLoading` state for `Card` components

feat(card) Card isLoading state

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/package.json
packages/forma-36-codemod/transforms/__testfixtures__/v4-select.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-select.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-select.js
packages/forma-36-codemod/utils/createComponent.js
packages/forma-36-codemod/utils/index.js
yarn.lock

feat(codemod): add select and selectField codemod

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-checkbox.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-checkbox.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-checkbox.js

Codemod for CheckboxField. 
Looking at the implementation of the Checkbox, I think we need to migrate it manually. I came across couple of cases like:
```
<label>
<Checkbox />
<span>label text</span>
</label>
```
Based on that I think it does not make much sense to write codemod for this component since we would need to manually change it anyway.

feat: checkbox field codemod

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-form.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-form.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-form.js

feat: codemod for Form component

---

packages/components/menu/Menu.mdx
packages/components/menu/src/Menu.tsx
packages/components/menu/src/MenuContext.ts
packages/components/menu/src/MenuItem/MenuItem.tsx
packages/components/menu/stories/Menu.stories.tsx
packages/components/menu/test/Menu.test.tsx
packages/components/utils/src/ArrowKeyNavigation/useArrowKeyNavigation.ts

feat: v4/Menu focused item

---

packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-radio.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4-radio.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-checkbox.js
packages/forma-36-codemod/transforms/v4-radio.js
packages/forma-36-codemod/transforms/v4-select.js

* Add Radio codemod
* Fix issue when some props were expressions and we had to pass as children

feat(codemod): add Radio codemod

---

packages/forma-36-fcss/README.md

docs(forma 36 fcss readme): add @contentful/forma-36-fcss install instruction

---

packages/forma-36-website/gatsby-config.js

Forma 36 Components [survey](https://docs.google.com/forms/d/e/1FAIpQLSfYVm_bfPGt-LcjGDYjjsKEUk7pAHx9Xo15AvcpIag2hhyQ2Q/viewform?usp=sf_link) to run for 2 weeks.

docs: update website with Forma 36 components survey

---

.circleci/config.yml
lerna.json
package.json

- Add release script
- Make beta publishing manual

chore: manual beta publishing

---

docs/folder-structure.md
scripts/plop-templates/package/src/Component.test.tsx.hbs

Following our poll regarding where to store test files, I updated the folder structure guide
We will need to move some files and folders around, but do not worry I will create a task for Bauhaus to do this as part of our documentation epic 👌

docs: add convention regarding test files

---

packages/components/card/src/base-card/BaseCard.styles.ts
packages/components/card/src/base-card/BaseCard.tsx
packages/components/card/src/base-card/BaseCard.types.ts
packages/components/card/stories/AssetCard.stories.tsx
packages/components/card/stories/Card.stories.tsx
packages/components/card/stories/EntryCard.stories.tsx
packages/components/card/stories/InlineEntryCard.stories.tsx

Small fixes for keyboard navigation for Card.
Removing `isFocused` property - are there any cases where we actually need to control this property?

fix: fix card issues

---

MIGRATION.md

docs: replace next-v4 tag with beta in migration guide

---

packages/forma-36-website/src/content/migration-v3-to-v4.mdx

Small adjustments after @alstaicu  review.

fix: Fix website migration page

---

packages/forma-36-website/src/components/ComponentSource.js

Following up on some feedbacak we got regarding discoverability in our docs
I created this simple PR that renders the pages with the source code for the examples open initially

docs: show source code

---

packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/components/Footer.js
packages/forma-36-website/src/content/guidelines/contributing.mdx
packages/forma-36-website/src/pages/index.jsx

This PR adds a page describing how people can contribute to Forma 36 🙌

[BAU-297] docs: add contribution guide page

---

packages/components/card/src/base-card/DefaultCardHeader.tsx

Don't render card actions if actions is an empty array

fix: don't render empty actions

---

packages/forma-36-website/src/content/migration-v3-to-v4.mdx

Suggestion to make it easier to read the list of migration guides

docs: change migration guide layout

---

packages/components/typography/src/DisplayText.tsx
packages/components/typography/src/Heading.mdx
packages/components/typography/src/Paragraph.mdx
packages/components/typography/src/SectionHeading.mdx
packages/components/typography/src/SectionHeading.tsx
packages/components/typography/src/Subheading.tsx
packages/components/typography/src/Text.mdx

- some fixes to default tags for typography components
- small adjustments in README files for those

fix: fix default tags for typography

---

packages/forma-36-codemod/README.md
packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-asset-card.output.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-entry-card.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-entry-card.output.js
packages/forma-36-codemod/transforms/__tests__/v4.test.js
packages/forma-36-codemod/transforms/v4-entry-card.js

A codemod for `EntryCard` component

feat: entry card codemod

---

MIGRATION.md
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

It adds the migration guide for Tooltip

[BAU-327] docs: tooltip migration guide

---

MIGRATION.md
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

I merged the migration guide for tooltip before @alstaicu could review it 🤦 
So now I'm updating it with her suggestions 🙌

docs: tooltip migration guide updates

---

MIGRATION.md
packages/components/menu/Menu.mdx
packages/components/menu/src/Menu.tsx
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

- Dropdown migration docs
- Minor fix for Menu fully controlled behaviour

docs: Dropdown migration to v4

---

MIGRATION.md
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

Adding migration guide for Tabs component

Migration guide for tabs

---

MIGRATION.md
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

Added documentation for migration of Spinner and Skeleton components.

chore(migration): add migration guides for Spinner and Skeleton components

---

.circleci/config.yml
package.json

Return auto release on each commit for beta tag

chore: adjust auto release

---

MIGRATION.md
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

Migration documentation for components Asset and Pill.

chore(migration-guides): added migration guides for Asset and Pill components

---

packages/forma-36-codemod/bin/cli.js
packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/transforms/v4-all.js

Extend to have an option to run all existing codemods.
In the future:
- cleanup package.json
- remove CSS imports (there is function for that that is commented out)

feat: add option to run all codemods

---

packages/forma-36-website/src/content/migration-v3-to-v4.mdx

Adjustment of the migration page after feedback from tech writter

fix: adjust migration page to feedback

---

MIGRATION.md

docs: fix contentful typo in the migration guide

---

packages/components/workbench/src/Workbench.tsx
packages/components/workbench/src/WorkbenchContent/WorkbenchContent.tsx
packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.tsx
packages/components/workbench/src/WorkbenchSidebar/WorkbenchSidebar.tsx

adds displayName to compound exported components so they can be recognized.

fix(Worbench): name exports

---

MIGRATION.md
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

docs: v4 accordion migration

---

packages/forma-36-codemod/README.md
packages/forma-36-codemod/bin/cli.js
packages/forma-36-codemod/bin/inquirer-choices.js
packages/forma-36-codemod/bin/packages-list.js
packages/forma-36-codemod/bin/updateDependencies.js
packages/forma-36-codemod/package.json
packages/forma-36-codemod/transforms/v4-all.js
packages/forma-36-codemod/transforms/v4-clean-css.js

This PR adds possibility to update packages through the codemod.
Also adds option to pass or select multiple codemods.

feat(codemod): add option to update packages on codemod

---

MIGRATION.md

Final updates to overall spelling and grammar of migration notes.

docs(migration-notes): final updates to migration notes

---

packages/components/autocomplete/stories/Autocomplete.stories.tsx
packages/components/forms/stories/Form.stories.tsx
packages/components/forms/stories/FormControl.stories.tsx
packages/components/forms/stories/Formik.stories.tsx
packages/components/forms/stories/ReactHookForm.stories.tsx
packages/components/forms/stories/ReactHookFormControlledInputs.stories.tsx
packages/components/menu/stories/Menu.stories.tsx
packages/components/modal/stories/ModalLauncher.tsx
packages/components/note/stories/Note.stories.tsx
packages/components/pill/stories/Pill.stories.tsx
packages/components/text-link/stories/TextLink.stories.tsx

Fix some typos in the storybook - checked storybook files with a spellchecker.

fix(storybook): fix typos in storybook files

---

packages/forma-36-codemod/bin/packages-list.js

Make the codemod install the latest version, since we are still releasing fixes and changes, it's better than to have a fixed version

chore(codemod): update which version of packages the codemod install

---

MIGRATION.md
packages/forma-36-codemod/transforms/v4-entity-list.js
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

`EntityList` component migration docs.

docs: EntityList

---

packages/core/src/GlobalStyles/GlobalStyles.mdx
packages/core/src/GlobalStyles/GlobalStyles.tsx
packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/content/getting-started.mdx

Add documentation page for GlobalStyles core component

docs(globalstyles): add documentation for GlobalStyles

---

MIGRATION.md
packages/components/copybutton/src/CopyButton.tsx
packages/components/entity-list/src/EntityListItem/EntityListItem.tsx
packages/forma-36-codemod/transforms/v4-all.js
packages/forma-36-website/src/content/integrations/formik/index.mdx
packages/forma-36-website/src/content/migration-v3-to-v4.mdx

- fixes for formik example
- small changes to fix a11y issues
- bunch of improvements and missing content for migration guides

fix: adjustments in migration guide

---

packages/forma-36-website/src/components/Layout.styles.js
packages/forma-36-website/src/components/SpacingTokensTable.js
packages/forma-36-website/src/content/foundation/spacing/index.mdx

It updates the "Spacing" page with examples and the updated name of our tokens

BAU-400 docs: update spacing page

---

packages/core/src/ScreenReaderOnly/ScreenReaderOnly.tsx

Use relative import to avoid recursive import

fix: wrong import in ScreenReaderOnly

---

package.json
packages/website/package.json
yarn.lock

Fixes problem with Gasby v4 documentation

fix: downgrade react

---

packages/components/card/src/inline-entry-card/InlineEntryCard.mdx
packages/forma-36-website/gatsby-config.js

Adds docs for `InlineEntryCard` component.

docs(inline-entry-card): add docs for InlineEntryCard

---

netlify.toml
package.json
packages/forma-36-website/netlify.toml
packages/website/netlify.toml
yarn.lock

this plugin is necessary to deploy the next js website in netlify for some reason 🤷 
https://www.netlify.com/blog/2020/11/30/how-to-deploy-next.js-sites-to-netlify/

[BAU-484] chore: install netlify plugin for next js deployment

---

packages/components/accordion/Accordion.mdx
packages/components/badge/Badge.mdx
packages/components/badge/EntityStatusBadge.mdx
packages/components/menu/Menu.mdx
packages/core/src/Stack/Stack.tsx
packages/f36-docs-utils/package.json
packages/f36-docs-utils/src/PropsHeading/PropsHeading.tsx
packages/f36-docs-utils/src/PropsHeading/index.ts
packages/f36-docs-utils/src/index.ts
packages/forma-36-website/gatsby-config.js

- New docs page for `EntityStatusBadge`
- New `PropsHeading` component for docs.
- Fix for `Stack` component types

docs: entity status badge

---

package.json
packages/website/utils/content.ts
yarn.lock

Use https://turborepo.com/ for build command.

chore: add turborepo

---

packages/website/components/Layout.tsx
packages/website/pages/[...slug].tsx
packages/website/pages/_app.tsx
packages/website/pages/index.tsx

Implements this Grid for the new website. Should be easy to place future components and pages inside those areas 👌

[BAU-489] feat: implement a layout grid for the next js website

---

packages/components/accordion/package.json
packages/components/accordion/src/AccordionPanel/AccordionPanel.styles.ts
packages/components/accordion/src/AccordionPanel/AccordionPanel.tsx
packages/components/collapse/Collapse.mdx
packages/components/collapse/README.md
packages/components/collapse/package.json
packages/components/collapse/src/Collapse.styles.ts
packages/components/collapse/src/Collapse.tsx
packages/components/collapse/src/index.ts
packages/components/collapse/stories/Collapse.stories.tsx
packages/forma-36-website/gatsby-config.js

This introduces a new basic component called "collapse" and like popover can be used in other components e.g. accordion.
https://user-images.githubusercontent.com/1789174/145439651-0e0de883-832e-4794-9483-7f7f545eb1af.mov

Feat new component collapse v4

---

packages/website/components/Layout.tsx
packages/website/components/MdxRenderer.tsx
packages/website/components/Topbar.tsx
packages/website/pages/[...slug].tsx

Start of styling MDX pages for Next.js website.
Copies existing styles for the Header component.

feat: styling content nextjs and copy header component

---

packages/website/package.json
packages/website/pages/_document.tsx
yarn.lock

Inline critical styles for Next.js website.

fix: proper inline styles for next.js

---

packages/website/pages/_document.tsx

Solve problem introduced by a concurrent merges of several PRs.

fix: add missing react import

---

packages/website/components/PageContent.tsx
packages/website/components/Sidebar.tsx
packages/website/content/deprecated-components/dropdown.mdx
packages/website/content/deprecated-components/editor-toolbar.mdx
packages/website/content/deprecated-components/empty-state.mdx
packages/website/content/deprecated-components/illustration.mdx
packages/website/content/deprecated-components/in-viewport.mdx
packages/website/content/deprecated-components/tab-focus-trap.mdx
packages/website/content/deprecated-components/tag.mdx
packages/website/content/deprecated-components/typography.mdx
packages/website/utils/sidebarLinks.json

feat: bring back deprecated components section

---

packages/components/menu/Menu.mdx
packages/components/menu/examples/BasicMenu.tsx
packages/components/menu/examples/ControlledMenu.tsx
packages/components/menu/examples/ControlledMenuWithCustomTriggerLogic.tsx
packages/components/menu/examples/MenuOpenByDefault.tsx
packages/components/menu/examples/MenuWithButtonAsTrigger.tsx
packages/components/menu/examples/MenuWithDisabledItems.tsx
packages/components/menu/examples/MenuWithMaxHeight.tsx
packages/components/menu/examples/MenuWithPredefinedFocusedMenuItem.tsx
packages/components/menu/examples/MenuWithReactRouterLinks.tsx
packages/components/menu/examples/MenuWithStickyHeaderFooter.tsx
packages/components/menu/examples/MenuWithSubmenu.tsx
packages/components/menu/examples/MenuWithTitle.tsx
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/LiveEditor/utils.ts
packages/website/package.json
packages/website/pages/[...slug].tsx
yarn.lock

Move docs examples to separate files.

feat: next code blocks

---

packages/components/button/src/Button.tsx
packages/components/button/src/IconButton/IconButton.tsx

Fix icon alignment in the `IconButton` component

fix: IconButton styles

---

packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/PageContent.tsx

A button to copy source code of an example

feat: copy source button

---

packages/website/components/Layout.tsx

Fixing a broken scrolling introduced by #1647

fix: scrolling issue

---

packages/website/components/Footer.tsx
packages/website/components/PageContent.tsx
packages/website/components/TableOfContent.tsx

In the separate PR I will adjust the highlighting of the nav while scrolling.

fix: sticky secondary nav

---

packages/website/components/GlobalStyles.tsx
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/MdxRenderer.tsx
packages/website/components/PageContent.tsx
packages/website/components/SidebarLink.tsx
packages/website/components/TableOfContent.tsx

in the next pr:
- highlight nav on scroll
- styles for active and hover state for secondary nav

fix: center layout and styled secondary nav

---

packages/core/src/Grid/Grid.mdx
packages/core/src/Grid/examples/BasicGridExample.tsx
packages/core/src/Grid/examples/ContentAlignmentGridExample.tsx
packages/core/src/Grid/examples/FrGridExample.tsx
packages/core/src/Grid/examples/RepeatNotationGridExample.tsx
packages/core/src/Grid/examples/SpanKeywordGridExample.tsx
packages/core/src/Stack/Stack.mdx
packages/core/src/Stack/examples/HorizontalStackExample.tsx
packages/core/src/Stack/examples/VerticalStackExample.tsx

Grid and Stack components documentation:
* Moved examples to separate files
* Simplified Grid documentation by removing excessive information and examples to make it more concise and digestable.

feat: Stack & Grid documentation

---

packages/components/copybutton/CopyButton.mdx
packages/components/copybutton/examples/CopyButtonExample.tsx
packages/components/copybutton/examples/CopyButtonModifiedTooltipsExample.tsx
packages/components/copybutton/examples/CopyButtonWithInputExample.tsx
packages/core/src/Flex/Flex.mdx
packages/website/components/MdxRenderer.tsx

Improves `CopyButton` documentation.

feat: improve CopyButton examples

---

packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/PageContent.tsx
packages/website/components/TableOfContent.tsx

Gives a bit more width for documentation content

feat: updates content width

---

packages/components/button/examples/IconButtonExample.tsx
packages/components/button/examples/IconButtonToolbarExample.tsx
packages/components/button/src/IconButton/README.mdx
packages/website/components/LiveEditor/ComponentSource.tsx

Improves `IconButton` examples and documentation.

feat: IconButton examples

---

packages/components/button/Button.mdx
packages/components/button/examples/ButtonAsAExample.tsx
packages/components/button/examples/ButtonFullWidthExample.tsx
packages/components/button/examples/ButtonSizesExample.tsx
packages/components/button/examples/ButtonStatesExample.tsx
packages/components/button/examples/ButtonVariantsExample.tsx
packages/components/button/examples/ButtonWithIconExample.tsx

docs: Button

---

packages/website/components/LiveEditor/ComponentSource.tsx

- Add padding-bottom to code blocks to prevent overlapping with floating buttons.

feat: code block styling

---

packages/components/autocomplete/Autocomplete.mdx
packages/components/autocomplete/src/Autocomplete.tsx

While using the Autocomplete component, I saw some small issues in the docs and updated them. Nothing major to call out.

fix: docs for Autocomplete

---

packages/components/typography/src/Heading.mdx
packages/components/typography/src/Paragraph.mdx
packages/components/typography/src/examples/HeadingTagExample.tsx
packages/components/typography/src/examples/HeadingTruncatedExample.tsx
packages/components/typography/src/examples/ParagraphExample.tsx
packages/components/typography/src/examples/ParagraphSpacingExample.tsx
packages/components/typography/src/examples/ParagraphTruncatedExample.tsx

- `Paragraph` docs
- `Heading` docs minor adjustments

docs: Paragraph

---

MIGRATION.md
packages/website/content/migration-v3-to-v4.mdx
packages/website/scripts/generate-public-files.ts

A small adjustments when reading environment variables.
Updates broken links.

fix: read PRODUCTION_URL env variable when generating public files

---

packages/website/content/migration-v3-to-v4.mdx

fix: update broken links

---

packages/components/typography/examples/TextBasicExample.tsx
packages/components/typography/examples/TextColorsExample.tsx
packages/components/typography/examples/TextFontSizeExample.tsx
packages/components/typography/examples/TextPolymorphicExample.tsx
packages/components/typography/examples/TextTruncateExample.tsx
packages/components/typography/src/Text.mdx

feat: improve Text documentation

---

packages/components/button/examples/ToggleButtonBasicExample.tsx
packages/components/button/examples/ToggleButtonGroupedExample.tsx
packages/components/button/examples/ToggleButtonStatesExample.tsx
packages/components/button/src/ToggleButton/README.mdx
packages/components/button/src/ToggleButton/ToggleButton.tsx

Improves `ToggleButton` documentation and updates new properties in ToggleButton props

feat: updates ToggleButton documentation and improves ToggleButton props

---

packages/website/components/DocSearch.tsx
packages/website/pages/_app.tsx

Fixes broken DocSearch configuration

fix: proper DocSearch configuration

---

packages/components/typography/src/Heading.mdx
packages/components/typography/src/SectionHeading.mdx
packages/components/typography/src/Subheading.mdx
packages/components/typography/src/examples/HeadingCompositionExample.tsx
packages/components/typography/src/examples/SectionHeadingCompositionExample.tsx
packages/components/typography/src/examples/SectionHeadingExample.tsx
packages/components/typography/src/examples/SectionHeadingSpacingExample.tsx
packages/components/typography/src/examples/SectionHeadingTagExample.tsx
packages/components/typography/src/examples/SectionHeadingTruncatedExample.tsx
packages/components/typography/src/examples/SubheadingCompositionExample.tsx
packages/components/typography/src/examples/SubheadingExample.tsx
packages/components/typography/src/examples/SubheadingSpacingExample.tsx
packages/components/typography/src/examples/SubheadingTagExample.tsx
packages/components/typography/src/examples/SubheadingTruncatedExample.tsx

New format docs for:
- `SectionHeading`
- `Subheading`

docs: Subheading, SectionHeading

---

packages/components/datetime/DateTime.mdx
packages/components/datetime/examples/ISOStringExample.tsx
packages/components/datetime/examples/JSDateExample.tsx
packages/components/datetime/examples/UnixEpochExample.tsx

The new format for DateTime component documentation.

docs(datetime): refactor to new docs format

---

packages/website/components/DocSearch.tsx
packages/website/package.json
packages/website/pages/_app.tsx
yarn.lock

fix: bring the previous version of Algolia back

---

.circleci/config.yml
lerna.json

Allow publishing from `v3` branch.

chore: update publishing branches

---

.circleci/config.yml
lerna.json

A small adjustment of publishing settings

chore: update publishing settings

---

packages/core/src/Box/examples/BoxPolymorphicExample.tsx
packages/core/src/Flex/examples/FlexExample.tsx
packages/core/src/Stack/examples/HorizontalStackExample.tsx
packages/core/src/Stack/examples/VerticalStackExample.tsx

Recreated https://github.com/contentful/forma-36/pull/1686 from master

fix: fix layout examples

---

packages/website/components/Sidebar.tsx
packages/website/content/maintenance-plan.mdx
packages/website/content/migration-v3-to-v4.mdx
packages/website/content/v3-faq.mdx
packages/website/utils/sidebarLinks.json

Recreate https://github.com/contentful/forma-36/pull/1709 from master

docs: FAQ and support for v3

---

packages/components/asset/src/Asset.styles.ts
packages/components/card/src/AssetCard/AssetCard.styles.ts
packages/components/card/stories/AssetCard.stories.tsx

- Revert the previous (v3) AssetCard behavior with flexible width

fix: AssetCard max-width

---

.circleci/config.yml

Adjust check broken link behavior

chore: exclude design link

---

packages/components/forms/examples/TextInputControlledExample.tsx
packages/components/forms/examples/TextInputGroupExample.tsx
packages/components/forms/examples/TextInputStatesExample.tsx
packages/components/forms/examples/TextInputUncontrolledExample.tsx
packages/components/forms/src/TextInput/README.mdx

Updates TextInput documentation.

docs: updates TextInput documentation

---

packages/components/forms/examples/RadioControlledExample.tsx
packages/components/forms/examples/RadioGroupExample.tsx
packages/components/forms/examples/RadioUncontrolledExample.tsx
packages/components/forms/src/Radio/README.mdx

docs: Radio documentation

---

.circleci/config.yml
lerna.json
packages/forma-36-website/gatsby-config.js
packages/forma-36-website/src/components/Header.js
packages/forma-36-website/src/components/Navigation.js

Updates promo copy on v3 website and adds a current version number

docs: update promo text and show version number

---

packages/website/components/LiveEditor/StaticSource.tsx

Fixes a small regression with no white space after static code blocks.

docs: add static code margin-bottom

---

.circleci/config.yml

Enable automatic publishing from the main branch.

chore: reenable automatic publishing from main branch

---

.github/ISSUE_TEMPLATE/bug-report.md

chore: updates issue template

---

packages/components/forms/examples/FormCharacterCountExample.tsx
packages/components/forms/examples/FormControlCharacterCountExample.tsx
packages/components/forms/examples/FormControlCheckboxGroupExample.tsx
packages/components/forms/examples/FormControlExample.tsx
packages/components/forms/examples/FormControlInvalidExample.tsx
packages/components/forms/examples/FormControlRadioGroupExample.tsx
packages/components/forms/examples/FormControlSelectExample.tsx
packages/components/forms/examples/FormExample.tsx
packages/components/forms/src/Form/README.mdx
packages/components/forms/src/FormControl/README.mdx

Move examples to separate files for `Form` and `FormControl` documentation

docs(forms): Forms docs update

---

packages/components/forms/examples/SwitchCheckboxDisabled.tsx
packages/components/forms/examples/SwitchControlledExample.tsx
packages/components/forms/examples/SwitchUncontrolledExample.tsx
packages/components/forms/examples/SwitchVsCheckboxExample.tsx
packages/components/forms/src/Switch/README.mdx

Move examples to separate files.

docs(switch): update documentation

---

packages/components/text-link/README.mdx
packages/components/text-link/examples/TextLinkAsButtonExample.tsx
packages/components/text-link/examples/TextLinkBasicExample.tsx

Updates `TextLink` documentation

docs: updates TextLink documentation

---

packages/components/notification/README.mdx
packages/components/notification/examples/NotificationBasicExample.tsx
packages/components/notification/examples/NotificationCtaExample.tsx
packages/components/notification/examples/NotificationIntentsExample.tsx
packages/components/notification/examples/NotificationPlacementExample.tsx
packages/components/notification/examples/NotificationStickyExample.tsx
packages/components/notification/examples/NotificationTitleExample.tsx
packages/components/notification/examples/NotificationUniqueIdExample.tsx

Improved `Notification` documentation.

docs: better Notification examples

---

packages/components/menu/README.mdx

Clean up and improve `Menu` documentation page

docs(menu): improve menu documentation

---

packages/components/spinner/README.mdx
packages/components/spinner/examples/SpinnerSizesExample.tsx
packages/components/spinner/examples/SpinnerVariantsExample.tsx
packages/components/spinner/examples/SpinnerWithTextExample.tsx

Improved documentation about Spinner component.

docs: spinner documentation

---

packages/components/icon/README.mdx
packages/components/icon/examples/AllIconsExample.tsx
packages/components/icon/examples/IconAsPropExample.tsx
packages/components/icon/examples/IconSizesExample.tsx
packages/components/icon/examples/IconVariantsExample.tsx
packages/components/icon/examples/IconWithSVGExample.tsx
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/SandpackRenderer.tsx
packages/website/package.json

Extract examples into separate files.

docs(icons): update documentation

---

packages/components/badge/examples/DefaultSizeExample.tsx
packages/components/badge/examples/FeaturedBadgeExample.tsx
packages/components/badge/examples/NegativeBadgeExample.tsx
packages/components/badge/examples/PositiveBadgeExample.tsx
packages/components/badge/examples/PrimaryBadgeExample.tsx
packages/components/badge/examples/PrimaryFilledBadgeExample.tsx
packages/components/badge/examples/SecondaryBadgeExample.tsx
packages/components/badge/examples/SmallSizeExample.tsx
packages/components/badge/examples/WarningBadgeExample.tsx
packages/components/badge/src/Badge/README.mdx

Update documentation and extract examples into separate files.

docs(badge): update documentation

---

packages/website/components/Sidebar.tsx
packages/website/components/SidebarLink.tsx
packages/website/components/SidebarSection.tsx

feat: add app framework link and playground link to the sidebar

---

packages/components/list/README.mdx
packages/components/list/examples/ListBasicExample.tsx
packages/components/list/examples/ListWithAsExample.tsx
packages/components/typography/src/SectionHeading/README.mdx
packages/components/typography/src/Subheading/README.mdx

- New docs format for `List` component
- Minor typo fixes in other docs

docs: new format for List

---

packages/components/entity-list/README.mdx
packages/components/entity-list/examples/BasicEntityListExample.tsx
packages/components/entity-list/examples/EntityListWithActionsMenuExample.tsx
packages/components/entity-list/examples/EntityListWithDragHandleExample.tsx

- new format for EntityList component

docs: new format for EntityList

---

packages/components/popover/README.mdx
packages/components/popover/examples/PopoverBasicExample.tsx
packages/components/popover/examples/PopoverFocusLockExample.tsx
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/SandpackRenderer.tsx

docs: migrate Popover

---

packages/components/modal/examples/ModalBasicExample.tsx
packages/components/modal/examples/ModalSizesExample.tsx
packages/components/modal/examples/ModalWithFormExample.tsx
packages/components/modal/src/Modal.tsx
packages/components/modal/src/README.mdx

- fix `Modal` defaults
- adjust `Modal` docs, add "Basic" and "With form" examples

fix: fix Modal defaults, adjust docs

---

packages/components/card/src/BaseCard/BaseCard.types.ts

Follow up on #1847, to fix the type definition on the badge prop of Card component

fix(card): fix type definition of Badge on Card component

---

packages/components/drag-handle/src/DragHandle.tsx

- adjusting DragHandle fix comment for more clarity

chore: adjusting DragHandle fix comment for more clarity

---

packages/website/components/LiveEditor/ComponentSource.tsx

feat: align all components to the center of their preview area

---

packages/components/button/src/Button/Button.styles.ts

This reverts commit 2f9b6f8b2c6cb9d0f7d61449d6160e45b17512aa.
Commit breaks custom styling (of course). We need a new approach to this problem 🤔

Revert "fix(button): enforce color properties with !important (#1856)"

---

packages/website/utils/getGridStyles.ts

feat: increase sidebar width

---

packages/components/pagination/examples/PaginationExample.tsx
packages/components/pagination/package.json
packages/components/pagination/src/Pagination.styles.ts
packages/components/pagination/src/Pagination.test.tsx
packages/components/pagination/src/Pagination.tsx
packages/components/pagination/src/index.ts
packages/components/pagination/src/utils.tsx
packages/components/pagination/stories/Pagination.stories.tsx

Add Pagination component to Forma repository, and remove lodash dependency.
[storybook](https://5fd1dda724cc620021ace8c5-lgniabwelq.chromatic.com/?path=/story/components-pagination--default)

feat(pagination): migrate pagination component from experience-package

---

packages/components/pagination/README.mdx
packages/components/pagination/examples/PaginationExample.tsx
packages/components/pagination/src/Pagination.tsx
packages/forma-36-react-components/package.json
packages/forma-36-react-components/src/index.ts
packages/website/components/PageContent.tsx
packages/website/components/SandpackRenderer.tsx
packages/website/components/Sidebar.tsx
packages/website/components/SidebarLink.tsx
packages/website/components/SidebarSection.tsx
packages/website/package.json
packages/website/utils/content.ts
packages/website/utils/sidebarLinks.json
packages/website/utils/sortByTitle.ts
yarn.lock

* Remove `lodash.sortBy` from website dependency
* Add `new` badge on sidebar on documentation website
* Add `deprecated` and `alpha` notes, based on component status
* Add Pagination to f36-components package.
* Add Documentation for pagination

feat(pagination): Add Pagination documentation and add Pagination to the f36-components

---

packages/website/components/LiveEditor/ComponentSource.tsx

fix(website): override style so what you select is what you edit

---

packages/website/components/GlobalStyles.tsx
yarn.lock

feat: implement a custom scrollbar

---

packages/components/note/src/Note.styles.tsx
packages/components/note/src/Note.tsx
packages/components/note/stories/Note.stories.tsx

fixing styles for Note components without title and with close button.
Closes https://github.com/contentful/forma-36/issues/1885

fix: fix Note without title

---

packages/website/content/migration-v3-to-v4.mdx

docs(migration): fix dropdown migration link

docs(migration): fix dropdown migration link

---

MIGRATION.md

docs(migration): update Autocomplete link

docs(migration): update Autocomplete link

---

packages/components/pagination/package.json
packages/website/components/Playground/SandpackRenderer.tsx
packages/website/package.json

Bump pagination version after visual changes.

chore: bump pagination version

---

.circleci/config.yml
package.json

A couple of improvements to our CI
- ~~cache website build in the first step so we do not need to build it again in `check-links` step~~
- re-enable storybook deployment in Github PRs
- stop building all the packages again in the `release` step they were cached in the first step... I think

chore: improvements to the CI pipeline

---

packages/components/autocomplete/src/Autocomplete.tsx

Fix Autocomplete's `onSelectItem` description.

fix: Autocomplete onSelectItem documentation

---

packages/components/button/src/Button/Button.styles.ts

fix(button): set font-family

---

packages/core/src/GlobalStyles/GlobalStyles.tsx

Add styles prop to `GlobalStyles` component

feat(GlobalStyles): add `styles` prop to enable extending global styles

---

.changeset/lemon-snails-drop.md
.changeset/thin-doors-arrive.md

chore: add changesets

---

.changeset/tricky-deers-love.md
packages/components/accordion/README.mdx
packages/components/accordion/examples/ControlledAccordion.tsx
packages/components/accordion/src/AccordionItem/AccordionItem.tsx
packages/components/accordion/stories/Accordion.stories.tsx
packages/components/menu/src/Menu.tsx
packages/core/src/hooks/index.ts
packages/core/src/hooks/useControllableState.ts
packages/core/src/index.ts

- Add controlled behaviour to Accordion

feat: add controlled behaviour to Accordion

---

packages/website/components/PageContent/TableOfContent.tsx
packages/website/pages/[...slug].tsx
packages/website/utils/tableOfContents.ts

It increases type safety in the parts around [...slug].tsx

refactor: improve website typing

---

.changeset/sharp-phones-check.md

Fix package name on changeset file which was causing release job to fail.

fix: package name on changeset file

---

.changeset/six-fans-sing.md
packages/components/modal/src/Modal.styles.ts

Scale is not applied properly in some (seemingly random) circumstances. We hereby force it to be applied.

fix(modal): force scale

---

.changeset/long-onions-behave.md
packages/components/modal/index.ts
packages/components/modal/package.json
packages/components/modal/src/Modal.styles.ts
packages/components/modal/src/Modal.tsx
packages/components/modal/src/ModalConfirm/ModalConfirm.tsx
packages/components/modal/src/types.ts

fix(modal): don't scale modal with size="zen"

---

.changeset/yellow-lamps-eat.md

Forgot to generate changeset for [this PR](https://github.com/contentful/forma-36/pull/2001)

chore: generate changeset

---

packages/components/datetime/src/RelativeDateTime/README.mdx

Add `baseDate` to examples to close #1954

docs(relative-date-time): update examples with baseDate

---

.changeset/giant-seas-deny.md
packages/components/autocomplete/src/AutocompleteItems.tsx
packages/components/card/src/BaseCard/DefaultCardHeader.tsx
packages/components/entity-list/src/EntityListItem/EntityListItem.tsx
packages/components/list/src/ListItem/ListItem.tsx
packages/components/modal/src/ModalConfirm/ModalConfirm.tsx
packages/components/modal/src/ModalContent/ModalContent.tsx
packages/components/modal/src/ModalControls/ModalControls.tsx
packages/components/modal/src/ModalHeader/ModalHeader.tsx
packages/components/notification/src/NotificationsManager/NotificationsManager.tsx
packages/components/skeleton/src/SkeletonContainer/SkeletonContainer.tsx
packages/components/skeleton/src/SkeletonDisplayText/SkeletonDisplayText.tsx
packages/components/skeleton/src/SkeletonImage/SkeletonImage.tsx
packages/components/skeleton/src/SkeletonText/SkeletonText.tsx
packages/components/workbench/src/WorkbenchContent/WorkbenchContent.tsx
packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.tsx
packages/components/workbench/src/WorkbenchSidebar/WorkbenchSidebar.tsx

Fixes types being generated wrongly
Checkout branch and run `yarn build`, and check that the generated `d.ts` files don't have a `declare export namespace`

fix: fix wrong type definition

---

.changeset/popular-carrots-shout.md
.changeset/selfish-drinks-reply.md
packages/components/pagination/README.mdx
packages/components/pagination/examples/PaginationExample.tsx
packages/components/pagination/examples/PaginationWithTotalAndViewPerPageExample.tsx
packages/components/pagination/examples/PaginationWithTotalExample.tsx
packages/components/pagination/examples/PaginationWithViewPerPageSelector.tsx
packages/components/pagination/package.json
packages/forma-36-react-components/package.json
packages/forma-36-react-components/src/index.ts
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/Playground/SandpackRenderer.tsx
packages/website/package.json

* Remove private flag from `Pagination` so it's published with other packages.
* Add it to the umbrella pacakge `@contentful/f36-components`.
* Update usage on website.

feat: promote pagination to stable

---

packages/components/icon/examples/IconVariantsExample.tsx

- add muted variant to Icon docs

docs: add muted variant to Icon docs

---

MIGRATION.md

Folks were asking for some guidance around Autocomplete for the migration. Maybe this might be helpful, wdyt?

fix: add migration guide for Autocomplete

---

.changeset/chilly-yaks-lay.md

chore: generate changeset for #2051

---

packages/components/autocomplete/examples/ControlledAutocomplete.tsx
packages/components/autocomplete/src/Autocomplete.tsx
packages/components/autocomplete/stories/Autocomplete.stories.tsx

This will enable the autocomplete to have a current selection set from outside.

feat: autocomplete allow setting selected Item from outside

---

.changeset/spicy-crews-kick.md

Adds changeset for latest update to autocomplete component

chore: add changeset for updated autocomplete

---

packages/components/collapse/examples/CollapseExample.tsx

the button was jumping when opening the collapsable element.

fix: collapse example

---

packages/components/icons/README.md

Updates icons README with a link to guidelines on the website.

docs(icons): add link to F36 website

---

.changeset/dull-ads-breathe.md
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-select.output.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.output.js
packages/forma-36-codemod/transforms/v4-select.js
packages/forma-36-codemod/transforms/v4-text-field.js
packages/forma-36-codemod/utils/getNewProp.js
packages/forma-36-codemod/utils/index.js

* Make TextField codemod work with binary conditions for validation message.
* Add transformer for selectProps on the SelectField codemod.
Closes #2086 #2091

fix: improve TextField and SelectField codemods

---

packages/components/tabs/src/Tabs.test.tsx

Adding tests for Tabs component

test(tabs): add tests as an example for testing Tabs component [BAU-676]

---

packages/components/datepicker/src/Datepicker.test.tsx
packages/components/datepicker/src/Datepicker.tsx

test: add datepicker tests

---

.changeset/honest-candles-call.md
.changeset/popular-badgers-search.md
.changeset/pre.json
packages/components/datepicker/package.json
packages/website/package.json

Publish new Calendar and Datepicker components `@contentful/f36-datepicker`
Expectation: Version `4.1.0-beta.1` to be published

chore: publish new Calendar and Datepicker components

---

README.md

I think we can get rid of this now.

docs: remove branch renaming info

---

.changeset/hot-bats-teach.md
packages/components/datepicker/README.mdx
packages/components/datepicker/examples/Datepicker/VisualStates.tsx
packages/components/datepicker/examples/Datepicker/WithFormControl.tsx
packages/components/datepicker/package.json
packages/components/datepicker/src/Calendar/Calendar.styles.ts
packages/components/datepicker/src/Datepicker.test.tsx
packages/components/datepicker/src/Datepicker.tsx
packages/components/datepicker/stories/Datepicker.stories.tsx
yarn.lock

- fix the issue when `usePortal` is marked as required https://github.com/contentful/experience-packages/pull/1630#discussion_r920097859
- fix the issue when years select overlaps months select https://github.com/contentful/content-planning-app/pull/2289#pullrequestreview-1038639593
- some additional props refactoring
- example with `FormControl` wrapper

fix: Datepicker [BAU-866]

---

.changeset/rude-crabs-remain.md

chore: update changeset with the latest change to datetime package

---

packages/forma-36-website/gatsby-config.js

fix: update banner for version 3 website

---

packages/website/content/deprecated-components/dropdown.mdx

fix: fix docs for deprecated components

---

.changeset/five-dots-attack.md

Reverts contentful/forma-36#2154

Revert "fix: fix changeset"

---

packages/components/asset/src/Asset.test.tsx
packages/components/asset/stories/Asset.stories.tsx
packages/components/card/stories/AssetCard.stories.tsx
packages/components/entity-list/stories/EntityListItem.stories.tsx
packages/website/content/deprecated-components/empty-state.mdx

Replaces the unstable placeholder image service with an asset from Contentful's image service.

chore: replace image placeholders

---

packages/components/datepicker/package.json
packages/components/datepicker/src/Datepicker.tsx

- Update datepicker input value when selected is undefined

fix: Datepicker input value

---

packages/components/datepicker/package.json
packages/components/datepicker/src/Datepicker.test.tsx
packages/components/datepicker/src/Datepicker.tsx

- fix datepicker trigger button a11y, issue was discovered [during `axe` bump](https://github.com/contentful/forma-36/pull/2177 )

fix: fix datepicker trigger button a11y

---

packages/forma-36-react-components/package.json
yarn.lock

We don't seem to be using react-is or markdown-it.

chore(deps): remove unused dependencies

---

package.json
turbo.json
yarn.lock

Turborepo is now using a JSON config file

build: upgrade turbo

---

packages/components/skeleton/README.mdx

docs(skeleton): fix typo

---

.eslintrc.js
packages/components/datetime/src/utils/formatDateTimeUtils.test.ts
scripts/test/setupTests.js

Test and lint fixes. More to come.

refactor: test and lint fixes

---

CHANGELOG.md
packages/website/content/changelog.mdx
packages/website/lib/api.ts
packages/website/pages/[...slug].tsx
packages/website/types.ts
packages/website/utils/sidebarLinks.json

fix(website): changelog page needs special handling

---

packages/components/datetime/src/RelativeDateTime/RelativeDateTime.tsx
packages/components/datetime/src/utils/formatDateTimeUtils.test.ts
packages/components/datetime/src/utils/formatDateTimeUtils.ts
packages/components/datetime/src/utils/relativeDateTimeUtils.ts
scripts/.storybook/main.js

I can't get size-limit to work otherwise, which is an indication other Webpack users would run into problems 🙁

fix: fully specify JS imports

---

packages/website/components/Layout.tsx
packages/website/components/PreviewAlert.tsx
packages/website/next.config.js
packages/website/pages/[...slug].tsx
packages/website/pages/api/exit-preview.ts
packages/website/pages/api/preview.ts

- Add preview logic and api routes

feat: Forma 36 website preview

---

.changeset/proud-cups-tie.md
packages/components/datepicker/README.mdx
packages/components/datepicker/examples/Calendar/Basic.tsx
packages/components/datepicker/examples/Calendar/CustomDayContent.tsx
packages/components/datepicker/examples/Calendar/Indicator.tsx
packages/components/datepicker/examples/Calendar/MinMax.tsx
packages/components/datepicker/examples/Calendar/MultiMonths.tsx
packages/components/datepicker/examples/Datepicker/Basic.tsx
packages/components/datepicker/examples/Datepicker/Custom.tsx
packages/components/datepicker/examples/Datepicker/DefaultOpen.tsx
packages/components/datepicker/examples/Datepicker/Format.tsx
packages/components/datepicker/examples/Datepicker/VisualStates.tsx
packages/components/datepicker/examples/Datepicker/WithFormControl.tsx
packages/components/datepicker/package.json
packages/components/datepicker/src/Calendar/README.mdx
packages/components/datepicker/src/Calendar/index.ts
packages/forma-36-react-components/package.json
packages/forma-36-react-components/src/index.ts
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/Playground/SandpackRenderer.tsx
packages/website/package.json
packages/website/utils/sidebarLinks.json

- Make Datepicker stable.
- Add it to the umbrella package @contentful/f36-components.
- Update usage on the website.
- BONUS: remove export hack for Parcel bundler (thanks to @denkristoffer  🙏)

feat: Datepicker to stable [BAU-699]

---

.changeset/unlucky-queens-think.md
packages/components/notification/package.json
packages/components/notification/src/NotificationItem/NotificationItemContainer.tsx
types/typings.d.ts
yarn.lock

- Upgrade react-animate-height to fix f36-notification

fix: notification

---

package.json
tsconfig.json
tsup.config.ts
yarn.lock

Upgrades browserslist-config which means we can now target es2020.

chore(deps): upgrade @contentful/browserslist-config

---

packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.output.js
packages/forma-36-codemod/transforms/v4-text-field.js

Add handling of textfields that had a `textarea` prop on the codemod.

feat: add textarea handling on textfield codemod

---

packages/components/datepicker/README.mdx

Removes beta install instructions for released component.

docs(datepicker): remove beta instructions

---

.changeset/brown-buses-rule.md
.size-limit.js

build: fix size-limit target

---

.changeset/config.json
.changeset/twelve-schools-move.md
.size-limit.js

We forgot to add the datepicker to the changeset config.

build: add datepicker package to changeset

---

MIGRATION.md
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.input.js
packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-text-field.output.js
packages/forma-36-codemod/transforms/v4-text-field.js
packages/forma-36-codemod/utils/index.js
packages/forma-36-codemod/utils/updateComponentsToImport.js

* Add handling of `textLinkProps` on TextField codemod
* Update Migration documentation to have example of TextField with `textLinkProps`

feat: add handling of textLinkProps on codemod and update migration documentation

---

.github/CODEOWNERS

chore: add @fabe to codeowners

---

.changeset/afraid-apples-dance.md

Generate notification changeset for #2232

chore: notification changeset

---

.changeset/slimy-poems-explain.md
packages/components/icons/src/Toggle.tsx
packages/components/icons/src/index.ts

Add ToggleIcon that's going to be used in the merge app.
Screenshot:

feat(icons): Add Toggle icon

---

packages/forma-36-react-components/README.md
scripts/.storybook/docs/General/General.stories.mdx

docs: remove old doc links

---

.circleci/config.yml

Trying to lessen our maintenance burden:
- build(circle-ci): use node LTS images
- build(circle-ci): use node orb

build(circle-ci): optimise config

---

MIGRATION.md

docs: rename FC.FormLabel to FC.Label

---

RELEASES.md

Fix command to run changeset cli on documentation

docs(releases): fix command to run changeset cli

---

.github/CODEOWNERS

chore: [] rename Bauhaus to Core Experience

---

packages/website/components/DocSearch.tsx

Allow a `console.error()` for one less eslint warning.

chore(doc-search): allow console error

---

.changeset/twenty-dragons-switch.md
packages/components/forms/src/BaseCheckbox/BaseCheckbox.tsx

Remove label prop as it was renamed to aria-label but kept on the typing

fix(basecheckbox): remove label prop

---

.changeset/pretty-pears-hug.md

chore: add changeset for entity list []

---

.changeset/proud-ants-rest.md
packages/components/tooltip/src/Tooltip.tsx

- fix tooltip sticky behavior issue

fix: fix tooltip useEffect

---

packages/components/multiselect/examples/MultiselectBasicUsageExample.tsx
packages/components/multiselect/examples/MultiselectSearchExample.tsx

- fix multiselect docs examples

fix: fix multiselect docs examples

---

.changeset/weak-pugs-approve.md
packages/components/multiselect/examples/MultiselectSelectAllExample.tsx

fix a small typo in the documentation example

fix: example in documentation

---

.circleci/config.yml
.contentful/.vault-secrets.yaml
package.json

Add vault configuration file.
This file should be added before updating circleci configuration.

chore: add .contentful/.vault-secrets file

---

.circleci/config.yml

Implements vault for NPM tokens.

chore: use vault [CFCX-142]

---

.changeset/popular-hats-knock.md
packages/components/copybutton/src/CopyButton.tsx

Omit more props that should not be used on the CopyButton.

chore(copy-button): omit more Button props

---

.changeset/chatty-clouds-deliver.md
packages/components/tabs/README.mdx
packages/components/tabs/examples/TabsControlledWithMountedContentExample.tsx
packages/components/tabs/src/TabPanel.tsx

- add forceMount prop to TabsPanel

feat: add forceMount prop to TabsPanel

---

.changeset/ninety-swans-invite.md
packages/components/utils/src/getStringMatch/getStringMatch.test.ts
packages/components/utils/src/getStringMatch/getStringMatch.ts

* Add escape to special characters on getStringMatch
* Add tests to getStringMatch

fix: add autoescape special characters on getStringMatch

---

.changeset/slow-pots-fold.md
packages/components/typography/examples/CaptionExample.tsx
packages/components/typography/examples/CaptionTagExample.tsx
packages/components/typography/src/Caption/Caption.test.tsx
packages/components/typography/src/Caption/Caption.tsx
packages/components/typography/src/Caption/README.mdx
packages/components/typography/src/Caption/index.ts
packages/components/typography/src/index.ts
packages/components/typography/stories/Caption.stories.tsx
packages/website/utils/sidebarLinks.json

Add a Caption typography component.

feat: Caption component

---

.changeset/four-boats-warn.md
packages/components/badge/examples/DefaultSizeExample.tsx
packages/components/badge/examples/FeaturedBadgeExample.tsx
packages/components/badge/examples/NegativeBadgeExample.tsx
packages/components/badge/examples/PositiveBadgeExample.tsx
packages/components/badge/examples/PrimaryBadgeExample.tsx
packages/components/badge/examples/PrimaryFilledBadgeExample.tsx
packages/components/badge/examples/SecondaryBadgeExample.tsx
packages/components/badge/examples/SmallSizeExample.tsx
packages/components/badge/examples/WarningBadgeExample.tsx
packages/components/badge/src/Badge/Badge.styles.ts
packages/components/badge/src/Badge/Badge.tsx
packages/components/badge/src/EntityStatusBadge/EntityStatusBadge.tsx
packages/components/badge/stories/Badge.stories.tsx

Update styling for Badge components:
* Use `Caption` component instead of span element;
* Cleanup style to remove unnecessary values;
* Update `EntityStatusBadge` to have Title Case, to have correct design without changes on API.

feat(badge): update Badge and EntityStatusBadge styling

---

.circleci/config.yml
package.json

Uses [Turbosnap](https://www.chromatic.com/docs/turbosnap#configure) for Chromatic to speed up UI testing.

build: use Chromatic turbosnap

---

.changeset/happy-kangaroos-count.md

Add changeset missing in #2430

fix: add changeset

---

.changeset/rotten-bikes-taste.md
packages/components/table/src/TableCell/TableCell.styles.ts

Add background to table cells.

fix(table-cell): background colour

---

.changeset/gorgeous-rules-develop.md
packages/components/autocomplete/src/Autocomplete.tsx
packages/components/autocomplete/stories/Autocomplete.stories.tsx

Expose `onFocus` and `onBlur` on Autocomplete component

feat(autocomplete): expose onFocus and onBlur events

---

.changeset/short-coats-arrive.md
package-lock.json
packages/components/empty-state/package.json
packages/forma-36-react-components/package.json

chore: bump empty state version

---

.changeset/red-teachers-build.md
packages/components/drag-handle/package.json

- Fix DragHandle component f36-utils dependency version

fix: fix DragHandle deps

---

.changeset/eleven-poets-yell.md
packages/components/drag-handle/src/DragHandle.styles.ts

We want a simple transparent DragHandle without hover style.

feat: remove hover style from draghandle transparent

---

.changeset/tough-trainers-thank.md
packages/components/table/src/TableBody/TableBody.tsx

- fix `Table.Body` children type

fix: Table.Body children type

---

.changeset/wild-rockets-wink.md
package-lock.json
packages/components/datepicker/src/Datepicker.test.tsx
packages/components/pill/examples/DragHandleComponentPillExample.tsx
packages/components/pill/package.json
packages/components/pill/src/Pill.styles.ts
packages/components/pill/src/Pill.test.tsx
packages/components/pill/src/Pill.tsx

Add `isDraggable` prop to `Pill` component, which renders the drag handle without passing an `onDrag` prop.

feat(pill): add isDraggable prop

---

.changeset/sweet-years-drive.md

For some reason [prev PR](https://github.com/contentful/forma-36/pull/2492) didn't get published properly to NPM. This is just to trigger new version publishing.

fix: fix table body types

---

.changeset/big-poems-live.md
.changeset/config.json
package-lock.json
packages/components/avatar/README.mdx
packages/components/avatar/examples/AvatarFallbackExample.tsx
packages/components/avatar/examples/AvatarLoadingExample.tsx
packages/components/avatar/examples/AvatarSizeExample.tsx
packages/components/avatar/examples/AvatarVariantExample.tsx
packages/components/avatar/package.json
packages/components/avatar/src/Avatar.styles.ts
packages/components/avatar/src/Avatar.test.tsx
packages/components/avatar/src/Avatar.tsx
packages/components/avatar/src/index.ts
packages/components/avatar/stories/Avatar.stories.tsx
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/components/Playground/SandpackRenderer.tsx
packages/website/package.json
packages/website/utils/sidebarLinks.json

`Avatar` component based on the `Image` component.

feat: Avatar component

---

CHANGELOG.md
RELEASES.md
packages/website/content/changelog.mdx
scripts/changesets/changelog-generate.js

* Fix changelog script to format multiline correct.
* Fix changelogs file with correct formatting
* Add changeset file example to documentation

fix: make changelog script work with multiline changeset

---

package-lock.json
package.json

Upgrade turborepo.
Unblocks #2530 and we get less CLI noise 👌

chore(deps): bump turbo

---

package-lock.json
packages/components/avatar/package.json

chore: avatar publish next alpha version

---

package-lock.json
packages/components/avatar/package.json

chore: bumps avatar version

---

.changeset/big-poems-live.md
.changeset/bright-lamps-roll.md
.changeset/chilly-roses-impress.md
.changeset/purple-cherries-walk.md
.changeset/rude-lamps-tan.md

Alpha packages are released manually, and they're added to changeset [ignore](https://github.com/contentful/forma-36/blob/main/.changeset/config.json#L10) array. These changesets are not needed

chore(changeset): remove ignored alpha packages changesets

---

.github/CODEOWNERS

Add @cf-remylenoir to codeowners

chore: add @cf-remylenoir to codeowners

---

.github/CODEOWNERS

chore: add @damann to codeowners

---

.changeset/violet-apricots-fix.md

Add missing changeset to trigger a release after my previous PR: https://github.com/contentful/forma-36/pull/2594

chore: add missing changeset

---

packages/forma-36-react-components/README.md

Updates the building documentation accordingly after the #2187 changes.

docs: update building

---

.changeset/thin-socks-sneeze.md
.changeset/wet-toys-pull.md
packages/components/button/src/Button/Button.styles.ts
packages/components/button/src/Button/Button.tsx
packages/components/button/src/IconButton/IconButton.styles.ts
packages/components/button/src/IconButton/IconButton.tsx
packages/components/utils/src/index.ts
packages/components/utils/src/useDensity/useDensity.ts
packages/website/components/Playground/SandpackRenderer.tsx

- Add density context provider to `f36-utils` package
- Consume density context on `f36-buttons` package
This should unblock: https://github.com/contentful/forma-36/pull/2618

feat: add density context []

---

.contentful/vault-secrets.yaml

Add vault policy that will be used on followup PR

chore: add vault packages-read policy [CFCX-857]

---

README.md

Make it clear that you should build before running Storybook.

docs: clearer storybook explanation (#2648) [skip ci]

---

.changeset/stale-cheetahs-fix.md
packages/components/button/src/Button/Button.styles.ts
packages/components/button/src/IconButton/IconButton.styles.ts
packages/components/copybutton/src/CopyButton.styles.ts
packages/components/forms/src/BaseInput/BaseInput.styles.ts
packages/components/forms/src/BaseInput/BaseInput.tsx
packages/components/forms/src/TextInput/README.mdx
packages/components/forms/src/TextInput/input-group/InputGroup.styles.ts
packages/components/forms/src/TextInput/input-group/InputGroup.tsx
packages/components/forms/src/TextInput/input-group/types.ts
packages/components/forms/src/Textarea/Textarea.styles.ts
packages/components/forms/src/Textarea/Textarea.tsx
packages/components/forms/stories/InputGroup.stories.tsx
packages/components/forms/stories/TextInput.stories.tsx

Add support for high density for text inputs

feat: add high density for textinput [CFCX-958]

---

.circleci/config.yml

Add missing step to Changelog CI job

chore: fix changelog CI job []

---

.changeset/itchy-coats-brake.md
packages/components/forms/src/TextInput/input-group/InputGroup.styles.ts

Normalize styles on input group elements

fix: try to normalize styles on elements in InputGroup []

---

packages/website/content/changelog.mdx

Previously fixed changelog messages ([see](https://github.com/contentful/forma-36/commit/23316a2f02d8bda75cdcabbb966e530281a94728)) reappeared and are failing on the CI.

chore: update changelog.mdx

---

.changeset/weak-melons-fail.md

In the previous PR #2680, I didn't add a changeset entry so it wasn't added to a release subsequently.

docs: add changeset entry for timezone bugfix in f36-datetime [SPA-1849]

---

.changeset/three-plums-reflect.md
packages/components/icons/src/Appearance.tsx
packages/components/icons/src/HelpCircle.tsx
packages/components/icons/src/HelpCircleInverted.tsx
packages/components/icons/src/LooksOne.tsx
packages/components/icons/src/LooksTwo.tsx
packages/components/icons/src/MoreVertical.tsx

Deprecate icons slated for removal in v5.

chore: deprecate icons that will be removed in v5

---

.changeset/shy-geckos-thank.md
packages/components/icons/src/HelpCircle.tsx
packages/components/icons/src/HelpCircleInverted.tsx

Un-deprecate icons that will be migrated by codemod 🥴

fix: un-deprecate icons that will be migrated by codemod

---

.changeset/beige-dodos-live.md
packages/core/src/index.ts

Follow up of https://github.com/contentful/forma-36/pull/2733 where the type export was forgotten.

fix: export type

---

packages/components/navbar/examples/WithAccountNotificationNavbarExample.tsx
packages/components/navbar/package.json
packages/components/navbar/src/NavbarAccount/NavbarAccount.styles.ts
packages/components/navbar/src/NavbarAccount/NavbarAccount.tsx
packages/components/navbar/stories/Navbar.stories.tsx

Duplicate the other PR for the `Navbar` component changes:
https://github.com/contentful/forma-36/pull/2750

feat: new variant for navbar account notif [Light Navigation]

---

packages/components/icon/package.json
packages/components/icon/src/utils/wrapPhosphorIcon.tsx
packages/components/icons/package.json

We were not passing correctly the props to the icons.

fix: properly pass the props from Icon to underling icon []

---

package-lock.json
packages/components/navbar/package.json
packages/components/navbar/src/NavbarAccount/NavbarAccount.tsx
packages/components/navbar/stories/Navbar.stories.tsx

Apply changes from https://github.com/contentful/forma-36/pull/2757 to the alpha navbar

refactor: apply avatar changes to light navbar []

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/component-feedback.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/proposal.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Our community Slack was removed ~11 months ago. Also, in our community discord, there is no F36 channel.
This PR updates the README and issue templates

chore: Slack -> Discord

---

packages/components/navbar/package.json
packages/components/navbar/src/NavbarSwitcher/NavbarEnvVariant.tsx
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.styles.ts
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.tsx
packages/components/navbar/stories/Navbar.stories.tsx

fix(navbar): centred env icon

---

packages/components/navbar/src/NavbarItem/NavbarItem.styles.ts
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.styles.ts

Small visual tweaks to the switcher button.

fix: navbar switcher colour

---

packages/components/navbar/src/Navbar.styles.ts
packages/components/navbar/src/Navbar.tsx
packages/components/navbar/src/NavbarAccount/NavbarAccount.styles.ts
packages/components/navbar/src/NavbarItem/NavbarItem.styles.ts
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.styles.ts
packages/components/navbar/src/utils.styles.ts

Increases the hit area on navigation buttons

feat: increase hit area for navigation buttons [CFISO-1555]

---

package-lock.json
packages/website/components/LiveEditor/ComponentSource.tsx
packages/website/package.json

Adds `f36-icons-alpha` to LiveEditor to make navbar renders on the website

fix: navbar rendering on website

---

.changeset/five-swans-think.md
packages/components/collapse/src/Collapse.styles.ts
packages/components/collapse/src/Collapse.tsx
packages/components/collapse/stories/Collapse.stories.tsx

- Add check to disable animation on mount.
- Add Story with expanded style.

refactor: not animate Collapse on first render

---

.eslintignore
packages/components/layout/src/Layout.styles.ts
packages/forma-36-codemod/.eslintignore
scripts/lint-packages.js

Remove top margin from the `Layout` component.

fix(layout): remove top margin

---

packages/components/icons/package.json
packages/components/icons/src/index.ts
packages/components/icons/src/vendor/phosphor/TranslateIcon.tsx

Adding translate icon from Phosphor library

feat: add translate icon

---

packages/components/navbar/package.json
packages/components/navbar/src/Navbar.styles.ts
packages/components/navbar/src/Navbar.tsx
packages/components/navbar/stories/Navbar.stories.tsx

Align the navbar max-width with the layout max-width increase (see https://github.com/contentful/forma-36/pull/2827).

feat(navbar): increase wide variant max-width

---

packages/components/datepicker/src/Calendar/README.mdx

They changed their URL structure, so the current links are pointing to 404s

docs: Update daypicker.dev links

---

.changeset/config.json
package-lock.json
packages/components/datepicker/src/Calendar/README.mdx
packages/components/typography/package.json
packages/components/typography/src/SectionHeading/SectionHeading.tsx

We want to replace the all caps section heading and update the font color to make the contrast more accessible

feat: update styles for section heading

---

.changeset/seven-bikes-sin.md
packages/components/typography/src/SectionHeading/SectionHeading.tsx

Update the style of the SectionHeading component so the color contrast is accessible and the aesthetic appeal is more modern.

feat: update section heading style

---

package-lock.json
packages/components/navbar/package.json
packages/components/navbar/src/Navbar.tsx
packages/components/navbar/src/NavbarItem/NavbarItem.styles.ts

adjusts width of buttons as well as spacing between secondary navigation buttons
before:
after:

fix: adjust spacing and button size

---

.changeset/empty-bees-march.md
package-lock.json
packages/components/notification/package.json

Remove `@swc/helpers` package and trigger a new feature release.

feat: remove swc helpers

---

package-lock.json
packages/components/navbar/package.json
packages/components/navbar/src/NavbarSwitcher/NavbarEnvVariant.tsx
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.tsx
packages/components/navbar/stories/Navbar.stories.tsx

Add environment name to the navbar switcher

feat: add environment to navbar switcher

---

packages/components/header/src/Header.styles.ts
packages/components/header/src/constants.ts
packages/components/header/src/index.ts

this PR is linked to https://github.com/contentful/forma-36/pull/2859
it sets a fixed height to the header component and exports the variable so other components can reuse it.

fix: add and export height constant

---

package-lock.json
packages/components/navbar/package.json

Why is the dependency pinned? I don't see a reason for that.

fix(navbar): unpin avatar dep

---

.changeset/grumpy-dragons-talk.md
packages/components/progress-stepper/src/ProgressStepper.tsx

[Form36 docs ](https://f36.contentful.com/components/progress-stepper) listed className as a prop for this component, but it wasn't being passed. I added it.

Cfiso 000 progress stepper add class name

---

packages/components/icons/package.json
packages/components/icons/src/index.ts
packages/components/icons/src/vendor/phosphor/ArrowUUpLeftIcon.tsx
packages/components/icons/src/vendor/phosphor/ArrowUUpRightIcon.tsx

- add new ArrowUUpLeftIcon and ArrowUUpRightIcon icons

feat: add `ArrowUUpLeftIcon` and `ArrowUUpRightIcon` icons

---

packages/components/header/src/index.ts

fix(header): export HeaderProps

---

package-lock.json

forces an update of the peer dependency package "rollup" to minimum of "2.79.2" in order to solve the security issue https://github.com/contentful/forma-36/security/dependabot/170

fix: resolve security alert #170

---

package-lock.json

updates dependency webpack version to v 5.95.0 to solve  https://github.com/contentful/forma-36/security/dependabot/162

fix: webpack dependency security issue 162

---

.gitignore

chore: ignore turbo cache

---

.changeset/ninety-bees-play.md
package-lock.json
packages/components/table/package.json
packages/components/table/src/TableCell/TableCell.tsx

`TableCell` uses `f36-utils` but the dependency is missing.

fix(table): add f36-utils dependency

---

packages/components/navbar/src/NavbarSwitcher/NavbarEnvVariant.tsx
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.styles.ts
packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.tsx
packages/components/navbar/stories/Navbar.stories.tsx

For our users to easily understand what space and environment they are working in.
- Ticket: https://contentful.atlassian.net/browse/CFISO-2011
- Design: https://www.figma.com/design/RBKfzEzcmiC974nFdtI2wK/Modern-%26-Scalable-%E2%80%93-2024-Webapp-Navigation?node-id=7319-31174&node-type=section&m=dev
| [Preview](https://5fd1dda724cc620021ace8c5-folfqaowjs.chromatic.com/?path=/story/components-navbar--with-different-environments) | [Preview](https://5fd1dda724cc620021ace8c5-zvjgdlueza.chromatic.com/?path=/story/components-navbar--with-different-environments) |

feat(NavbarSwitcher): improve env switcher salience

---

.github/workflows/sast.yaml
catalog-info.yaml

Updates the `catalog-info` ownership and enables Polaris SAST.

chore(catalog-info): update owner + enable Polaris SAST

---

.changeset/warm-clouds-wait.md

The changelog was missing in the previous https://github.com/contentful/forma-36/pull/2965 work.

chore(Tooltip): add missing changelog

---

packages/components/icons/src/index.ts
packages/components/icons/src/vendor/phosphor/BellIcon.tsx
packages/components/icons/src/vendor/phosphor/EnvelopeIcon.tsx
packages/components/icons/src/vendor/phosphor/MicrosoftTeamsLogoIcon.tsx
packages/components/icons/src/vendor/phosphor/SlackLogoIcon.tsx

- BellIcon
- EnvelopeIcon
- MicrosoftTeamsLogoIcon
- SlackLogoIcon

feat: icons icons icons

---

packages/components/icons/src/index.ts
packages/components/icons/src/vendor/phosphor/SquaresFourIcon.tsx

feat(icons): add `SquaresFour` icon

---

package-lock.json
package.json
packages/website/package.json

Update 3 dependencies of the website package to address dependabot alerts.

chore(website): update some dependencies

---

package-lock.json
package.json

Update indirect dependency cross-spawn to 7.0.6 or higher by updating direct dependencies.

chore: pin cross-spawn to ^7.0.6

---

.changeset/serious-pans-marry.md
packages/components/navbar/src/NavbarItem/NavbarItem.styles.ts
packages/components/navbar/src/NavbarItem/NavbarItem.tsx
packages/components/navbar/stories/Navbar.stories.tsx

We needed to enable disabled state for navbar, as it's available in the figma and We're working on a feature requiring that - https://contentful.atlassian.net/browse/HEJO-6990

[HEJO-6990] Add disabled state for Navbar Item

---

package-lock.json
packages/components/navbar/src/Navbar.tsx
packages/components/navbar/stories/Navbar.stories.tsx

this enables full translatability of the Contentful platform and apps that are making use of the navbar component. All new props are optional and use the copy from before as their default values. 
There are no visual differences expected

feat:remove hardcoded copy from navbar [UFO-1308]

---

packages/components/navlist/src/NavList/NavList.tsx
packages/components/navlist/stories/NavList.stories.tsx

Enables translation of the component.

feat: enable handing over aria-label for Navlist

---

.changeset/thin-parents-run.md
packages/components/note/src/Note.tsx
packages/components/note/stories/Note.stories.tsx

This enables overwriting the aira-label on the close Button in order to allow for full translation of the component

feat: enable i18n note [UFO-1314]

---

packages/components/icons/package.json
packages/components/icons/src/index.ts
packages/components/icons/src/vendor/phosphor/VideoIcon.tsx

added a new icon (Video) to alpha

feat: adding video icon []

---

packages/website/components/Footer.tsx

This updates the form behind the "give us feedback" link in the footer of the website.

feat: add new feedback form

---

.changeset/config.json
packages/f36-i18n-utils/package.json
scripts/changesets/changelog-generate.js

this should fix the broken release step

chore: make i18n utils private

---

packages/website/content/tokens/typography.mdx

Updates the tokens/typography documentation to reflect the latest setup.

docs(tokens/typography): update description
