contentful/forma-36

packages/forma-36-react-components/src/components/Modal/ModalControls/ModalControls.css
Flexbox doesn't appear to be needed for ModalControls. The addition of it causes issues when a Modal features long content and the browser's viewport is small - the modal content overlaps the modal controls.
=> Remove flex box from ModalControls

packages/forma-36-react-components/src/components/TextInput/TextInput.css
This PR fixes the spacing for the TextInput with a CopyButton on Safari, so that the copy button is flush with the input field. It also fixes the padding in general, as it seems it was slightly off on Chrome as well.
=> Fix TextInput with CopyButton margins/padding

packages/forma-36-react-components/tools/.storybook/docs/General/General.md
This PR will remove the mention of blueprints in the documentation
=> fix(Docs): Removed mention of blueprints

bin/before-deploy
This PR should fix authentication with Github in CI
=> fix(CI): reset github remote origin

bin/deploy, package.json, yarn.lock
This PR will update Lerna to 3.11.0 to enable github releases!
=> chore(Lerna): Update Lerna to 3.11.0 to use github releases

packages/forma-36-tokens/README.md, packages/forma-36-tokens/package.json, packages/forma-36-tokens/tools/build.js, packages/forma-36-tokens/yarn.lock
Adds `index.js` and `index.d.ts` generation for `forma-36-tokens` so tokens can be used in any CSS-in-JS library.
For example:
```js
import styled from 'styled-components';
import tokens from '@contentful/forma-36-tokens';
const Item = styled.div`
margin-top: ${tokens.spacingXl};
color: ${tokens.colorGreenLight};
`;
```
All tokens are exported in a flat object with camelCase notation, which is more natural for JS and is more convenient to use with TS.
=> feat(forma-36-tokens): Added JS export of all tokens with TS typings

packages/forma-36-react-components/src/components/Select/Select/Select.css, packages/forma-36-react-components/src/components/TextInput/TextInput.css
Fixes transparent background for Select component and adds explicit background for Input component.
=> fix(Select,Input): Fixes a lack of background-color for Select

packages/forma-36-fcss/package.json, packages/forma-36-react-components/yarn.lock
`postcss` is a developer dependency for `forma-36-fcss` package and it shouldn't be installed when `forma-36-fcss` is used in the app
=> build(forma-36-fcss): Moved postcss from deps to devDeps

package.json, packages/forma-36-react-components/.eslintignore, packages/forma-36-react-components/package.json, packages/forma-36-react-components/yarn.lock
This PR will update url-parse and merge since they seem to be vulnerable.
Note: This is not a permanent solution and should be removed as soon as there is a stable storybook update
=> chore(Dependencies): Update vulnarable dependencies merge and parse-url

packages/forma-36-react-components/src/components/Tooltip/Tooltip.css, packages/forma-36-react-components/src/components/Tooltip/Tooltip.stories.js
Position absolute can be influenced by the parent positioning
=> fix(Tooltip): Use position fixed for positioning of Tooltip

packages/forma-36-react-components/src/components/Notification/Notification.md, packages/forma-36-react-components/src/components/Notification/Notification.stories.tsx, packages/forma-36-react-components/src/components/Notification/NotificationItem.css, packages/forma-36-react-components/src/components/Notification/NotificationItem.css.d.ts, packages/forma-36-react-components/src/components/Notification/NotificationItem.test.tsx, packages/forma-36-react-components/src/components/Notification/NotificationItem.tsx, packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx, packages/forma-36-react-components/src/components/Notification/__snapshots__/NotificationItem.test.tsx.snap, packages/forma-36-react-components/src/components/Notification/index.tsx
I'm using Forma-36 as UI framework for UI-extensions. Sometime I need to send to user a notification that is not an error, but just a warning.
SO I've added **warning** intent to Notification Component and API. I used the `-color-orange-dark`as background, following the "error" and "success" CSS.
I also updated:
- Notification.md;
- jest test (I also added an "error" intent test);
- storybook stories.
I'hope you will accept my first PR 😄 
Vincenzo
=> feat(Notification): Added "warning" intent to Notifications system

packages/forma-36-react-components/package.json, packages/forma-36-react-components/yarn.lock
This PR will force Extend version 3.0.2 to prevent a vulnerability
=> fix(ExtendDependency): Bump version to 3.0.2

packages/forma-36-react-components/src/components/ToggleButton/ToggleButton.tsx, packages/forma-36-react-components/src/components/ToggleButton/__snapshots__/ToggleButton.test.tsx.snap
The `ToggleButton` component is missing the `aria-pressed` attribute to make it fully accessible to screen readers. This is based on Heydon Pickering's great tutorial on accessible toggle buttons: https://inclusive-components.design/toggle-button/#atruetogglebutton
=> fix: Add missing aria attribute to ToggleButton

packages/forma-36-react-components/package.json, packages/forma-36-react-components/src/components/Tooltip/Tooltip.js, packages/forma-36-website/src/components/Layout.js, packages/forma-36-website/src/pages/404.js, packages/forma-36-website/src/pages/index.js
* Fixes problem with SSR in Tooltip component which caused a build fail of Gatsby website.
* Fixes problem with `"sideEffects": false` which caused Webpack 4 to cut styles from the build in production mode
=> Fix styles tree shaking in webpack 4

packages/forma-36-react-components/tools/plop-templates/components/stories.tsx.hbs
This PR updates the component stories Plop template to use the new propTypes addon.
=> Use propTypes addon in component stories Plop template

packages/forma-36-react-components/src/components/Modal/Modal/Modal.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.tsx, packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.css, packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.tsx
This PR adds the option to disable word wrapping for the Modal title. It also automatically truncates long words to prevent them from breaking outside the title container.
=> Add option for modal title wrapping

packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.css.d.ts
Fixes an issue shown when building Storybook - TypeScript definition for ModalHeader CSS was missing.
=> Create TS definition for CSS

packages/forma-36-tokens/src/tokens/typography/font-stack.js
https://github.com/contentful/forma-36/pull/128 improved situation on MacOS but made it worse for Ubuntu users. This PR limits fonts fallback list to fonts that look acceptable on all OS.
=> fix: More concise fonts fallback list

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
To prevent ghost dropdowns floating over the slide in editor we should close the dropdown of the asset card after onClick has been dispatched.
=> fix(AssetCard): Close dropdown after onClick

packages/forma-36-react-components/src/components/Icon/Icon.test.tsx, packages/forma-36-react-components/src/components/Icon/Icon.tsx, packages/forma-36-react-components/src/components/Icon/__snapshots__/Icon.test.tsx.snap
Adds `warning` as a valid IconColorType to the Icon component to prevent errors in Note component.
Fixes #137
=> Add ‘warning’ type to Icon props

packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx, packages/forma-36-react-components/src/components/Notification/index.tsx
Fixes a regression with non-closable notifications introduced in `2.10.0`
=> fix(Notification): Fixes non-closable notifications

packages/forma-36-react-components/src/components/Modal/Modal/Modal.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.tsx
* If confirmLabel/cancelLabel properties are empty or falsy then buttons should be hidden
* Add `allowHeightOverflow` to `ModalConfirm` to be aligned with `Modal`
=> fix(ModalConfirm): Hide confirm/cancel buttons

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.css, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.test.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/__snapshots__/DropdownListItem.test.tsx.snap
This change adds a `href` prop to the `DropdownItem` component. This adds the ability to render dropdown actions as links, enabling native browser features such as the ability to open items in a new tab/page.
This PR requires #139 to be merged into master first - once this is merged I will rebase.
=> Add href prop to DropdownItem

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.stories.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.test.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardDragHandle/CardActions.stories.tsx, packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.css, packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.test.tsx, packages/forma-36-react-components/src/components/Card/CardDragHandle/CardDragHandle.tsx, packages/forma-36-react-components/src/components/Card/CardDragHandle/__snapshots__/CardDragHandle.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardDragHandle/index.ts, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.test.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap
This PR adds a drag handle to the EntryCard and AssetCard components for use in drag and drop contexts
=> Card Drag Handles

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
This PR will fix a bug of dropdown repositioning when no resolution is defined.
=> fix(Dropdown): Dont reposition if no resoulution available

packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap
There's currently an issue with the EntryCard component - if it has CardActions, when clicking an action the click event on the EntryCard also fires. This PR fixes this issue.
=> Stop EntryCard click events firing on CardActions click

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.tsx, packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap
This PR will stop CardActions events propagating to AssetCards and InlineEntryCards
=> Stop CardActions events propagating to AssetCard and InlineEntryCard

packages/forma-36-react-components/src/components/Form/Form/Form.css
This PR changes the values of the spacing setting to the following:
default: spacing-l
condensed: spacing-m
=> fix(Form): Use forma tokens for spacing configuration

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.test.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap
This PR adds a size prop to the EntryCard component for purposes of rendering more compact entry cards.
=> Add size prop to EntryCard component

packages/forma-36-react-components/src/components/TextField/TextField.tsx
This PR will fix the issue of the character count not beeing updated when the value is set through props.
Related Issue: https://github.com/contentful/forma-36/issues/143
=> fix(TextField): Update character count on value set through props

packages/forma-36-react-components/src/components/Form/Form/Form.tsx, packages/forma-36-react-components/src/components/TextField/TextField.tsx
*  Filter out nullable children in Form component, so the following code doesn't cause weird empty spacing:
```
<Form>
{null}
<TextField />
<TextField />
</Form>
```
* Fixed warning about incorrect usage of getDerivedStateFromProps
=> Fix broken spacing in Form caused by nullable children

packages/forma-36-react-components/src/components/TextField/TextField.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.tsx
This PR will introduce Date and Time as types for the input component. It also fixes a warning of not returning state on getDerivedStateFromProps.
=> fix(TextInput): Add Date and Time as type

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
Prevents the contents of an EntryCard from overflowing the EntryCard itself
=> Prevent text from overflowing EntryCard component

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.stories.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.test.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.test.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.test.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
This PR introduces a breaking change: the `withDragHandle` prop is now deprecated. To render a drag handle on a component you must pass a CardDragHandle via the `cardDragHandleComponent` prop. This change is necessary for integrating drag and drop libraries such as `react-sortable-hoc` (https://github.com/clauderic/react-sortable-hoc/blob/master/examples/drag-handle.js#L10) - it'll allow the user to pass a HOC drag and drop handle.
=> Refactor card drag handles

packages/forma-36-react-components/src/components/EmptyState/EmptyState.stories.tsx, packages/forma-36-react-components/src/components/EmptyState/EmptyState.test.tsx, packages/forma-36-react-components/src/components/EmptyState/EmptyState.tsx, packages/forma-36-react-components/src/components/EmptyState/__snapshots__/EmptyState.test.tsx.snap
To provide an opportunity to use SVG or any custom element as the illustration, the customImageElement prop was added.
=> fix(EmptyState): Added customImageElement prop

.travis.yml, yarn.lock
=> chore(ci): freeze lockfile in ci

packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
This PR will add a preventDefault to the toggleButton click of the card actions so if the card is a link it won't follow it on click of the toggle button.
=> fix(CarActions): Prevent default for toggle click

packages/forma-36-react-components/src/components/EmptyState/EmptyState.tsx
Update headingProps and desctiptionProps to support ReactNode type for text prop, so it's possible to pass down JSX elements.
=> feat(EmptyState): Update prop type

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
Fixes a bug where if an EntryCard is displayed within an `a` tag, the description text inherits the text colour from that tag if it has been styled with a `:link` pseudo-class in CSS.
=> EntryCard - Give explicit text colour to description

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.stories.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.test.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCardSkeleton.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
Adds a prop which will render a small variant of the AssetCard component
This PR adds a size prop to the AssetCard, giving it the ability to render a smaller image.
=> AssetCard - Add small size variant

bin/deploy, package.json
This PR fixes failing CI because of commitlint
=> chore(CI): fix failing publishes because of commitlint fails

package.json
Disable commitlint to recover failed publishes
=> chore(Commitlint): Disable commitlint to recover failed publish

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.stories.tsx
Without this change there was an issue with the component width in IE11 and Edge. This change fixes that.
=> Fix AssetCard in IE/Edge

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
Fixes a bug where if an AssetCard, EntryCard, or EntityListItem component is passed props relating to drag handles, React would throw a warning as these props were passed to the rendered React component or DOM elements via `otherProps`.
=> Fix Asset/Entry/Entity card props

packages/forma-36-react-components/src/components/Pill/Pill.tsx, packages/forma-36-react-components/src/components/Pill/__snapshots__/Pill.test.tsx.snap
`draggable=true` confuses browser and third-party drag-n-drop libraries and causes bugs.
=> fix(Pill): Removed draggable attribute from Pill component

packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/__snapshots__/DropdownContainer.test.tsx.snap
This PR will add `dropdownContainerClassName` prop to the dropdown for more flexibility overwriting portal container styles. (e.g override zIndex when used in modals)
=> feat(DropDown): Add dropdownContainerClassName

packages/forma-36-website/src/pages/foundation/box-shadows/index.mdx, packages/forma-36-website/src/pages/foundation/spacing/index.mdx, packages/forma-36-website/src/pages/foundation/transitions/index.mdx, packages/forma-36-website/src/pages/foundation/typography/index.mdx
After upgrading `gatsby-plugin-mdx` the foundation pages are attempting to render the code source component when we display values for our tokens. This doesn't work so well… This PR changes the foundation docs to use the `pre` tag rather than `code`, resulting in values being displayed as expected.
=> Fix broken rendering of token values

packages/forma-36-react-components/src/components/IconButton/IconButton.tsx, packages/forma-36-react-components/src/components/Workbench/Workbench.css, packages/forma-36-react-components/src/components/Workbench/Workbench.stories.tsx, packages/forma-36-react-components/src/components/Workbench/Workbench.tsx
Add `BackButton` to Workbench components and more flexible `title` property.
=> chore: added back button to Workbench components

packages/forma-36-react-components/src/components/Tooltip/Tooltip.css
This PR prevents long strings without spaces from being truncated in tooltips by forcing word-breaks.
=> Tooltip - Prevent content being truncated

packages/forma-36-react-components/src/components/Tooltip/Tooltip.css
This is a follow up PR to https://github.com/contentful/forma-36/pull/257 which fixes tooltips in Microsoft Edge
=> Tooltip - Fix overflowing text in Edge

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
With the introduction of the Autocomplete component, the list of options in a dropdown can change depending on the search/filter. This caused an issue where, when positioned at the top of the anchor, the list would not be positioned correctly after a filter is applied.
_List in its default state_
---
_List after a filter is applied, before the fix_
---
_After the fix_
---
=> fix(Dropdown): Position DropdownContainer when list of options reduces

packages/forma-36-react-components/src/components/Asset/Asset.css
Currently the title text in assets will not span multiple lines if the title is set to a long string with no breaking characters. This PR resolves that.
=> Asset - Split non-breaking strings

README.md, forma-icon.svg
This PR adds a SVG version of the forma 36 icon, solely derived from the PNG version.
Also the README headline will be adjusted to incorporate a resized icon within the h1 headline.
Currently the icon size is adjusted to meet the styling of the h1 text on GitHub (renders well in Chrome and Firefox on a Mac, but ymmv):
=> SVG Icon and README update

packages/forma-36-react-components/src/components/Workbench/Workbench.css
Without flexbox, the icon container doesn't properly adapt to it's child dimensions.
There might be alternative solutions
=> fix(Workbench): Align header icon with title

packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx
If onClick and href is defined we still want to provide right click open in new tab.
=> fix(EntryListItem): Add target blank if onClick and href is defined

packages/forma-36-react-components/src/components/Button/Button.css, packages/forma-36-react-components/src/components/CheckboxField/CheckboxField.css, packages/forma-36-react-components/src/components/ControlledInputField/ControlledInputField.css, packages/forma-36-tokens/src/tokens/typography/font-stack.js, packages/forma-36-tokens/src/tokens/typography/font-weight.js
This PR includes some preparations for the deprecation of Avenir in favour of system UI fonts.
**⚠️ This PR does not remove Avenir from the font-stack - this will happen in a follow up PR**
=> System UI font preparation

packages/forma-36-react-components/src/components/Tabs/Tabs.css
This PR reduces of font-weights in preparation for our change to a system UI font-stack
=> Reduce font-weight of Tabs

packages/forma-36-react-components/src/components/Tabs/Tabs.css, packages/forma-36-react-components/src/components/Tabs/Tabs.stories.tsx, packages/forma-36-react-components/src/components/Tabs/Tabs.tsx, packages/forma-36-react-components/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
This PR adds a withDivider property to the Tabs component. if this is true a border will be shown underneath the tabs panel.
=> fix(Tabs): Add withDivider property

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.css
This PR will adjust the width of the small AssetCard variation so 4 will fit into the workbench container configured in text mode.
=> fix(AssetCard): Adjust width to fit 4 into workbench.content

packages/forma-36-react-components/src/components/InViewport/__snapshots__/InViewport.test.tsx.snap, packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forma-36-react-components/src/components/TextLink/TextLink.css, packages/forma-36-react-components/src/components/TextLink/TextLink.stories.tsx, packages/forma-36-react-components/src/components/TextLink/TextLink.test.tsx, packages/forma-36-react-components/src/components/TextLink/TextLink.tsx, packages/forma-36-react-components/src/components/TextLink/__snapshots__/TextLink.test.tsx.snap
This PR will add a property iconPosition to the TextLink component which will allow the selection of the Icon left or right from the link text.
=> feat(TextLink): Add proprety to align the Icon left or right

packages/forma-36-react-components/src/components/TextLink/TextLink.css, packages/forma-36-react-components/src/components/TextLink/TextLink.tsx, packages/forma-36-react-components/src/components/TextLink/__snapshots__/TextLink.test.tsx.snap
This PR will fix a small issue with the right aligned TextLink Icon. It'll now wrap if the text is too long.
=> fix(TextLink): Allow wrapping of right aligned Icon

packages/forma-36-tokens/tools/build.js
Fixes typings for `tokens` package.
`"string"` is not equal to `string`
=> fix(tokens): generate types without quotas

packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardActions/CardActions.stories.tsx, packages/forma-36-react-components/src/components/Card/CardActions/CardActions.test.tsx, packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx, packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityList/__snapshots__/EntityList.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.test.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
This PR will add the isDisabled property to the Card Actions
=> feat(CardActions): Add isDisabled property

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Select/Select/Select.tsx, packages/forma-36-react-components/src/components/SelectField/SelectField.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.tsx, packages/forma-36-react-components/src/components/Textarea/Textarea.tsx
To avoid warnings in react@16.9.0 and create awareness that this method is deprecated.
=> chore(react-components): Prefix componentWillReceiveProps with UNSAFE

packages/forma-36-react-components/src/components/Button/Button.css, packages/forma-36-react-components/src/components/Button/Button.stories.tsx, packages/forma-36-react-components/src/components/Button/Button.test.tsx, packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
This PR adds an isActive prop for programmatically setting active state rather than just relying on the CSS `:active` pseudoclass. Thanks @Silhoue for flagging!
=> feat(Button): Add isActive prop for active state

packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.css
This PR fixes the overflow of the content type. It'll hide the content type if the title is to long. The title will have a content type tooltip using the title attribute.
=> fix(EntityListItem): Fix ct overflow

packages/forma-36-react-components/src/components/TextInput/TextInput.tsx
`TextInput` typings are not complete. This PR adds typings for some keyboard events.
=> fix(text-input): better typings for TextInput component

packages/forma-36-react-components/src/components/Checkbox/Checkbox.stories.tsx, packages/forma-36-react-components/src/components/Checkbox/Checkbox.tsx, packages/forma-36-react-components/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/forma-36-react-components/src/components/ControlledInput/ControlledInput.tsx, packages/forma-36-react-components/src/components/ControlledInput/__snapshots__/ControlledInput.test.tsx.snap, packages/forma-36-react-components/src/components/ControlledInputField/__snapshots__/ControlledInputField.test.tsx.snap, packages/forma-36-react-components/src/components/RadioButton/RadioButton.stories.tsx, packages/forma-36-react-components/src/components/RadioButton/RadioButton.tsx, packages/forma-36-react-components/src/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap, packages/forma-36-react-components/src/components/Select/Select/Select.stories.tsx, packages/forma-36-react-components/src/components/Select/Select/Select.tsx, packages/forma-36-react-components/src/components/Select/Select/__snapshots__/Select.test.tsx.snap, packages/forma-36-react-components/src/components/SelectField/__snapshots__/SelectField.test.tsx.snap
This PR adds a `willBlurOnEsc` prop to checkboxes, radio buttons, and select inputs.
=> Add willBlurOnEsc to more inputs

packages/forma-36-react-components/src/components/Modal/Modal/Modal.tsx, packages/forma-36-react-components/src/components/Modal/Modal/__snapshots__/Modal.test.tsx.snap
This PR will set the default of allowHeightOverflow to true since it's commonly configured this way. It's a small change but breaking so this PR target is next and will kick off F36 4.0
Related Issue: https://github.com/contentful/forma-36/issues/305
=> feat(Modal): Allow height overflow as default

packages/forma-36-react-components/src/components/Workbench/Workbench.css
Fix a problem with shrank sidebar width on small screens.
=> fix(Workbench): set minWidth for sidebars

packages/forma-36-react-components/src/components/Icon/Icon.tsx, packages/forma-36-react-components/src/components/Icon/__snapshots__/Icon.test.tsx.snap, packages/forma-36-react-components/src/components/IconButton/IconButton.tsx
* Fix TS properties for `IconButton` component.
* Added ability to override IconSize with custom css
=> fix(IconButton): Added ability to change size. Fixed TS props

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.stories.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
This adds an icon to EntryCard component that indicates whether or not the entry is scheduled for publish/unpublish/<supported actions>
=> feat(EntryCard): Add scheduled status icon

packages/forma-36-react-components/src/components/TextInput/TextInput.css
This PR adds `-webkit-appearance: textfield` to the `TextInput.css` file. 
Currently in Safari, if the type attribute is set to `search`, the input field looks a lot smaller and unstyled, due to Safari setting the appearance to `searchfield`. To override this, I've explicitly set the appearance to `textfield`.
=> Make Safari's TextInput always look like a text input

packages/forma-36-react-components/src/components/Button/Button.css, packages/forma-36-react-components/src/components/Button/Button.stories.tsx
This PR will add the "warning" button type to the button component
=> feat(Button): Add warning button type

packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
This PR will add the isAutoalignmentEnabled prop to the Dropdown to manual disable this feature.
=> feat(Dropdown): Add isAutoalignmentEnabled prop

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Button/Button.css, packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.css, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css, packages/forma-36-react-components/src/components/Modal/Modal/Modal.css, packages/forma-36-react-components/src/components/Notification/NotificationsManager.css, packages/forma-36-react-components/src/components/TextInput/TextInput.css, packages/forma-36-react-components/src/components/Tooltip/Tooltip.css, packages/forma-36-react-components/src/components/Workbench/Workbench.css, packages/forma-36-react-components/src/styles/settings/z-index.css, packages/forma-36-tokens/src/tokens/z-index.js
This PR will add ZIndex tokens to Forma 36. It should also fix the inability to use tooltips in modals.
=> feat(Tokens): Add ZIndex tokens

packages/forma-36-website/gatsby-config.js
This PR removes the irrelevant promotional bar from the documentation website. ~I chose to comment the relevant code instead of removing it in order to make it more discoverable. Ideally it should be added to the readme as well. Let me know if you disagree with this approach.~
I added the properties back as empty strings to fix failing tests, thanks @m10l for the hint.
=> chore(gatsby-config.js): Remove promotional bar

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownList/__snapshots__/DropdownList.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/__snapshots__/DropdownListItem.test.tsx.snap
There are currently a couple of accessibility issues with the dropdown components. This PR fixes them by firstly updating the Jest snapshots, and secondly (and more important for review) - changing the `DropdownList` and `DropdownListItem` role to be `menu` and `menuitem`.
=> Fix accessibility issues with dropdown

packages/forma-36-react-components/src/components/TextLink/TextLink.tsx
=> Fix text link typescript

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Icon/Icon.tsx, packages/forma-36-react-components/src/components/Icon/constants.ts, packages/forma-36-react-components/src/components/Icon/svg/Delete.svg, packages/forma-36-react-components/src/components/Icon/svg/DeleteTrimmed.svg, packages/forma-36-react-components/src/components/Textarea/Textarea.stories.tsx, packages/forma-36-react-components/src/components/Textarea/Textarea.tsx
This PR exposes a ref for the Textarea component so that focus can be controlled programmatically (similar to TextInput), and adds two new icons - Delete and DeleteTrimmed
=> Expose Ref for Textarea

packages/forma-36-react-components/src/components/Modal/Modal/Modal.css, packages/forma-36-react-components/src/components/Modal/Modal/Modal.stories.tsx, packages/forma-36-react-components/src/components/Modal/Modal/Modal.tsx
Added ability to open modal in a truly fullscreen mode (`zen` mode).
=> feat(modal): added zen size

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
Allow status icon to be a string or node for more flexibility (e.g: Icon wrapped in Tooltip)
=> feat(EntryCard): Allow status icon to be a string or node for more flexibility

packages/forma-36-react-components/README.md
Adds links to the live documentation for users' convenience.
This PR adds links to both the Forma 36 homepage and the Forma 36 storybook online. This page is most common in my internet history and I always wish there were links to those pages from here.
=> docs(README): add links to F36 homepage and storybook

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx
Skip propagation of none HTML attributes to the DOM
Get rid of react warnings from passing none HTML attributes to the DOM
=> refactor(dropdown): skip propagation of none html attributes to the dom

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
Drop dependency to `containerWidth` state variable from `isFullWidth` prop and reuse `anchorDimensions` since they're keeping better track of the container's width.
Dropdown container width calculation isn't triggering when using `isFullWidth` prop from a client component (e.g Autocomplete)
=> improvement(dropdown): container width not re-calcutating

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css, packages/forma-36-react-components/tools/plop-templates/components/styles.css.hbs
Forma 36 components default box-sizing should default to border-box. Apply rule to `dropdown` and hint library developers with the plop templates.
=> improvement(dropdown): change default box-sizing to border-box

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
Prevent chrome from autocompleting Forma 36 Autocomplete
We could consider adding `aria-label` to the TextInput component directly
=> fix(autocomplete): prevent chrome autocomplete

packages/forma-36-react-components/src/components/Button/Button.css, packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.css, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css, packages/forma-36-react-components/src/components/Notification/NotificationsManager.css, packages/forma-36-react-components/src/components/TextInput/TextInput.css, packages/forma-36-react-components/src/components/Tooltip/Tooltip.css, packages/forma-36-react-components/src/components/Workbench/Workbench.css
Some of z-index variables are unresolved in a final build due to a missing imports. This causes a number of different layout bugs.
=> fix(z-index): fixed unresolved z-index values

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.css, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
Support the `width="full"` option in the Autocomplete component. It is currently not working.
=> fix(Autocomplete): Support for full width

packages/forma-36-react-components/package.json, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.test.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Autocomplete/utils.ts, packages/forma-36-react-components/yarn.lock
drop dependency to `is-hotkey`
<!--
Drop `is-hotkey` dependency.
=> refactor(autocomplete): drop is-hotkey dependency

packages/forma-36-react-components/src/components/Modal/Modal/Modal.css, packages/forma-36-react-components/src/components/Modal/Modal/Modal.tsx
Fixed zen mode for Modal component - to avoid breaking the layout with "Show scrollbars: always" setting in OS
When additional scroll-bars would be shown, zen-mode would be broken, this fixes the issue and Modal with zen mode displays correctly with all OS settings.
=> style(modal): fix zen mode for Modal component

packages/forma-36-website/src/components/Masthead.js
Tidy up the display of the F36 logo on the documentation website. Previously the logo wasn't aligned with the dotted background image on the homepage banner. This PR makes sure that it's aligned at any viewport width.
=> Improve display of logo on F36 docs site

packages/forma-36-react-components/src/components/Asset/Asset.stories.tsx, packages/forma-36-react-components/src/components/Asset/Asset.test.tsx, packages/forma-36-react-components/src/components/Asset/Asset.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap
Check the status as part of rendering an `Asset`.
* If the status is present and is archived short-circuit to render as an asset
* Else if the type is an image attempt to render a preview using an `img` tag
=> fix(Asset): Do not attempt to render images with a status of archived

packages/components/forma-36-react-datepicker/yarn.lock, packages/components/forma-36-react-timepicker/yarn.lock, packages/forma-36-react-components/package.json, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx, packages/forma-36-react-components/yarn.lock
Drop `PropTypes` dependency. Update `yarn.lock`s after issuing `lerna clean && lerna bootstrap` from the project's root to keep them aligned.
=> chore(cleanup): drop proptypes usage

packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.test.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
Archived assets will not have a preview image available due to the asset being removed from the CDN. This PR short-circuits the logic in EntityListItem to revert to rendering the icon instead of the thumbnail.
=> fix(EntityListItem): Do not render a thumbnail for archived assets

packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/__snapshots__/DropdownContainer.test.tsx.snap
Pass the test id, given to dropdown, down to dropdownContainer
First of all, dropdownContainer's testId prop was defined, but never used
Secondly, it was unable to identify which dropdownList relates to which dropdown if there were multiple on the page.
=> fix(DropdownContainer): Pass dropdown test id down to dropdownContainer

packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.stories.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.tsx
Make it possible for a secondary button to have "muted" color schema w/out any prop-types warnings
=> fix(ModalConfirm): allow "muted" as a value for the secondaryIntent prop

packages/forma-36-react-components/src/components/Modal/Modal/Modal.css
Use 'display: flex' for centering Modal window position
=> fix(modal component): fix Modal window centering

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Dropdown/Dropdown/Dropdown.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
Check if the size of the dropdown list dimensions have changed and, if so, re-calculate the offset
=> fix(DropdownContainer): Recalculate dropdown position

packages/forma-36-react-components/src/components/Skeleton/SkeletonImage/SkeletonImage.tsx, packages/forma-36-react-components/src/components/Skeleton/SkeletonText/SkeletonText.tsx
This PR will add string as proptype of widths and other spacing props so we don't get warnings for percentage values.
=> fix(SkeletonText): Allow string as proptype for percentage values

packages/forma-36-react-components/src/components/Modal/Modal/Modal.css
Fixes a bug with the `allowHeightOverflow` prop. 
By default, the modal window set a max-width prop which allows the user to set any arbitrary width but the modal will then nicely resize horizontally as the user resizes their browser window.
The `allowHeightOverflow` removes this max-width setting (alongside the max-height), which essentially allows the modal window to overflow both in width and height. 
This would have made sense, if the prop was `allowOverflow` as opposed to `allowHeightOverflow` where the expected behavior should be that the window will overflow only vertically.
=> fix(ModalWindow): Remove unsetting of max width when allowHeightOverflow is set

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx, packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.tsx
Fix TS definitions and make it clear that href can be passed.
=> fix(cards): fix missing href ts definition

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Button/Button.css
Small fix for issue when buttons that recieve href, gets a gray border - https://github.com/contentful/forma-36/issues/421
fix #421
BEFORE:
AFTER:
=> fix: fix gray border issue for buttons with href

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Notification/Notification.stories.tsx, packages/forma-36-react-components/src/components/Notification/NotificationItem.css, packages/forma-36-react-components/src/components/Notification/NotificationItem.test.tsx, packages/forma-36-react-components/src/components/Notification/NotificationItem.tsx, packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx, packages/forma-36-react-components/src/components/Notification/__snapshots__/NotificationItem.test.tsx.snap, packages/forma-36-react-components/src/components/Notification/index.tsx, packages/forma-36-react-components/src/components/TextLink/TextLink.css, packages/forma-36-react-components/src/components/TextLink/TextLink.md, packages/forma-36-react-components/src/components/TextLink/TextLink.stories.tsx, packages/forma-36-react-components/src/components/TextLink/TextLink.test.tsx, packages/forma-36-react-components/src/components/TextLink/TextLink.tsx, packages/forma-36-react-components/src/components/TextLink/__snapshots__/TextLink.test.tsx.snap
This PR will allow notifications to accept a title, body, and CTA
=> Allow notifications to accept a title, body, and CTA

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Notification/NotificationItem.css, packages/forma-36-react-components/src/components/Notification/NotificationItem.tsx, packages/forma-36-react-components/src/components/Notification/__snapshots__/NotificationItem.test.tsx.snap
This PR introduces a redesign to the NotificiationIcon component to address some accessibility concerns.
=> Notification - Address accessibility issues

packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap, packages/forma-36-react-components/src/components/Skeleton/SkeletonBodyText/__snapshots__/SkeletonBodyText.test.tsx.snap, packages/forma-36-react-components/src/components/Skeleton/SkeletonContainer/SkeletonContainer.test.tsx, packages/forma-36-react-components/src/components/Skeleton/SkeletonContainer/SkeletonContainer.tsx, packages/forma-36-react-components/src/components/Skeleton/SkeletonContainer/__snapshots__/SkeletonContainer.test.tsx.snap, packages/forma-36-react-components/src/components/Skeleton/SkeletonDisplayText/__snapshots__/SkeletonDisplayText.test.tsx.snap, packages/forma-36-react-components/src/components/Skeleton/SkeletonImage/__snapshots__/SkeletonImage.test.tsx.snap, packages/forma-36-react-components/src/components/Skeleton/SkeletonText/__snapshots__/SkeletonText.test.tsx.snap
This PR makes the default IDs for the `<defs>` elements in the `<SkeletonContainer>` unique by using computed properties in the component's `defaultProps`. This means that there's now no need to manually set IDs.
Key file: https://github.com/contentful/forma-36/pull/451/files#diff-e8634b3333c8e1a09fd8a7f4e67a00a8
- [ x Has been tested based on [Contentful's browser support](https://www.contentful.com/faq/about-contentful/#which-browsers-does-contentful-support)
=> fix(skeletoncontainer): use unique ids for clipPath and gradient

packages/forma-36-website/src/components/Navigation.js
While working on the search input I saw that we were getting the warnings above. In this PR I refactored the code in the Navigation component to remove the warnings and also to convert the class components to function components
=> Remove warnings in Navigation about GatsbyLink

packages/forma-36-react-components/src/components/Tag/Tag.stories.tsx, packages/forma-36-react-components/src/components/Tag/Tag.test.tsx, packages/forma-36-react-components/src/components/Tag/Tag.tsx, packages/forma-36-react-components/src/components/Tag/__snapshots__/Tag.test.tsx.snap
This PR will add the EntityStatusTag which simplifies color-coding the entity status.
=> feat(EntityStatusTag): Added Entity Status Tag component

README.md
I've added a link to the Contentful community Slack where it is referenced in the README to avoid
newcomers having to guess where to find that and save them a google.
View the markdown here: https://github.com/jacquesporveau/forma-36/tree/jacquesporveau/update-readme#reach-out-to-us
Hey 👋 
I am new here. Trying to get some experience working on UI design libraries. I'll write some real code soon.
=> docs(readme.md): add link to Contentful community Slack

packages/forma-36-react-components/src/components/Switch/Switch.tsx, packages/forma-36-react-components/src/components/Switch/__snapshots__/Switch.test.tsx.snap
Remove the following React warning:
```
You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`
```
=> fix(Switch): Replace checked prop with defaultChecked

packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.tsx
Removes this warning:
```
Warning: Failed prop type: Invalid prop `maxHeight` of type `string` supplied to `DropdownList`, expected `number`.
```
Prop `maxHeight` is currently defined as optional `number` but is used as css property.
=> fix: type type maxHeight

packages/forma-36-react-components/src/components/Button/Button.tsx
#Purpose of PR
Spotted a that `warning` was missing in buttons prop types - which is causing an error to be shown when developing the web app.
=> fix: add missing button type

packages/forma-36-website/gatsby-config.js, packages/forma-36-website/src/pages/components/asset/index.mdx
This PR is adding basic documentation for the Asset component
=> docs: add asset page

packages/forma-36-website/gatsby-config.js
Hey 👋 
Just a small update in our website sidebar navigation - replacement of the PascalCase.
BEFORE:
AFTER:
=> fix(sidebar): Replace PascalCase

packages/forma-36-react-components/src/components/Tabs/Tab.tsx
Exposes event in Tab.onSelect handler that allows us to do `e.preventDefault()` in application code. This is needed for a proper integration of Tab component and a Link component from `react-router`.
=> fix(Tab): expose event in onSelect callback

packages/forma-36-tokens/src/tokens/colors/colors-semantic.js
Update semantic color mapping to use `mid` variants
=> fix: update semantic color mapping

packages/forma-36-website/.eslintignore, packages/forma-36-website/.eslintrc
Previously we ignored the files in `/dist/esm` but maybe it's not enough and we are still getting the error @burakukula posted in #493 
So this PR ignores all `/dist`
I'm not 100% sure if this is correct tough
=> Chore(website): remove eslintrc and  ignore react-components/dist

packages/forma-36-react-components/src/components/Button/Button.css
I noticed that we created this tiny bug after the color change in our buttons. We decided to make the border the same color as the background, but in buttons that use the `<a>` tag the border was still darker which makes them look different
This PR makes the border of those buttons the same color as their background
=> fix(button): make border color the same blue when button is a link

packages/forma-36-react-components/src/components/Grid/Grid.stories.tsx
Just a little change fix over here - display it in Alpha
=> fix: move Grid into Alpha section in storybook

packages/forma-36-fcss/package.json, packages/forma-36-fcss/yarn.lock
Upgrade `node-sass` to `4.14.1` to support node version `14.x`
=> chore: upgrade node-sass for node 14.x support

packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.css, packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.tsx
This PR adds animation to the Accordion component currently in review at PR #531 
There are actually two implementations hahaha
In the first commit I used WAAPI, but look at the support for it:
(Also, I think enzyme or jest do not understand `.animate()`)
So I replaced with requestAnimationFrame magic
I followed some ideas from [CSS-Tricks](https://css-tricks.com/using-css-transitions-auto-dimensions/) on how to animate `height: auto`
We need it to be auto because the content of the accordion varies
It would be nice if we can make a component (or a custom Hook) out of the animations to make it modular, but I wanted to check with you first. WDYT?
=> Implement animation in the Accordion component

packages/forma-36-tokens/src/tokens/typography/font-weight.js
This is to fix type errors when using these tokens with emotion
which expects font-weight to be a number
=> fix: change font-weight to number

packages/forma-36-react-components/src/components/Form/FieldGroup/FieldGroup.tsx, packages/forma-36-react-components/src/components/Form/FieldGroup/__snapshots__/FieldGroup.test.tsx.snap
Fixes `FieldGroup` which wasn't using a passed `className`.
=> fix: use FieldGroup classname property

packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.stories.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.tsx, packages/forma-36-react-components/src/components/EntityList/__snapshots__/EntityList.test.tsx.snap
Closes #535 
Adds `withThumbnail` prop to control whether or not the Thumbnail should render
=> feat(entity-list-item): add withThumbnail prop

packages/forma-36-react-components/src/components/EntityList/EntityList.stories.tsx, packages/forma-36-react-components/src/components/EntityList/EntityList.tsx
This closes #534 
Following the proposal in #534, this PR implements forwardRef to EntityList. It also refactors the component to a functional component
=> feat(entityList): add forwardRef to component

packages/forma-36-tokens/tools/build.js
In previous PR I changed the value of the font weights to a number, but didn't realise I needed to update the build file that creates the type definition. This PR makes it so the outputted types for fontweights are correct. 
I'd appreciate feedback on this approach, as while it currently outputs the correct result - it feels a little big 'magic' to me..
=> fix: output the correct type for font weights

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/alpha.ts, packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.stories.tsx, packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.tsx, packages/forma-36-react-components/src/components/Modal/ModalLauncher/index.ts, packages/forma-36-react-components/src/index.ts, packages/forma-36-website/src/pages/components/modal/index.mdx
Adds a modal launcher helper with an open method that allows the user to wrap a value that results from a user interaction with a modal window in a promise and await it.
=> feat: add modal launcher helper as alpha component

packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.tsx
Makes the argument of on close optional
=> fix(ModalLauncher): make argument of on close optional

packages/forma-36-react-components/src/components/Accordion/Accordion.css, packages/forma-36-react-components/src/components/Accordion/AccordionHeader/AccordionHeader.tsx, packages/forma-36-react-components/tools/.storybook/contentful-theme.js
This PR makes the chevron in the accordion like this:
Why?
Check [this research](https://www.nngroup.com/articles/accordion-icons/) made by Nilsen Norman Group
I also made the color of the text in the toolbar lighter
**before**
**after**
=> Change Accordion chevron orientation

packages/forma-36-react-components/src/components/Tag/Tag.stories.tsx, packages/forma-36-react-components/src/components/Tag/Tag.test.tsx, packages/forma-36-react-components/src/components/Tag/Tag.tsx, packages/forma-36-react-components/src/components/Tag/__snapshots__/Tag.test.tsx.snap, packages/forma-36-react-components/yarn.lock
Add 'deleted' status to `entityStatusType` prop on `Tag` component
=> feat(tag): add deleted variant to entityStatusType

packages/forma-36-react-components/src/components/Card/Card.stories.tsx, packages/forma-36-react-components/src/components/Card/Card.tsx
Add `target` property to `Card` component
=> feat(card): add target prop

packages/forma-36-react-components/src/components/Asset/Asset.css, packages/forma-36-react-components/src/components/Asset/Asset.tsx
* `Asset` shouldn't render an image tag if `src` attribute is nullable (for example, an empty string).
* Adds padding to title div, so there not situation like this:
=> fix: show image only there's src

packages/forma-36-react-components/src/components/Asset/Asset.css
Fix issue with longer titles of an asset as seen here:
=> fix(asset): handle overflow in asset title

packages/forma-36-react-components/src/components/Asset/Asset.tsx, packages/forma-36-react-components/src/components/Asset/index.ts, packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/index.ts
* Exposes `AssetIcon` component that is useful in field-editors code.
* Hides Asset title DOM nodes if asset title is nullable
=> feat: expose AssetIcon and hide title if it's empty

packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx, packages/forma-36-tokens/src/tokens/z-index.js
- Add tooltip `z-index` value from tokens
- Change tokens `z-index` values to `number` instead of `string` to generate the correct type
=> fix(tooltip): return children if no content provided and add z-index

packages/forma-36-react-components/src/components/CopyButton/__snapshots__/CopyButton.test.tsx.snap, packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/__snapshots__/EditorToolbarButton.test.tsx.snap, packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx, packages/forma-36-react-components/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
My bad! I thought we could return the children of the tooltip in case the prop `content` was undefined, but some people rely on the `targetWrapperClassName` prop
So this makes us return the target and its container to fix that
I'm also proposing to change the default value of `place` to 'auto', because I  had to change this in user_interface more than once. Initially, I did the default value 'bottom' to preserve the old API, but it is messing up positioning in some cases where the tooltip does not have room to be placed. And 'auto' is always positioning the tooltip the best way
... or maybe we update this to use portals but that's a bigger task that we can do it in another PR
=> fix: return target wrapper when tooltip has no content

packages/forma-36-website/src/pages/components/radio-button/index.mdx
There is an issue in the current radio button example:
- `checked` is a boolean and not a string
- we should be consistent with the quotes in jsx
=> fix: radio button example

packages/forma-36-react-components/src/components/Select/Select.tsx
Specify element type of change, blur and focus event handlers as `HTMLSelectElement`.
This currently throws an error in TypeScript because `Property 'value' does not exist on type 'EventTarget & Element'.`:
```jsx
<Select
value={value}
onChange={(e) => {
console.log(e.target.value);
}
>
<Option />
</Select>
```
At the moment you have to write the following to not get the error:
```jsx
<Select
value={value}
onChange={(e: ChangeEvent<HTMLSelectElement>) => {
console.log(e.target.value);
}
>
<Option />
</Select>
```
With this PR you don't have to explicitly type the parameter of the `onChange` method.
This problem probably exists for other components as well.
=> fix(select): specify element type for event handlers

packages/forma-36-react-components/src/components/Tooltip/Tooltip.css
This PR sets `white-space: normal` on the tooltip component styles to allow text wrapping even when the parent elements prevent it.
=> fix(tooltip): wrap text

packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
https://github.com/facebook/react/issues/15792#issuecomment-497952680
@andipaetzold reminded me and Dan Abramov confirms it, that we need to return early a component after all the calls to Hooks
=> refactor: return early after all the hooks

packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.test.tsx, packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.tsx, packages/forma-36-react-components/src/components/Grid/GridItem/__snapshots__/GridItem.test.tsx.snap
Happy Friday! It's me again 😄 
As you can see in the [storybook](https://f36-storybook.contentful.com/?path=/story/alpha-grid-griditem--default), the GridItem is not displayed correctly. The default knobs are `columnStart=1; columnEnd=3; rowStart=1; rowEnd=4`.
When you look at the rendered code, you see that the `style` prop is empty. When manually changing the `columnStart` and `rowStart` react prop with the react dev tools to another value and then back to the original, the GridItem is displayed correctly. The knobs are still the same.
When doing this in dev mode locally, you get the following error message
> Updating a style property during rerender (gridColumn) when a conflicting property is set (gridArea) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand …
=> fix: Grid shorthand conflicts

packages/components/forma-36-react-timepicker/jest.config.js, packages/components/forma-36-react-timepicker/package.json, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx, packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/Dropdown.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.test.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/__snapshots__/DropdownContainer.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownList/DropdownList.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownList/__snapshots__/DropdownList.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx, packages/forma-36-react-components/src/components/Dropdown/README.mdx, packages/forma-36-react-components/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap, packages/forma-36-react-components/yarn.lock
This PR refactors the Dropdown component to use [Popper.js](https://popper.js.org/) instead of the current, custom positioning calculation.
Resolves #361
=> feat(dropdown): use Popper.js for a proper positioning

packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
This should prevent capturing escape press when we don't intend to.
=> fix(dropdown): only add keydown event handler when dropdown is open

packages/forma-36-react-components/.eslintrc.js, packages/forma-36-react-components/src/components/Accordion/Accordion.test.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx, packages/forma-36-react-components/src/components/DateTime/DateTime/DateTime.stories.tsx, packages/forma-36-react-components/src/components/DateTime/DateTime/DateTime.test.tsx, packages/forma-36-react-components/src/components/DateTime/RelativeDate/RelativeDate.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx, packages/forma-36-react-components/src/components/Flex/Flex.stories.tsx, packages/forma-36-react-components/src/components/Grid/Grid.stories.tsx, packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.stories.tsx, packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.stories.tsx, packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.tsx, packages/forma-36-react-components/src/components/Notification/NotificationsManager.tsx, packages/forma-36-react-components/src/components/Notification/index.tsx, packages/forma-36-react-components/src/components/Tabs/Tab.tsx, packages/forma-36-react-components/src/utils/throttle.ts
Lint fixes. This PR should make it easier to land some other changes we have coming 🙂
We should decide what we want to do with the eslint rule `@typescript-eslint/no-explicit-any`, which is producing the last warnings. I'm thinking we can turn it off and trust people to know when to use `any`. I did the same with `@typescript-eslint/no-empty-function`.
=> chore: lint fixes

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
This fix handles the situation where the dropdown is open and the user then clicks on the toggle element to close the dropdown, which fires both an open and a close event right after each other.
This happens as the event bubbles from the button and up to the document, where the outside click event handler is bound. The alternative is using a capture event like in this PR, where the event goes from the document and down to the button. This solves the issue of two events firing, but the downside is that it now also takes a second click to e.g. open another dropdown; the first to close the active dropdown and the second to trigger the event of the action.
=> fix(dropdown): use capture event in outside click handler

packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.css
Currently the boldness of `EntryCard` title depends on global CSS for h1. This fix sets explicit boldness to the entry card title so it's bold even if h1 were reset.
=> chore: explicitly set entry title to demi-bold

packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownList/__snapshots__/DropdownList.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/__snapshots__/DropdownListItem.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
`DropdownListItem` class and test-id should not be overwritten by props. Also adds a React display name to the `forwardRef`.
=> fix(dropdownlistitem): always apply button classname and test-id

packages/forma-36-react-components/src/components/Dropdown/Dropdown.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/__snapshots__/DropdownContainer.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/README.mdx, packages/forma-36-react-components/src/components/Portal/Portal.test.tsx, packages/forma-36-react-components/src/components/Portal/Portal.tsx, packages/forma-36-react-components/src/components/Portal/__snapshots__/Portal.test.tsx.snap, packages/forma-36-react-components/src/components/Portal/index.ts, packages/forma-36-react-components/src/utils/useOnClickOutside.ts
This PR adds a prop to the `<Dropdown />` component called `usePortal`. As the name implies this boolean decides whether or not to render the dropdown in a React Portal. Defaults to true to keep all existing dropdowns working 😄 I think it's proven useful to be able to control this on an individual level.
To achieve this I've also added a simple `<Portal />` component I image we can reuse elsewhere. I have a few ideas myself 🙂 
I also did a bit of refactoring and used the code from #615
=> feat(dropdown): add usePortal boolean prop

packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownList/__snapshots__/DropdownList.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/DropdownListItem.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownListItem/__snapshots__/DropdownListItem.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
Last refactor, I promise 🙏 This PR ensures no props are unintentionally being overridden. Also adds a `displayName` to the `DropdownListItem` component for easier debugging in the web inspector.
=> fix(DropdownListItem): extract rendering to methods like old class

packages/components/forma-36-react-datepicker/package.json, packages/components/forma-36-react-timepicker/package.json, packages/forma-36-react-components/src/components/Grid/Grid.tsx
Previously there was a separate `bin/build` job to build all packages before release, and `prepublishOnly` script that repeats the build process.
Currently `release` job on circleci relies on `prepublishOnly` only to avoid repetition. 
This PR adds `prepublishOnly` to the components packages. Later we should look into having `prepublishOnly` on the root and see if it builds on all packages.
=> fix: build components packages before publish

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
This is not a full fix as it doesn't work with closing the dropdown with the escape key and then opening it again on focus.
=> fix(autocomplete): Hotfix for autocomplete dropdown

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/utils/useOnClickOutside.ts
We have other components upstream that need to prevent the dropdown from closing (e.g. a filter value on the entity searchbar) so here is a way to do that by enhancing the `useOnClickOutside` hook to check additional references.
=> feat(dropdown): ability to exclude elements from closing the dropdow

packages/forma-36-react-components/src/components/Tooltip/Tooltip.stories.tsx, packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
This PR adds the ability for the tooltip to stay open while the user interacts with its content.
i.e. Useful when implementing the below design (see the pic)
=> feat(tooltip): make the tooltip stay open when hovering on the content

packages/forma-36-react-components/src/components/Grid/Grid.stories.tsx, packages/forma-36-react-components/src/components/Grid/README.md, packages/forma-36-react-components/tools/.storybook/preview.js
What do you think about showing the components in the center of the canvas?
this PR also wraps all stories in a container that sets our font-family, so components like the spinner are not using Times New Roman anymore
P.S.: I had to add a wrapper in the Grid story because the centered layout broke it and then I updated the story to storybook’s new format
=> docs: show components in the center of the canvas

packages/forma-36-react-components/src/components/Flex/Flex.tsx, packages/forma-36-react-components/src/components/Flex/README.md, packages/forma-36-react-components/src/components/Grid/Grid.md, packages/forma-36-react-components/src/components/Grid/Grid.tsx
I toy around with Forma36 every few months to see what is new. Today I decided I would like to take your Grid / GridItem components for a drive, but I encountered an issue in which they do not seem to be exported from `@contentful/forma-36-react-components@3.67.0`.
([Input](https://user-images.githubusercontent.com/19484365/99481100-02a49e80-291f-11eb-8d1d-0bb27ca0f549.png) and [output](https://user-images.githubusercontent.com/19484365/99481079-f4ef1900-291e-11eb-9ab7-76c913b4b284.png).)
I dug into the repo and found that extracting these 2 components would be relatively simple, so I did. And that is when I encountered this super-massive, show-stopping, brain melting, beast of a bug inside of `Grid.tsx`.
I cloned it all down and found that the typo actually exists a few other places, as …
=> fix(grid): GapTypes typos

packages/forma-36-react-components/src/components/Card/Card.tsx, packages/forma-36-react-components/src/components/Card/__snapshots__/Card.test.tsx.snap
@m10l remembered me that we have use cases where the card will have interactive elements inside of it, like an entry card with context menu, so making it a button when passing `onClick` is dangerous
This PR reverts the card to use `div` always without losing a11y features (... I hope 🙏 )
=> fix(card): make it a div even when onClick has a value

packages/components/forma-36-react-timepicker/src/Timepicker.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Checkbox/Checkbox.tsx, packages/forma-36-react-components/src/components/CheckboxField/CheckboxField.tsx, packages/forma-36-react-components/src/components/ControlledInput/ControlledInput.tsx, packages/forma-36-react-components/src/components/ControlledInputField/ControlledInputField.tsx, packages/forma-36-react-components/src/components/Form/FieldGroup/FieldGroup.tsx, packages/forma-36-react-components/src/components/Form/Form.tsx, packages/forma-36-react-components/src/components/FormLabel/FormLabel.tsx, packages/forma-36-react-components/src/components/IconButton/IconButton.tsx, packages/forma-36-react-components/src/components/RadioButton/RadioButton.tsx, packages/forma-36-react-components/src/components/RadioButtonField/RadioButtonField.tsx, packages/forma-36-react-components/src/components/Select/Option/Option.tsx, packages/forma-36-react-components/src/components/Select/Select.tsx, packages/forma-36-react-components/src/components/SelectField/SelectField.tsx, packages/forma-36-react-components/src/components/TextField/TextField.tsx, packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forma-36-react-components/src/components/TextInput/TextInput.stories.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.tsx, packages/forma-36-react-components/src/components/Textarea/Textarea.tsx, packages/forma-36-react-components/src/components/ToggleButton/ToggleButton.tsx
Refactor form controls to use functional components and react hooks, why:
* https://reactjs.org/docs/hooks-intro.html#motivation
* Remove `UNSAFE` lifecycle methods
* Cleaner code
* Should help with tree shaking and less bundle size, see #304
**Note:** This shouldn't introduce any breaking changes, so if you see anything please flag it.
=> refactor(form-controls): use functional components and react hooks

packages/forma-36-react-components/src/components/TextInput/TextInput.css
This PR removes some webkit specific styling that was showing in Safari
=> fix(text input): remove webkit search styling

packages/forma-36-react-components/README.md, packages/forma-36-react-components/src/components/Flex/README.mdx, packages/forma-36-react-components/src/components/Grid/README.mdx, packages/forma-36-website/gatsby-config.js, packages/forma-36-website/src/pages/components/autocomplete/index.mdx, packages/forma-36-website/src/pages/components/flex/index.mdx, packages/forma-36-website/src/pages/components/grid/index.mdx
Hey F36!
We had some small issues around alpha docs visibility. I tried to add some small tweaks to make it more clear for users. WDYT?
=> fix: add small improvements for readme around alpha components

packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
This PR fixes the issue where `isVisible` is not respected. It is being overwritten to `false` always by the default false `isHoveringTarget` and `isHoveringContent`.
=> fix(tooltip): the isVisible prop is not respected

packages/forma-36-react-components/src/components/Autocomplete/README.mdx
Hey!
Docs for Autocomplete. I think there is a room for improvements when it comes to the component itself (Maybe visual might be improved and accessibility). We might want to tackle that for v4?
=> fix: Autocomplete component docs

packages/forma-36-react-components/src/components/Table/Table.tsx, packages/forma-36-react-components/src/components/Table/TableBody/TableBody.tsx, packages/forma-36-react-components/src/components/Table/TableCell/TableCell/TableCell.tsx, packages/forma-36-react-components/src/components/Table/TableCell/TableSortingLabel/TableSortingLabel.tsx, packages/forma-36-react-components/src/components/Table/TableHead/TableHead.tsx, packages/forma-36-react-components/src/components/Table/TableRow/TableRow.tsx
Refactor table components to functional components, and extend prop types properly. Part of #651
Although we are spreading `{...otherProps}` but ts doesn't really recognise any props the consumer passes that doesn't exist in the props definition. with extending the actual html type it recognises `otherProps` and tight it to the supported attributes
e.g. 
```tsx
export interface TableRowProps extends HTMLProps<HTMLTableRowElement> {
className?: string;
testId?: string;
children: React.ReactNode;
}
// TS works, and recognises onClick
<TableRow onClick={...} /> 
export interface TableRowProps {
className?: string;
style?: React.CSSProperties;
testId?: string;
children: React.ReactNode;
}
// Won't work
<TableRow onClick={...} /> 
```
=> feat: refactor table components to functional components [PUL-1298]

README.md
The current all-contributors CLI adds a shield that doesn't work inline, so this is based on https://github.com/all-contributors/all-contributors-cli/issues/266 and https://github.com/all-contributors/all-contributors/issues/361 👍
=> docs: fix contributors shield

packages/forma-36-react-components/src/components/Tooltip/Tooltip.stories.tsx, packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
This adds `delay` property to `Toolbox` component.
- Previous delay of 1000ms was too long
- We think it’d be beneficial to be able to set custom delay via props, separately for `show` and `hide` (so that there will be no request just to change the delay time etc)
- We aren’t sure if `show` delay is useful as usually we want to show the tooltip right away. But lots of library like https://material.angular.io/components/tooltip/overview and bootstrap has `show` and `hide` delay as props. For the sake of completeness, we can have it. Otherwise, just keep the delay for `hide`.
=> fix(component): Add delay property to Toolbox component

README.md
Should we remove the maintainers section now that we have a list of contributors?
=> docs: remove maintainers

packages/forma-36-react-components/src/components/TextField/TextField.tsx, packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap
We got some failing tests in user_interface due to TextField not passing testId to its TextInput child
=> fix: pass down textInputProps to Element

packages/forma-36-react-components/src/components/TextField/TextField.test.tsx, packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap
Adds a test for typing in the `TextField` component.
=> test(text-field): add test to ensure value changes when typing

packages/forma-36-react-components/src/components/Modal/Modal.css
Modals components using `position="top"` extend too far vertically, which can block outside clicks underneath the modal. For some users, this makes it feel like outside clicks don't close the modal, or only work sporadically.
I propose setting `align-items` to `baseline` on the wrapper, which will reset flex behavior and set the vertical size to the original size of the children, unblocking the space for outside clicks. See images:
Modals using `position="center"` already add the `align-items: center` property, so they don't need to be changed.
=> fix: modals extend too far vertically

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Accordion/Accordion.stories.tsx, packages/forma-36-react-components/src/components/Accordion/README.mdx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx, packages/forma-36-react-components/src/components/Autocomplete/README.mdx, packages/forma-36-react-components/src/components/Flex/Flex.stories.tsx, packages/forma-36-react-components/src/components/Flex/README.mdx, packages/forma-36-react-components/src/components/Grid/Grid.stories.tsx, packages/forma-36-react-components/src/components/Grid/GridItem/GridItem.stories.tsx, packages/forma-36-react-components/src/components/Grid/README.mdx, packages/forma-36-react-components/src/index.ts, packages/forma-36-website/src/components/Footer.js, packages/forma-36-website/src/pages/components/accordion/index.mdx, packages/forma-36-website/src/pages/components/autocomplete/index.mdx, packages/forma-36-website/src/pages/components/flex/index.mdx, packages/forma-36-website/src/pages/components/workbench/index.mdx
Autocomplete, Grid, GridItem, Flex, Accordion, AccordionItem, and ModalLauncher are now stable.
=> feat: export previous alpha components as stable

packages/forma-36-react-components/src/components/TextInput/TextInput.tsx
Specify input element type in ChangeEventHandler
=> fix(text-input): specify input element type in ChangeEventHandler

.circleci/config.yml, bin/deploy
Allows publishing canary releases from `v3-visual-changes` branch
=> chore: enable publishing canary releases

packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
This allows controlling the open state
=> fix(card-actions): extend DropdownProps

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.test.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
We have an useReducer hook in the **Autocomplete**  component that handles an **isOpen** flag that was not taken in account the **dropDown props** in the initialState, this was producing an unexpected behaviour in the Autocomplete dropdown.
We have a current bug in the Search component, since [TagsMultiSelectAutocomplete](https://github.com/contentful/experience-packages/blob/master/packages/entity-search/src/Search/TagsMultiSelectAutocomplete/TagsMultiSelectAutocomplete.tsx) makes use of this **Autocomplete**.
- [x ] I have read the relevant `readme.md` file(s)
- [ x] All commits follow our [Git commit message convention](https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#commits)
- [ x] Tests are added/updated/not required
- [ x] Tests are passing
- [ …
=> fix(Autocomplete): Make use of dropdownProp.isOpen

packages/forma-36-react-components/src/components/Card/CardActions/CardActions.tsx
We have revert to a class component for now.
=> revert(card-actions): revert to class component

packages/forma-36-react-components/src/components/Modal/Modal.stories.tsx, packages/forma-36-react-components/src/components/Modal/Modal.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.stories.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.test.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.tsx, packages/forma-36-react-components/src/components/Modal/ModalContent/ModalContent.css, packages/forma-36-react-components/src/components/Modal/ModalControls/ModalControls.css, packages/forma-36-react-components/src/components/Modal/ModalControls/ModalControls.tsx, packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.css, packages/forma-36-react-components/src/components/Modal/ModalHeader/ModalHeader.tsx, packages/forma-36-react-components/src/components/Typography/Typography/Typography.stories.tsx, scripts/.storybook/main.js
Implements all v3 changes for Modal and ModalConfirm
* New paddings
* Change ModalHeader background
* By default, all buttons in ModalConfirm have `small` size
* Added optional ability to align button on the right side
* The aligning on the right side will be a default behavior in V4
=> feat: new design for modals and allow change buttons positions

packages/forma-36-react-components/src/components/Skeleton/SkeletonRow/__snapshots__/SkeletonRow.test.tsx.snap, packages/forma-36-react-components/src/components/Table/Table.css, packages/forma-36-react-components/src/components/Table/Table.stories.tsx, packages/forma-36-react-components/src/components/Table/Table.tsx, packages/forma-36-react-components/src/components/Table/TableCell/TableCell/TableCell.css, packages/forma-36-react-components/src/components/Table/TableCell/TableSortingLabel/TableSortingLabel.css, packages/forma-36-react-components/src/components/Table/TableRow/TableRow.css
V3 visual changes.
A thing to note, Webkit (Safari) doesn't support `box-shadow` on `tr` elements, which is used to show the blue line at the end of the row. I tried with an absolutely positioned pseudo element instead but `position: relative` on table elements is actually against the CSS spec, so this doesn't work at all. I think we can drop the behaviour in Safari and hope they choose to implement `box-shadow` at some point.
=> feat(table): visual changes

packages/forma-36-react-components/src/components/Button/Button.css
When I worked on the full-width button fix, @fabe told me the label and icons should be aligned like this:
I made the change but I forgot to push it 🤦
=> V3: fix center icon and label in full width button

packages/forma-36-website/src/pages/index.mdx
- Changed the link on the homepage to the active Figma file instead of the missing Sketch file
=> docs(website homepage): change UI Kit link from Sketech to Figma

packages/forma-36-react-components/src/components/Tag/Tag.css
Small fix to make sure that Tag component would not scale it's height:
=> fix: bugfix for Tag 

packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
Hey!
Just a small fix of the loading position in the button.
=> fix: loading Spinner position in button

packages/forma-36-react-components/src/components/Tabs/Tabs.css
I'd rather fix this in consumer apps but this is a faster fix if we need it.
=> fix(tabs): 100% height

packages/forma-36-react-components/src/components/Select/Select.css, packages/forma-36-react-components/src/components/TextField/TextField.stories.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.css, packages/forma-36-react-components/src/components/TextInput/TextInput.stories.tsx, packages/forma-36-react-components/src/components/Textarea/Textarea.css, packages/forma-36-react-components/src/components/Textarea/Textarea.stories.tsx
Hey!
In order to make it work, I need to adjust the placeholder color, but also the input color itself. Changes introduced into all related form components - Input, Textarea, and select.
Additionally one refactor on the stories into the new format.
=> fix: Form elements placeholder improvements

packages/forma-36-react-components/src/components/Select/Select.css, packages/forma-36-react-components/src/components/TextInput/TextInput.css, packages/forma-36-react-components/src/components/Textarea/Textarea.css
Hey!
Fix for input color. Not so black anymore 😉
=> fix: fixed input color

packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
Allow use of React portals wil Tooltip
=> feat(tooltip): implement usePortal prop

packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/src/components/Tooltip/Tooltip.css, packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
Uses Popper to position the Tooltip arrow. Also uses some new tokens.
=> feat(tooltip): use Popper for arrow placement

packages/forma-36-website/gatsby-config.js, packages/forma-36-website/package.json, packages/forma-36-website/src/components/Footer.js, packages/forma-36-website/src/components/Layout.js, packages/forma-36-website/src/components/Promo.js
Hey there!
Just a small update for the website to display information about the new release for F36
=> docs: new release info on the F36 website

packages/components/timepicker/src/Timepicker.tsx
* fix(timepicker): allow clicking on input without closing dropdown
=> fix(timepicker): allow clicking on input without closing dropdown

packages/forma-36-react-components/src/components/Dropdown/Dropdown.stories.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx
This is a hotfix that just removes the gap between dropdown and toggle element or dropdown and
subdropdown. We should fix this in v4
=> fix(dropdown): remove offset to avoid dropdown unexpectedly closing

packages/forma-36-react-components/src/components/List/List.css, packages/forma-36-react-components/src/components/List/List.stories.tsx, packages/forma-36-react-components/src/components/List/List.test.tsx, packages/forma-36-react-components/src/components/List/List.tsx, packages/forma-36-react-components/src/components/List/ListItem/ListItem.css, packages/forma-36-react-components/src/components/List/README.mdx, packages/forma-36-react-components/src/components/List/__snapshots__/List.test.tsx.snap
Addresses https://github.com/contentful/forma-36/issues/423 by introducing the tag change in the List component.
tagging @fabe for design review on the addition of the ordered list
=> feat: handle tag change in the List component

packages/forma-36-react-components/src/components/Button/Button.stories.tsx, packages/forma-36-react-components/src/components/Button/Button.test.tsx, packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
~~Adds the optional "isExternalLink" boolean property to the Button component, which, if enabled
together with the "href" property, sets 'target="_blank"' and 'rel="noopener noreferrer"' on the
resulting html tag.~~
~~I have previously worked around this by using an onclick={() => window.open(url, '_blank');}, which isn't as nice for accessibility.~~
**Edit:**
Adds the optional `target` and `rel` props for the Button component, which only get rendered if the component gets rendered as an anchor tag.
As Kristoffer mentioned, you're already able to use these but the types are complaining, which is alleviated by this PR.
=> feat(button): add additional optional properties for using Buttons as external links

packages/forma-36-react-components/src/components/CopyButton/__snapshots__/CopyButton.test.tsx.snap, packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/__snapshots__/EditorToolbarButton.test.tsx.snap, packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forma-36-react-components/src/components/TextInput/__snapshots__/TextInput.test.tsx.snap, packages/forma-36-react-components/src/components/Tooltip/Tooltip.css, packages/forma-36-react-components/src/components/Tooltip/Tooltip.stories.tsx, packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx, packages/forma-36-react-components/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
A fix for #805
See https://github.com/facebook/react/issues/4251#issuecomment-267004045
=> fix(tooltip): pointer-events disabled on button toggles

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.tsx
Align possible entity statuses with [field-editor-helpers](https://github.com/contentful/field-editors/blob/master/packages/_shared/src/utils/entityHelpers.ts#L169-L186)
forma was missing the `deleted` status
=> chore(AssetCard): align possible entity status

packages/forma-36-react-components/src/components/Table/TableHead/TableHead.css
Fixes #793 by adding a `z-index` value to `th` elements when `isSticky` is used.
=> fix(table): add z-index to table head

packages/forma-36-react-components/src/components/Checkbox/Checkbox.stories.tsx, packages/forma-36-react-components/src/components/CheckboxField/CheckboxField.stories.tsx, packages/forma-36-react-components/src/components/Form/FieldGroup/FieldGroup.stories.tsx, packages/forma-36-react-components/src/components/Form/Form.stories.tsx, packages/forma-36-react-components/src/components/FormLabel/FormLabel.stories.tsx, packages/forma-36-react-components/src/components/RadioButton/RadioButton.stories.tsx, packages/forma-36-react-components/src/components/RadioButtonField/RadioButtonField.stories.tsx, packages/forma-36-react-components/src/components/Select/Select.stories.tsx, packages/forma-36-react-components/src/components/SelectField/SelectField.stories.tsx, packages/forma-36-react-components/src/components/Switch/Switch.stories.tsx, packages/forma-36-react-components/src/components/TextField/TextField.stories.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.stories.tsx, packages/forma-36-react-components/src/components/Textarea/Textarea.stories.tsx, scripts/.storybook/preview.js
With the intention to organize our usage examples, I propose to create a section for the components related to Forms
Since they are usually used in the same context, grouping these components makes it easier to find them
=> docs(forms): create section for form components

packages/forma-36-react-components/src/components/ControlledInput/ControlledInput.css, packages/forma-36-react-components/src/components/RadioButtonField/RadioButtonField.stories.tsx
Hey F36!
Small fix for styles for disabled Radio buttons. 
**BEFORE:**
**AFTER:**
=> fix: fix styles for disable Radio button

packages/forma-36-website/src/pages/index.mdx
Added a note about the need to have a Figma account to use the UI Kit to the UI Kit part on the homepage.
=> docs: add notes about figma account to the home page

packages/forma-36-website/src/pages/index.mdx
Change the URL to automatically create a duplicate
Move the note about a necessary Figma account to the end
=> docs: add notes about figma account to the home page part 2

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx
The purpose of this PR is to `preventDefault` when hitting Enter in the Autocomplete component.
Related discussion that led to this PR is [here](https://github.com/contentful/forma-36/pull/846).
=> feat(autocomplete): add preventDefault for enter key

packages/forma-36-react-components/src/components/Flex/Flex.tsx
Fix typo in Flex `fullHeight` prop
=> fix(flex): typo in fullHeight prop preventing the height to take effect

packages/forma-36-react-components/package.json
Correct the `module` field of `package.json` to point to the correct esm file.
=> fix: correct esm entry file

package.json, yarn.lock
Upgrades to TypeScript v4. I'd like to get this change in because I ran into a TS bug that's blocking #864, which got fixed in 4.1.5 🙂
=> v4 chore: upgrade to TypeScript v4

packages/forma-36-react-components/src/components/Tag/Tag.css
The typography [changes](https://github.com/contentful/forma-36/pull/823/files#diff-825231766b7f9c91f84f3a1ed1959049497b3fcb75fcdeeceda45ad6d69cc997L3) introduced in #823 changed the token value used in the Tag component and made
the text thinner than it should be considering it's all caps and smaller text size. Reverting to
font-weight: 600.
=> style(tag): increase font-weight to correct changes made in #823

packages/components/datepicker/CHANGELOG.md, packages/components/timepicker/CHANGELOG.md, packages/forma-36-react-components/.size-limit, packages/forma-36-react-components/CHANGELOG.md, packages/forma-36-react-components/src/components/Tag/README.mdx, packages/forma-36-react-components/src/components/Tag/Tag.css, packages/forma-36-react-components/src/components/Tag/Tag.stories.tsx, packages/forma-36-react-components/src/components/Tag/Tag.tsx, packages/forma-36-react-components/src/styles/settings/colors.css
Adding `featured` tagType to Tag, as requested by @fabe
=> feat: add 'featured' tagType to Tag

package.json
To make semantic-release format its CHANGELOG before committing.
=> build: add postversion script

packages/forma-36-react-components/src/components/CopyButton/CopyButton.css
Fix for CopyButton icon not being centered. The problem seems to be CSS specificity issues that show up in our production build but not in development, which is why the problem doesn't show in Storybook. The  `TabFocusTrap` component's default `display: inherit` value is overriding the CSS from CopyButton which sets it to `display: flex`.
I tried changing the class name order around and it didn't fix the problem 🤔 
Closes #904
=> fix(copy-button): center icon alignment

packages/components/datepicker/CHANGELOG.md, packages/components/timepicker/CHANGELOG.md, packages/forma-36-react-components/CHANGELOG.md, packages/forma-36-react-components/src/components/Button/Button.css, packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
A medium or large button with `indicateDropdown` being `true` has a too small right-padding. The paddings should be the same on both sides. Right now this is only the case for a small button since its CSS styles have a higher specificity than ".is--dropdown".
Before:
After:
=> fix: equal left & right paddings in a dropdown button

.circleci/config.yml, package.json, packages/components/datepicker/CHANGELOG.md, packages/components/timepicker/CHANGELOG.md, packages/forma-36-react-components/CHANGELOG.md
Chromatic job is using a secret environment variable that isn't visible to forked PRs.
https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/ suggests to disable the step and allow running them only after collaborator executes a command:
```bash
git-push-fork-to-upstream-branch upstream <fork_username>:<fork_branch>
```
=> chore: don't run chromatic for external prs

packages/components/validation-message/src/ValidationMessage.tsx
We should use `FlexInternalProps` since we're using the `Flex` component.
=> fix(validation-message): use FlexInternalProps

packages/forma-36-react-components/src/components/Workbench/Workbench.tsx
Makes `children` property of `Workbench.Sidebar` and `Workbench.Content` optional. It's already a `React.ReactNode` type, so `undefined` is allowed. My change would allow to render them as self-enclosed: `<Workbench.Sidebar position="right" />`
=> fix: make children optional in Workbench sidebar and content

packages/forma-36-react-components/src/components/DateTime/DateTime.test.tsx, packages/forma-36-react-components/src/components/DateTime/DateTime.tsx, packages/forma-36-react-components/src/components/DateTime/__snapshots__/DateTime.test.tsx.snap, packages/forma-36-react-components/src/components/DateTime/dateUtils.test.ts, packages/forma-36-react-components/src/components/DateTime/dateUtils.ts
When one uses DateTime only showing the date or time, the `datetime` attribute should represent that, too.
I followed the respective [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time#valid_datetime_values) regarding which formats are allowed.
=> feat: Machine Readable Formats for DateTime with DATE_ONLY or TIME_ONLY

packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
The current size of the spinner in buttons is not related to any value in the button — padding, label or line-height.
I suggest we reduce the size so that it sits on the baseline of the label and is closer in size to an ellipsis.
**Current**
**Proposed change**
=> style(button spinner): reduce the size of the new spinner in buttons

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.css
Under some circumstances, the margin style of `.inputIconButton` class get's overwritten, which results in a wrongly placed dropdown indicator button.
This PR adds a more specific css class path to ensure the domination of the button class.
=> fix(autocomplete): dropdown button position

packages/forma-36-react-components/src/components/EmptyState/EmptyState.css
In Launch app we discovered broken margins when using the `EmptyState`. While we have `margin-bottom` for paragraph and heading in the storybook, the according to rules are overwritten if using F36 in another place (like the Launch app). @mshaaban0 pointed out that this issue is known and advised me to improve the selector specificity for this particular case.
Storybook | Launch
------------ | -------------
=> fix: Restore Margins on EmptyState in Product [HOMER-23]

packages/forma-36-react-components/src/components/Typography/DisplayText/DisplayText.tsx, packages/forma-36-react-components/src/components/Typography/Heading/Heading.tsx, packages/forma-36-react-components/src/components/Typography/Paragraph/Paragraph.tsx, packages/forma-36-react-components/src/components/Typography/SectionHeading/SectionHeading.tsx, packages/forma-36-react-components/src/components/Typography/Subheading/Subheading.tsx, packages/forma-36-react-components/src/components/Typography/Typography/Typography.tsx
This PR adds `title` attribute to all Typography components. 
`title` is a global HTML attribute and can be used on any HTML tag. There are multiple usages of it in our Contentful web app. To make Typescript happy we should have it listed in the props.
=> feat: adds title attribute to typography components

packages/forma-36-react-components/src/components/ControlledInputField/ControlledInputField.tsx, packages/forma-36-react-components/src/components/SelectField/SelectField.tsx, packages/forma-36-react-components/src/components/TextField/TextField.tsx
This PR narrows down types of some inputs handlers, specifically `onChange`, `onBlur`, `onFocus`.
=> fix: fix inputs onChange, onBlur, onFocus types

packages/components/inputs/README.mdx, packages/components/inputs/src/checkbox/Checkbox.test.tsx, packages/components/inputs/src/checkbox/Checkbox.tsx, packages/components/inputs/src/checkbox/README.mdx, packages/components/inputs/src/controlled-input/ControlledInput.test.tsx, packages/components/inputs/src/controlled-input/ControlledInput.tsx, packages/components/inputs/src/controlled-input/README.mdx, packages/components/inputs/src/radio-button/README.mdx, packages/components/inputs/src/radio-button/RadioButton.test.tsx, packages/components/inputs/src/radio-button/RadioButton.tsx, packages/components/inputs/stories/Checkbox.stories.tsx, packages/components/inputs/stories/RadioButton.stories.tsx, packages/forma-36-react-components/README.md, packages/forma-36-react-components/src/components/ControlledInputField/ControlledInputField.tsx
Following up on the new created f36-inputs package, we want to have all components in this package documented and sticking to our guidelines.
Used Guidelines:
https://contentful.atlassian.net/wiki/spaces/PROD/pages/2821095662/F36+Code+Styleguide
https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#development
=> feat: follow guidelines for f36-inputs [HOMER-37]

jest.config.js, packages/components/timepicker/package.json, packages/components/timepicker/src/Timepicker.tsx, yarn.lock
The old function specific lodash packages aren't supported anymore and haven't been updated in years. We could switch to lodash or lodash-es, I went with the latter to hopefully get a smaller build without having to change our tooling.
=> v4 chore(deps): switch function specific lodash packages to lodash-es

packages/components/inputs/src/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/components/inputs/src/controlled-input/ControlledInput.tsx, packages/components/inputs/src/controlled-input/__snapshots__/ControlledInput.test.tsx.snap, packages/components/inputs/src/radio-button/__snapshots__/RadioButton.test.tsx.snap, packages/forma-36-react-components/src/components/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap, packages/forma-36-react-components/src/components/ControlledInputField/__snapshots__/ControlledInputField.test.tsx.snap, packages/forma-36-react-components/src/components/Form/FieldGroup/__snapshots__/FieldGroup.test.tsx.snap, packages/forma-36-react-components/src/components/RadioButtonField/__snapshots__/RadioButtonField.test.tsx.snap
For migrating ControlledInputField, we want to pass styles down to the label component. Thus, we add the prop `labelProps` in the same manner as `inputProps`.
[See related comment](https://github.com/contentful/forma-36/pull/954/files#r637008561)
=> feat: enable passing props down to label in ControlledInput [Homer 25]

packages/forma-36-react-components/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forma-36-react-components/src/components/TextInput/TextInput.stories.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.test.tsx, packages/forma-36-react-components/src/components/TextInput/TextInput.tsx
fixes #894
Addressed originally in #971
=> fix: add labelText prop support to TextInput component

packages/forma-36-react-components/src/components/Select/Option.tsx, packages/forma-36-react-components/src/components/Select/README.mdx, packages/forma-36-react-components/src/components/Select/Select.test.tsx, packages/forma-36-react-components/src/components/Select/__snapshots__/Select.test.tsx.snap
In our use case at Team Homer, we needed a select element with a placeholder. It's a common pattern to add an option with an empty string, and selected and disabled set to true. Due to missing props definitions this raised typescript errors.
=> feat: extend Options props to supported native props like disabled []

packages/forma-36-react-components/src/components/Card/AssetCard/AssetCard.test.tsx, packages/forma-36-react-components/src/components/Card/AssetCard/__snapshots__/AssetCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/CardActions/CardActions.test.tsx, packages/forma-36-react-components/src/components/Card/CardActions/__snapshots__/CardActions.test.tsx.snap, packages/forma-36-react-components/src/components/Card/EntryCard/EntryCard.test.tsx, packages/forma-36-react-components/src/components/Card/EntryCard/__snapshots__/EntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Card/InlineEntryCard/InlineEntryCard.test.tsx, packages/forma-36-react-components/src/components/Card/InlineEntryCard/__snapshots__/InlineEntryCard.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/Dropdown.test.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/__snapshots__/DropdownContainer.test.tsx.snap, packages/forma-36-react-components/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/forma-36-react-components/src/components/EntityList/EntityListItem/EntityListItem.test.tsx, packages/forma-36-react-components/src/components/EntityList/EntityListItem/__snapshots__/EntityListItem.test.tsx.snap
This PR fixes the issue of focus order on dropdown open and close
Previously the dropdown container won't be focused as the dropdown gets appended at the end of document body
Now dropdown container receives focus on open, and the toggle element receives the focus back on close
Same behaviour applied on submenus as well, it'll open when the `subToggleElement` is focused and clicked
https://user-images.githubusercontent.com/6163988/121927562-7d139080-cd3f-11eb-9ffd-b23020db2313.mov
=> fix: add keyboard support to dropdown elements [SPA-262]

packages/forma-36-react-components/src/components/Modal/ModalContent/ModalContent.css, packages/forma-36-react-components/src/components/Modal/ModalControls/ModalControls.css
Removes negative margin top on ModalControls and fix padding on ModalContent to account for not having the negative margin anymore.
Closes #995
=> fix(modal-controls): remove negative margin-top and fix padding

.github/dependabot.yml, .github/labeler.yml, .github/semantic.yml, .github/workflows/auto-approve.yml, .github/workflows/labeler.yml
Aligns Github actions configuration with the rest of open-source repositories:
* Updated dependabot configuration
* Auto-approve for dependabot PRs
* Automatic labels for PRs with component names that are touched in this PR
* Semantic titles validation
=> ci: align github actions setup with field-editors repository

packages/forma-36-react-components/src/components/Pill/Pill.tsx
#1031 Fix pill types to include `...otherProps`
=> fix: Include `...otherProps` in Pill types

packages/forma-36-website/src/pages/index.jsx
Currently on the F36 website [View all components in Storybook] points to https://f36.contentful.com/storybook. But, all the storybook links in the components point to https://f36-storybook.contentful.com/. I feel https://f36-storybook.contentful.com/ appropriate.
More explanation here 👇
https://loom.com/share/87b97f3782d34b06b49683ab8f391e53
=> docs: update Forma36 storybook link on Forma36 website

packages/components/button/src/Button.tsx, packages/components/button/src/styles.ts, packages/components/button/src/types.ts, packages/components/button/stories/Button.stories.tsx
In order to be able to merge IconButton into the Button in v4, we need to introduce a transparent variant of the component.
I made small adjustments for icon sizes and display couple more examples in the storybook.
Next PR - create a separate component for the divided version:
=> fix: introduce transparent variant of the button component

packages/core/src/Flex/Flex.tsx
Add [CSS `gap` property](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) to `Flex` component.
=> feat(flex): add gap property

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
With the recent fixes for dropdown component to focus the dropdown container on open, that is interrupting input on autocomplete component as the focus moves out of input on focusing
This PR adds `focusContainerOnOpen` on open property to `Dropdown` and setting it to false on `Autocomplete` as autocomplete already handling mouse up and down, and doesn't need focus on content container
=> fix: add focusContainerOnOpen prop on Dropdown

packages/forma-36-react-components/src/components/Skeleton/SkeletonDisplayText/SkeletonDisplayText.stories.tsx, packages/forma-36-react-components/src/components/Skeleton/SkeletonImage/SkeletonImage.stories.tsx, packages/forma-36-react-components/src/components/Skeleton/SkeletonRow/SkeletonRow.stories.tsx
Most of our skeleton components don't take classnames. This PR removes the `className` prop from stories for those components, to avoid confusion.
Closes #992
=> docs: remove classNames from Skeleton component stories

packages/components/button/package.json, packages/components/empty-state/package.json, packages/components/forms/src/Label/Label.tsx, packages/components/helptext/package.json, packages/components/icon/package.json, packages/components/icons/package.json, packages/components/inputs/src/controlled-input/ControlledInput.tsx, packages/components/list/package.json, packages/components/note/package.json, packages/components/pill/package.json, packages/components/table/src/Table.tsx, packages/forma-36-react-components/src/components/Card/Card.tsx, packages/forma-36-react-components/src/components/TextLink/TextLink.tsx
Fixes missing dependencies in packages and improve typings.
We need to find an ESLint plugin that catches a situation when you use dependency but it's not specified in package.json of the corresponding package.
=> refactor: fix dependencies and improve types

packages/forma-36-react-components/CHANGELOG.md, packages/forma-36-react-components/src/components/Card/Card.stories.tsx, packages/forma-36-react-components/src/components/DateTime/README.mdx, packages/forma-36-react-components/src/components/DateTime/RelativeDate/RelativeDate.tsx, packages/forma-36-react-components/src/components/Spinner/README.mdx, packages/forma-36-react-components/tools/rollup.umd.config.js, packages/forma-36-website/gatsby-config.js, packages/forma-36-website/src/components/DocSearch.jsx
👋
It happens quite often that people remove the space from the Forma 36 name and write it as "Forma36". This PR removes any last instances of such naming from our code. Hopefully this helps avoid confusion about how Forma 36 is written 🙂 
The only remaining question is if we should bother renaming the community Slack channel to `#forma-36` instead of `#forma36`.
=> docs: we are Forma 36

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.tsx
Closes #1075 by preventing Dropdown from scrolling to the focused dropdown on open.
=> fix(dropdown-container): force window not to scroll on dropdown focus

packages/forma-36-react-components/src/components/Accordion/Accordion.stories.tsx, packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.css, packages/forma-36-react-components/src/components/Accordion/AccordionPanel/AccordionPanel.tsx, packages/forma-36-react-components/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Make `AccordionPanel` height dynamically adjustable to its content. So whenever content size changes the height of `AccordionPanel` adapt to it.
Closes #962
=> fix(accordion): make AccordionPanel height adjustable to content

packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx
There is an issue sometimes, when `toggleElementNode` is `null`, it causes a TypeError. This check should fix it, at least avoid chasing an app.
=> fix(dropdown): fix "`focus` of `null`" error in Dropdown component

packages/forma-36-react-components/src/components/Switch/Switch.css
adds missing `font-family: var(--font-stack-primary)` declaration for Switch labels to `Switch.css`
=> fix(switch.css): adds missing font-family: var(--font-stack-primary) declaration for Switch labels

packages/components/badge/src/types.ts, packages/components/button/src/types.ts, packages/components/icon/src/Icon.tsx, packages/components/note/src/Note.tsx, packages/components/spinner/src/Spinner.tsx, packages/components/text-link/src/types.ts, packages/core/src/index.ts, packages/core/src/types.ts
Inline all component variants instead of picking and excluding from the shared type.
=> refactor: inline all component variants [BAU-59]

packages/forma-36-react-components/src/components/Workbench/Workbench.tsx, packages/forma-36-react-components/src/components/Workbench/__snapshots__/Workbench.test.tsx.snap
Currently workbench is structured with divs only, this should be changed to use semantic html main aside  and header
We need to expose aria-label for these tags as well so screen reader users can determine the purpose of these tags
For more info see landmarks and page regions docs  https://www.w3.org/TR/WCAG20-TECHS/ARIA11.html
=> feat: improve Workbench a11y support

packages/forma-36-react-components/src/components/Button/Button.tsx
Spinner stays on downstream services when loading is finished, so taking a conservative approach again and unmount on exit.
=> fix(button): unmount spinner on exit

packages/forma-36-react-components/src/components/Workbench/Workbench.tsx, packages/forma-36-react-components/src/components/Workbench/__snapshots__/Workbench.test.tsx.snap
Based on the current webapp status, most of the single sidebars are used on the right side which makes it primary by default.
=> fix: workbench sidebar label

packages/forma-36-tokens/README.md
Correct two tiny typos in links. Can't find info on the commit message format for something that shouldn't trigger a release, so I'm hoping `Typo:` works.
=> chore: `form` -> `forma`

packages/forma-36-react-components/src/components/Button/README.mdx
Closes https://github.com/contentful/forma-36/issues/1046
This PR will update code examples for Buttons, this is how they look now:
=> docs: add space between buttons in the website

.circleci/config.yml
Since we would like to start the adoption of the v4 in clients, we would like to deploy new packages from v4
=> chore: enable auto deploy of the v4 packages

packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.stories.tsx, packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.tsx
Add `closeAll` method to the `ModalLauncher`.
It works by storing all the root elements ids, on a Map, when the `open` method is called, and iterating over the map when the `closeAll` method is called to render with `{ isShown: false }`, and waiting for the set delay before removing the element from the tree, so it keeps the closing animation.
Also removes the value from the map in case the modal is closed through the onClosed.
=> feat(modallauncher): add closeAll method to ModalLauncher

packages/components/badge/src/getBadgeStyles.ts, packages/components/badge/src/types.ts, packages/components/badge/stories/Badge.stories.tsx
Remove the muted variant from Badge component (it is already deprecated in v3)
i will add an option to migrate it with the codemod.
=> fix: remove muted Badge variant

scripts/.storybook/preview.js, scripts/plop-templates/package/src/Component.tsx.hbs
- Remove the old hack to create docs from our old "note" files
- Set storybook to render mandatory props on top of the prop table
- in the plop template for Component
- change the place of the `_{{ComponentName}}` pattern
- move the React import to the first line :P
- remove `testId` and `className` from the props type because they are inherited from CommonProps
=> chore: small improvements to storybook and plop template

packages/forma-36-website/gatsby-browser.js
Well... apparently Netlify use `NODE_ENV=production` for both production and preview deployments
So we need to check `CONTEXT` in order to NOT send tracked events of our previews to Segment in production 👀
=> chore: make netlify use different segment in preview and branch deploys

packages/forma-36-react-components/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forma-36-react-components/src/components/TextLink/TextLink.css, packages/forma-36-react-components/src/components/TextLink/TextLink.tsx, packages/forma-36-react-components/src/components/TextLink/__snapshots__/TextLink.test.tsx.snap
Resolves
- Use `span` instead of `div` to resolve semantic warnings
- Align text and icon center
=> fix: text link semantics and alignment

packages/forma-36-react-components/src/components/EditorToolbar/EditorToolbarButton/EditorToolbarButton.tsx
Adds support for custom Tooltip placement of the `<EditorToolbarButton>` component ~while defaulting to `bottom` to make the behavior in the current web app consistent~.
=> feat(EditorToolbarButton): custom Tooltip placement

.circleci/config.yml, package.json
- exposes chromatic's token in package.json so it does not fail in forked PRs anymore.[ This is recommended for open source projects](https://www.chromatic.com/docs/circleci#run-chromatic-on-external-forks-of-open-source-projects)
- make chromatic-deployment not required to release f36 packages
- rename circle-ci workflow from `commit-check` to `f36-build`
=> chore: expose chromatic token in package json

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.css, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.stories.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.test.tsx, packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Autocomplete/README.mdx, yarn.lock
The Autocomplete component was not able to handle a possible error state e.g. if the component is required. Now it accepts a boolean prop named error as well as a validationMessage to display below the component.
=> fix(Autocomplete): add error handling possibility

packages/components/copybutton/src/CopyButton.styles.ts, packages/components/copybutton/src/CopyButton.tsx, packages/components/tooltip/src/Tooltip.tsx
We would need to allow CopyButton to be disbaled on order to make it work nicely with input, when it's disbaled.
When CopyButton is disabled, we should not show the tooltip.
=> fix: allow isDisabled property for CopyButton

packages/forma-36-react-components/src/components/Modal/ModalConfirm/ModalConfirm.tsx, packages/forma-36-react-components/src/components/Modal/ModalConfirm/__snapshots__/ModalConfirm.test.tsx.snap, packages/forma-36-react-components/src/components/Modal/ModalLauncher/ModalLauncher.stories.tsx
A customer is complaining that a confirmation modal with some content doesn't render properly on smaller devices. The content overflows and makes it impossible to submit the dialog.
This works for the normal modal while it doesn't work for the confirmation one because we render a `<div>` container breaking the intended scrolling behavior of the modal.
After the fix:
While investigating this bug and clicking through modals in the storybook, I was getting annoyed by the ModalLauncher stories always creating a modal on mount. I guess it's part of the story but at least I expect it to close them again if I switch to another story. With the unmount function I'm doing this now.
- [o] Tests are added/updated/not required
=> fix(Modal): story improvement & allow scrolling in ModalCofirm []

packages/components/forms/src/checkbox/Checkbox.tsx, packages/components/forms/src/radio/Radio.tsx, packages/components/forms/src/select/Select.mdx, packages/components/forms/src/select/Select.test.tsx, packages/components/forms/src/select/Select.tsx, packages/components/forms/src/select/SelectOption.tsx, packages/components/forms/src/switch/Switch.tsx, packages/components/forms/stories/Form.stories.tsx, packages/components/forms/stories/FormControl.stories.tsx, packages/components/forms/stories/Select.stories.tsx
* Refactor `Select` component to use `value` and `defaultValue` instead of isSelected on the option.
* Update documentation with examples.
=> refactor:(select) use defaultValue and value props instead of isSelected

packages/components/forms/src/base-checkbox/BaseCheckbox.styles.ts, packages/components/forms/src/base-checkbox/BaseCheckbox.tsx, packages/components/forms/src/base-checkbox/GhostCheckbox.styles.ts, packages/components/forms/src/base-checkbox/GhostCheckbox.tsx, packages/components/forms/src/base-checkbox/types.ts, packages/components/forms/src/checkbox/Checkbox.tsx, packages/components/forms/src/radio/Radio.tsx, packages/components/forms/stories/Switch.stories.tsx
Adds the `size` prop to render the switch component smaller or on medium(default) size.
=> feat(switch): add sizes to Switch input component

packages/components/forms/src/form-label/FormLabel.styles.ts
While working on integrating our v4 forms to react-hook-form, I noticed that our FormLabels had `font-weight: 400`
But looking in the designs they should have `font-weight: 500` which is our `fontWeightMedium` token
So I created this PR
before:
after:
design in Figma:
=> fix: FormLabel font weight should be 500

packages/components/forms/src/base-checkbox/BaseCheckbox.styles.ts, packages/components/forms/src/base-checkbox/BaseCheckbox.tsx, packages/components/forms/src/base-checkbox/BaseCheckboxGroup.tsx, packages/components/forms/src/base-checkbox/BaseCheckboxGroupContext.tsx, packages/components/forms/src/base-checkbox/GhostCheckbox.styles.ts, packages/components/forms/src/base-checkbox/types.ts, packages/components/forms/src/checkbox/Checkbox.mdx, packages/components/forms/src/checkbox/Checkbox.tsx, packages/components/forms/src/checkbox/CheckboxGroup.tsx, packages/components/forms/src/form-label/FormLabel.tsx, packages/components/forms/src/radio/Radio.mdx, packages/components/forms/src/radio/Radio.tsx, packages/components/forms/src/radio/RadioGroup.tsx, packages/components/forms/stories/CheckboxGroup.stories.tsx, packages/components/forms/stories/FormControl.stories.tsx, packages/components/forms/stories/RadioGroup.stories.tsx
Add a default styling for the BaseCheckboxGroup.
=> refactor: Add default styling for BaseCheckboxGroup

packages/forma-36-react-components/src/components/Button/Button.stories.tsx, packages/forma-36-react-components/src/components/Button/Button.tsx
We want to use the button with a loading state in our use case. We observe buggy behaviour when removing the loading animation (the animation comes back and never disappears). 
We wanted to check if the button actually supports removing the loading animation. Because the storybook is missing an example so far I added one and tested with it. It works in the storybook, so we will do further investigations. I think it's good to keep this story for others.
*Update:*
I found a fix in [this github issue](https://github.com/reactjs/react-transition-group/issues/338#issuecomment-442538453). By checking the transition status on our own we can make sure that it's really unmounted if the status is "unmounted".
https://user-images.githubusercontent.com/9327071/132471918-6642c0fc-d701-41fb-ad32-49238f1 …
=> fix(Button): hide spinner when loading is false

packages/forma-36-react-components/src/components/ControlledInput/ControlledInput.css
Fix issue on RadioButton disabled always being marked as checked.
=> fix(radiobutton): wrong style on disabled radiobutton

.github/ISSUE_TEMPLATE/bug-report.md, packages/forma-36-website/src/pages/index.jsx
I created the Codesandbox template so people can share examples of their usage faster with us
and the dev relationship team suggested to put it in the official docs somewhere so I opened this PR that will add this to Forma 36’s home
It also adds link to the template in our Bug report template
=> docs: add embed code sandbox template to website

packages/components/tooltip/Tooltip.mdx, packages/forma-36-codemod/README.md, packages/forma-36-codemod/bin/inquirer-choices.js, packages/forma-36-codemod/transforms/__testfixtures__/v4-tooltip.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v4-tooltip.output.js, packages/forma-36-codemod/transforms/__tests__/v4.test.js, packages/forma-36-codemod/transforms/v4-tooltip.js
This PR adds a codemod for Tooltip component from v3 to v4.
=> chore(tooltip): create codemod for Tooltip component

packages/components/button/src/Button.tsx
Pass disabled to button when rendered as `<a />`
=> fix(button): add missing property when rendered as a tag

packages/forma-36-website/gatsby-config.js
This might be a moment to remove the note regarding the colors update from the website? It's been there for 2 months. WDYT?
=> fix: remove migration note regarding colors migration

packages/forma-36-react-components/src/components/Dropdown/DropdownContainer/DropdownContainer.css
Refine dropdown container focus style 
**Before**
**After**
=> fix: dropdown container focus styles

packages/components/forms/stories/FormControl.stories.tsx, packages/core/src/GlobalStyles/GlobalStyles.tsx
Add css reset for `fieldset` on `GlobalStyles`
=> fix(globalstyles): add fieldset reset to GlobalStyles

packages/forma-36-codemod/transforms/__testfixtures__/v4-tooltip.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v4-tooltip.output.js, packages/forma-36-codemod/transforms/v4-tooltip.js
To make this change visible, I added a "console.error". If consumer won't update the property, it will lead to type errors.
=> feat(tooltip-v4): update tooltip-v4 codemod to add console error for wrong prop type

packages/components/forms/src/base-input/BaseInput.tsx
Completely removes `(e.target as HTMLInputElement).select();`. Fixes https://github.com/contentful/field-editors/pull/867
=> fix: remove select on disabled and readonly

packages/components/button/src/IconButton/IconButton.tsx, packages/components/button/stories/IconButton.stories.tsx
Add default variant, and default icon color per variant to make the usage easier
https://5fd1dda724cc620021ace8c5-qzqoodjook.chromatic.com/?path=/story/components-button-iconbutton--basic&args=iconProps.variant:negative;iconProps.size:large
=> refactor(iconbutton): add default icon colors and default variant

packages/components/utils/src/index.ts, packages/components/utils/src/useKeyboard/useKeyboard.spec.tsx, packages/components/utils/src/useKeyboard/useKeyboard.ts
closes https://github.com/contentful/forma-36/discussions/1008
Example usage
```js
useKeyboard({
event: 'keydown', // Optional, default is `keydown`
ref: yourReactRef, // Optional, by default event is attached to document
keys: {
ArrowUp: (e) => handleArrowUp(e),
Tab: (e) => handleTab(e)
}
})
```
=> feat: add useKeyboard hook to f36-utils

packages/components/autocomplete/src/Autocomplete.tsx, packages/components/autocomplete/test/Autocomplete.test.tsx, packages/components/popover/src/PopoverContent/PopoverContent.styles.ts, packages/components/popover/src/PopoverContent/PopoverContent.tsx, packages/components/popover/test/Popover.test.tsx
Besides adding tests I made the Popover.Content to always be in the DOM
That's necessary for a better a11y of the Autocomplete and it makes downshift stop throwing that error about the menuRef that you probably saw already
I made this the default behaviour, do you think it should be optional? Something that we control with a prop?
But I really don't know if I'm breaking something with my solution for that hahahaha
(I'm just using `display: 'none' when !isOpen`)
so please test it!
=> test: add tests to v4 autocomplete

packages/components/menu/Menu.mdx, packages/components/menu/src/Menu.tsx, packages/components/menu/stories/Menu.stories.tsx, packages/components/menu/test/Menu.test.tsx, packages/components/utils/src/ArrowKeyNavigation/useArrowKeyNavigation.ts
Extend Menu component logic to be able to accept `initialFocusedItem` prop
=> feat(menu): add initial focused item index logic

packages/forma-36-website/src/components/ComponentSource.js
I think the Card component now does not allow us to do `padding="none"` so the code preview got some weird spacing, and this PR tries to fix it
before the fix
after fix
For some reason, emotion is working differently in production
So if you check the website in production, the whole example of the components are using monospace fonts
but in local development, only the code editor is using monospace (as expected)
And this makes it hard to fix this issue. This PR tries to change some styles to make only the code editor monospace, but we will only know when this is deployed
I will open a bug ticket to check why are we having this difference between the styles in prod and in dev
=> docs: fix code preview after changes in Card

packages/forma-36-codemod/transforms/__testfixtures__/v4-select.output.js, packages/forma-36-codemod/transforms/v4-select.js
Update Select codemod to drop width property.
=> refactor(codemod): remove width from Select component codemod

packages/forma-36-react-components/src/components/Button/Button.tsx, packages/forma-36-react-components/src/components/Button/__snapshots__/Button.test.tsx.snap
Remove button `type` attribute when href is defined
=> fix: remove button type attribute when href is defined

packages/forma-36-website/src/content/foundation/typography/index.mdx
=> fix(website docs): remove reference to Sketch UI kit from forma-36 website

packages/core/src/ScreenReaderOnly/ScreenReaderOnly.mdx, packages/forma-36-website/gatsby-config.js
Since `ScreenReaderOnly` is a component and its route is `/components/ScreenReaderOnly`, I moved it to the Components section and changed the route to follow our convention
=> docs: screen reader only under components

docs/folder-structure.md
While working on the Next.js experiment, I noticed that we are not following any convention on how to organise our files in the repo. This was noticeable because the website tries to generate pages from the .mdx files, but they are not always in the same places or with the same name
I created a guide that proposes a structure for our files similar to what we have in the "features" folder in the webapp project
Please comment, suggest things, and fix my grammar!
Right now, in v4, we always have two MD files in a folder because one markdown has the documentation of that component and the other has a warning for people who is using it during our "alpha" phase
We are almost releasing the beta version of v4 and all the documentation of every component will be moved to README.mdx files
That's …
=> docs: folder structure guide

MIGRATION.md, packages/components/copybutton/CopyButton.mdx, packages/components/forms/src/radio/Radio.mdx, packages/components/forms/src/text-input/TextInput.mdx, packages/components/popover/Popover.mdx, packages/components/text-link/TextLink.mdx, packages/components/tooltip/Tooltip.mdx, packages/core/src/ScreenReaderOnly/ScreenReaderOnly.mdx
a small fix for documentation website: use all-lower-case on anchor on-page links
Why: the anchor navigation only works with all-lower-case letters in the link
=> fix(docs): fix in-page nvigation with anchors

packages/forma-36-website/src/components/Navigation.js
Make it so the submenus area always rendered even when not expanded, so the docsearch crawler can correctly find the links to be indexed.
Improve keyboard navigation on the menu
=> refactor(website): Improve navigation on menu and submenu rendering

packages/forma-36-website/src/components/Navigation.js
Make it so the submenus area always rendered even when not expanded, so the docsearch crawler can correctly find the links to be indexed.
Improve keyboard navigation on the menu
=> refactor(website): make the submenus always rendered but hidden

packages/components/badge/Badge.mdx, packages/components/entity-list/EntityList.mdx, packages/components/list/List.mdx, packages/core/src/Grid/Grid.mdx, scripts/lint-packages.js
=> docs(website): add missing prop tables

packages/components/autocomplete/src/Autocomplete.styles.ts, packages/components/autocomplete/src/Autocomplete.tsx, packages/components/autocomplete/src/AutocompleteItems.tsx, packages/components/autocomplete/stories/Autocomplete.stories.tsx, packages/components/autocomplete/test/Autocomplete.test.tsx
- I don't see the need in rendering an empty group. It should be our default behaviour to not render this until needed otherwise.
- Currently, we need to define the font explicitly for the AutoCompleteItems (only for those). Same as for all components, this should be defined in the library.
=> fix: autocomplete style & empty groups

packages/components/forms/src/checkbox/Checkbox.mdx, packages/components/forms/src/form-control/FormControl.mdx, packages/components/forms/src/form-control/FormControl.tsx, packages/components/forms/src/form-label/FormLabel.tsx, packages/components/forms/src/radio/Radio.mdx, packages/components/forms/stories/FormControl.stories.tsx, packages/components/forms/stories/Formik.stories.tsx, packages/components/forms/stories/ReactHookForm.stories.tsx, packages/components/forms/stories/ReactHookFormControlledInputs.stories.tsx, packages/forma-36-website/src/content/integrations/react-hook-form/index.mdx
Make it possible to render the `FormControl` as `fieldset` and the `Form.Label` as `legend` to be used when grouping with `RadioGroup` or `CheckboxGroup`
=> refactor(formcontrol): add possibility to render fieldset and legend

packages/components/forms/src/base-checkbox/BaseCheckbox.tsx, packages/components/forms/src/checkbox/Checkbox.mdx, packages/components/forms/src/checkbox/CompoundCheckbox.tsx, packages/components/forms/src/form-control/FormControl.mdx, packages/components/forms/src/index.ts, packages/components/forms/src/radio/CompoundRadio.tsx, packages/components/forms/src/radio/Radio.mdx, packages/components/forms/stories/CheckboxGroup.stories.tsx, packages/components/forms/stories/FormControl.stories.tsx, packages/components/forms/stories/Formik.stories.tsx, packages/components/forms/stories/RadioGroup.stories.tsx, packages/components/forms/stories/ReactHookForm.stories.tsx, packages/components/forms/stories/ReactHookFormControlledInputs.stories.tsx, packages/components/forms/test/Formik.test.tsx, packages/components/forms/test/ReactHookForm.test.tsx, packages/forma-36-website/src/content/integrations/formik/index.mdx, packages/forma-36-website/src/content/integrations/react-hook-form/index.mdx
Refactor `RadioGroup` and `CheckboxGroup` to be compound components.
Fix `aria-describedby` when helptext is not set, and points to Checkbox helptext, instead of formControl helptext
=> refactor: compound group components

packages/components/menu/src/Menu.tsx, packages/components/popover/src/Popover.tsx, packages/components/popover/src/PopoverContent/PopoverContent.styles.ts
Don't focus menu trigger on blur, and default to browser behaviour
=> fix: do not focus menu trigger on mouse click outside

packages/components/card/src/asset-card/AssetCard.styles.ts, packages/components/card/src/asset-card/AssetCard.tsx, packages/components/card/src/entry-card/EntryCard.tsx
* Consistent `withDragHandle` default value
* Removed custom AssetCard selection styles
=> fix: remove custom asset card selection

packages/forma-36-react-components/src/components/TextInput/TextInput.css
This class was hiding the input every time a user was focusing it
=> fix: remove z-index of focused input

packages/components/card/src/base-card/BaseCard.styles.ts, packages/components/card/stories/Card.stories.tsx
BaseCard had a `overflow: hidden` that was cropping the focus glow of the things inside the card
Before:
After:
It's possible that we introduced this `overflow: hidden` issue in other places, some people spotted the focus glow getting cropped in Compose and Launch
So let's take care when using `overflow: hidden`, I would say that most of the time we do not need it
=> fix: remove overflow hidden from BaseCard

packages/forma-36-website/gatsby-config.js, packages/forma-36-website/src/components/Navigation.js, packages/forma-36-website/src/content/contributing.mdx, packages/forma-36-website/src/pages/index.jsx
It moves the contribution guide from the guidelines section to its own page. And I "dried" some code of the side menu
=> docs: change contribution guide hierarchy

packages/components/card/src/base-card/BaseCard.styles.ts, packages/components/card/stories/Card.stories.tsx
I spotted this bug while writing some docs
The content of the card was not breaking into new lines for some reason so I added `whiteSpace: initial` and it fixed it
=> fix: add whiteSpace breaks in BaseCard content

MIGRATION.md, packages/forma-36-website/src/content/migration-v3-to-v4.mdx
Migration guide for two components: DateTime and RelativeDateTime
=> chore(migration-guide): add migration guide for DateTime and RelativeDateTime

MIGRATION.md, docs/code-style-guide.md, packages/components/autocomplete/stories/Autocomplete.stories.tsx, packages/components/forms/src/form/Form.mdx, packages/components/forms/src/select/Select.mdx, packages/components/icon/Icon.mdx, packages/components/icons/stories/Icons.stories.tsx, packages/core/src/Grid/Grid.mdx, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-note.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-note.output.js, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-tooltip.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-tooltip.output.js
I propose to add this convention to or code style guide
When the value of the prop is a string, pass it directly with double quotes. There is no need to wrap it with curly braces.
```
// bad
<Button variant={'primary'} >Add entry</Button>
// good
<Button variant="primary" >Add entry</Button>
```
This PR also replaces all the places where this convention is not being done now
This should be something that our eslint and/or prettier should warn but I didn't have time to check why it's not throwing warns when linting the code
=> docs: use double quotes when prop is string

packages/forma-36-react-components/src/components/Autocomplete/Autocomplete.tsx, packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx
This PR is a reaction to feedback about Autocomplete component - passing the `dropdownProps` prop causes a type error, because the `children` prop is required, but not passed.
=> fix(autocomplete): fix dropdown props type

packages/forma-36-website/_redirects, scripts/.storybook/docs/General/General.stories.mdx
We need this to redirect people that access v3.f36.contentful.com to the main domain f36.contentful.com
And we need this new subdomain because we will need two version of the website soon (v3 and v4)
=> chore: update redirects with v3 domain

packages/forma-36-codemod/README.md, packages/forma-36-codemod/bin/inquirer-choices.js, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-helptext.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-helptext.output.js, packages/forma-36-codemod/transforms/__tests__/v4.test.js, packages/forma-36-codemod/transforms/v4-helptext.js
This codemod does a simple check if the `HelpText` component is wrapped inside a `<Form>` or `<form>` tag, and replaces by text if it isn't.
=> feat(codemod): add codemod for HelpText outisde forms

packages/components/workbench/src/CompoundWorkbench.tsx, packages/components/workbench/src/index.ts
After feedback about usage of Workbench components, we discovered the components were not exported property and didn't work in apps framework. This PR should fix the issue.
=> fix(workbench): fix exports for regular and compound components of workbench

packages/components/button/Button.mdx, packages/components/button/stories/Button.stories.tsx
This updates the documentation to show the variation of Buttons as links.
=> docs(Button): show example for as property

packages/components/autocomplete/Autocomplete.mdx, packages/components/badge/Badge.mdx, packages/components/button/Button.mdx, packages/components/button/src/ButtonGroup/README.mdx, packages/components/card/src/card/README.mdx, packages/components/datetime/RelativeDateTime.mdx, packages/components/forms/src/checkbox/Checkbox.mdx, packages/components/forms/src/form/Form.mdx, packages/components/forms/src/radio/Radio.mdx, packages/components/forms/src/switch/Switch.mdx, packages/components/forms/src/text-input/TextInput.mdx, packages/components/forms/src/textarea/Textarea.mdx, packages/components/menu/Menu.mdx, packages/components/modal/src/ModalLauncher/ModalLauncher.mdx, packages/components/notification/Notification.mdx, packages/components/popover/Popover.mdx, packages/components/skeleton/src/SkeletonBodyText/README.mdx, packages/components/skeleton/src/SkeletonDisplayText/README.mdx, packages/components/skeleton/src/SkeletonImage/README.mdx, packages/components/typography/src/Text.mdx, packages/core/src/Flex/Flex.mdx, packages/core/src/Stack/Stack.mdx, packages/forma-36-website/src/content/contributing.mdx, packages/forma-36-website/src/content/foundation/color-system/index.mdx, packages/forma-36-website/src/content/getting-started.mdx, packages/forma-36-website/src/content/integrations/react-hook-form/index.mdx
Fixing typos in docs - some stuff that was caught in spellchecker.
=> docs(docs-website): fix typos on documentation website

packages/components/asset/src/Asset.styles.ts
When using AssetCard for SVG files, they are not being displayed. This PR fixes this issue. If you have some feedback or ideas on how to deal with it better, I love to hear it :) 
How to reproduce - in storybook pass a link to an SVG file to AssetCard component
=> fix(asset-card): fix svg assets - unable to display

packages/components/autocomplete/Autocomplete.mdx
Improved wording a bit, but if you see how we can make it a bit more clear, I would love some feedback :)
=> docs(autocomplete): improve wording on autocomplete documentation

packages/components/typography/src/DisplayText.tsx
It was impossible to change the element that DisplayText would be because we were not using the `as` prop and it was being extract from `otherProps` which is passed to the returned Element
=> fix: DisplayText was not using the as prop

packages/forma-36-website/gatsby-config.js, packages/forma-36-website/src/components/MDXPage.js, packages/forma-36-website/src/content/deprecated-components/dropdown/index.mdx, packages/forma-36-website/src/content/deprecated-components/editor-toolbar/index.mdx, packages/forma-36-website/src/content/deprecated-components/empty-state/index.mdx, packages/forma-36-website/src/content/deprecated-components/illustration/index.mdx, packages/forma-36-website/src/content/deprecated-components/tab-focus-trap/index.mdx, packages/forma-36-website/src/content/deprecated-components/typography/index.mdx
Adding docs for components that got removed in v4.
2 more missing:
- Portal
- InViewport
Those will be done in the next PR.
Idea for separate PR: maybe we could add Badge to the navigation items to indicate components that got removed? WDYT?
=> feat: add docs for deprecated components

packages/components/accordion/Accordion.mdx, packages/forma-36-website/gatsby-node.js, packages/forma-36-website/src/components/MDXPage.js, scripts/plop-templates/package/v4ComponentDoc.mdx.hbs, scripts/plopfile.js
The title is a bit misleading, this PR is not updating the current template but it's creating a new template for the new format.
It also creates to new plop actions: "add documentation with new format" and "convert documentation to new format" to help us convert the current pages to the new format
The changes in MDXPage were necessary because we will need to render both formats for a while and I used this PR to fix some spacing inconsistencies in our documentation pages
To know if a page is in the new format or not, MDXPage will check the property `v4Doc` in that mdx's frontmatter
I kept the table of contents the same way it is in the current format because @domarku is still working on this 🙏 
current format:
new format:
=> [BAU-302] docs: update plop template with new format

packages/forma-36-website/src/content/getting-started.mdx
=> fix(forma-36-website): remove extra back-ticks

package.json, yarn.lock
The latest version of storybook breaks our implementation of it for some weird reason, so I reverted it to v6.3.7
Does anyone know how to make dependabot ignore it for now?
=> chore: revert storybook to v6.3.7

packages/components/card/src/asset-card/AssetCard.styles.ts, packages/components/card/src/base-card/BaseCard.styles.ts, packages/components/card/src/card/Card.styles.ts, packages/components/card/src/entry-card/EntryCard.styles.ts, packages/components/card/src/inline-entry-card/InlineEntryCard.styles.ts
So there was an issue with paddings for cards reported. 👀 
In general styling for cards seems complex and for some reason, I have a feeling it might bring more issues in the future, if we would like to extend API for example. Maybe we should have a look at the API of cards and think of a slightly different approach. I don't have anything specific in mind, but maybe it's worth having a deeper look. (Forma 36 4.1 ?)
This PR might fix the issue at the moment, I am not sure if I am not forgetting about some use cases 🤔 Maybe some examples are not added in the overviews for each card. dunno. WDYT?
Also, interesting thing brought by @gui-santos , this issue is right now not visible in storybook for EntryCard, which is very confusing, since we can see it in prod, or when you reproduce the …
=> fix: fix issue with padding for cards

packages/components/card/src/entry-card/EntryCard.mdx, packages/components/card/stories/EntryCard.stories.tsx, packages/forma-36-website/gatsby-config.js
Besides adding a page for EntryCard, this PR creates a `Card Components` section with both Card and EntryCard in it. I suggested to add the documentation for the other "card" components in this place
=> [BAU-345] docs: it creates a page for entry card

packages/components/forms/src/counter/Counter.styles.ts, packages/components/forms/src/counter/Counter.tsx, packages/components/forms/src/text-input/input-group/InputGroup.styles.ts, packages/components/forms/stories/InputGroup.stories.tsx, yarn.lock
1. Make the counter not shrinking, when the input help text is too long.
2. Adjust `InputGroup` styles to accept wrapped buttons. For example, a button wrapped in our `Tooltip`.
=> fix: input related components fixes

packages/components/card/src/asset-card/AssetCard.mdx, packages/forma-36-website/gatsby-config.js
=> [BAU-482] docs: add documentation page for asset card

packages/components/menu/Menu.mdx
There is an issue with the broken website for the menu component caused by the example with the menu open by default. in order to fix it, I would need to add a property to not focus on the first item I guess (something like `itemIsNotFocused`), but I don't think we actually need this property. I am also not sure why we need the property `defaultIsOpen`, it is possible to control by using `isOpen` property I guess.
Anyway, since I was already there, I moved the README to the new format.
=> fix: restructure menu readme

packages/components/autocomplete/src/Autocomplete.tsx
When using screen reader, it should read the items when they are selected
=> [BAU-496] fix: autocomplete screen reader now reads the items

packages/components/datetime/DateTimeUtils.mdx, packages/f36-docs-utils/src/Props/PropsContext.ts, packages/f36-docs-utils/src/Props/index.ts, packages/f36-docs-utils/src/index.ts, packages/website/components/MdxRenderer.tsx, packages/website/package.json, packages/website/pages/[...slug].tsx, packages/website/utils/propsMeta.ts, yarn.lock
1. Logic for providing context with components props types info.
2. Props filtering logic was moved from `PropsContext` to the script where we gather and prepare all those props. To decrease the size of data transferred to the client.
=> feat: nextjs props types context

packages/components/card/src/entry-card/EntryCard.tsx
Truncate long descriptions in EntryCard using CSS.
=> fix: truncate entry card description

packages/components/modal/src/Modal.mdx, packages/components/tabs/src/Tabs.styles.ts, packages/components/tooltip/stories/Tooltip.stories.tsx
- add 'shouldCloseOnOverlayClick' and 'shouldCloseOnEscapePress' props to Modal examples
- Add visual focused state for Tab (focus state was missing on the active state)
=> fix(modal): add props to modal examples and add focus state for tabs

packages/components/autocomplete/src/Autocomplete.tsx
We need an ability to pass truthy `usePortal` value in Autocomplete component as discovered while integrating v4 in Launch application.
=> fix: allow to pass usePortal to Autocomplete

packages/components/asset/src/Asset.styles.ts, packages/components/card/stories/AssetCard.stories.tsx
This fix should prevent the image on Asset preview from being distorted.
=> Fix asset image fit

package.json, packages/components/card/stories/EntryCard.stories.tsx, packages/components/drag-handle/src/DragHandle.tsx, yarn.lock
Temporary fix to the issue that we face in the field editors.
The library used by field editors (react-sortable-hoc) is canceling events for buttons for some reason (https://github.com/clauderic/react-sortable-hoc/blob/d94ba3cc67cfc7d6d460b585e7723bdb50015e53/src/SortableContainer/defaultShouldCancelStart.js).
We should change the implementation on the field editors at some point. We will have a look at it while working on the keyboard nav for dragHandle (inspiration from user interface, where it's already done)
I added the example in the storybook,but skipped the website, we don't want to encourage anyone to use react-sortable-hoc, but maybe it's still worth keeping the example in the storybook?
=> fix: fix dragHandle issue

packages/website/components/Layout.tsx, packages/website/components/Sidebar.tsx
I have OCD and the double scrollbar of the website was annoying me so I created this small fix, it removes unnecessary styles and html that was creating the double bar
before:
after:
=> fix: double scroll in the sidemenu

packages/components/card/src/base-card/BaseCard.tsx
When hovering over the asset card, if the title is cut by ellipsis it's hard to know the full title of the assets because hovering over the title doesn't show the full title.
This PR adds the "title" attribute to "BaseCard" component.
Before:
Now:
=> Fix/add title attribute to base card [ZEND-1740]

packages/components/button/examples/ButtonGroupCollapsedExample.tsx, packages/components/button/examples/ButtonGroupMergedExample.tsx, packages/components/button/examples/ButtonGroupSpacedExample.tsx, packages/components/button/src/ButtonGroup/ButtonGroup.styles.ts, packages/components/button/src/ButtonGroup/ButtonGroup.tsx, packages/components/button/src/ButtonGroup/README.mdx, packages/components/button/src/ButtonGroup/types.ts, packages/components/button/stories/ButtonGroup.stories.tsx, packages/components/modal/src/ModalControls/ModalControls.tsx
- Better documentation for the `ButtonGroup` component with more real-world examples.
- Fixes wrong `spaced` implementation (there was 2 * spacing space between items) by using `Stack` component in the implementation.
- Fixes broken `withDivider` implementation
=> feat: better ButtonGroup docs and fixed spaced implementation

packages/components/modal/src/Modal.styles.ts
For some reason, `react-modal` and `emotion` are not playing nice and they invert the order a CSS class is defined when a user opens a ModelConfirm inside of another Modal using ModalLauncher
yes, I know...
Because this is kinda urgent for a customer, we had to add `!important` to the "afterOpen" class to make sure that the modal shows up after the opening transition
=> [ZEND-1727] fix: modal confirm does not show if opened from another modal

packages/website/components/DocSearch.tsx, packages/website/package.json, packages/website/pages/_app.tsx, yarn.lock
Install Algolia DocSearch from NPM instead of CDN load.
=> fix: use docsearch from npm

packages/website/components/Layout.tsx, packages/website/components/PageContent.tsx
- Makes content of the page grow to the maximum always so the footer is sticky to the bottom
- Removes sidebar's `overflow: hidden`
=> fix: sidebar cropping docsearch and footer not sticky to the bottom

MIGRATION.md, packages/components/typography/examples/DisplayTextExample.tsx, packages/components/typography/examples/DisplayTextMarginsExample.tsx, packages/components/typography/src/DisplayText/DisplayText.tsx, packages/components/typography/stories/DisplayText.stories.tsx, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-typography.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-typography.output.js
Removes `DisplayText` size `huge`
=> fix: removes DisplayText huge size

packages/website/components/LiveEditor/ComponentSource.tsx
- remove playground btn from old format code blocks
- minor styles changes for floating controls
=> docs: remove playground btn from old format code blocks

packages/components/collapse/src/Collapse.styles.ts, packages/components/collapse/src/Collapse.tsx, packages/components/collapse/stories/Collapse.stories.tsx
1. In order to extend my Collapse element with properties like ID to link it via ARIA to my DragHandle button, we should allow passing through native properties to the DOM node.
2. When the element is collapsed (and the transition is done), it adds `display: none` to the region. Thereby, the elements within are not reachable with `Tab` anymore. The style is removed when the expanding transition starts.
- feat: pass native props like ID to Collapse node
- fix: hide collapsed content with display none
=> fix(Collapse): enrich props type and add display none for collapsed state

packages/website/mdx-components/ColorSwatchGroup.tsx
=> fix: color demo spacing

packages/website/components/Sidebar.tsx, packages/website/components/Topbar.tsx, packages/website/pages/index.tsx
* We're disabling the search for the time being, it has to be reindexed first.
* We want to show the current version number at the top bar
=> docs: disable search and show version number

packages/components/forms/src/BaseCheckbox/BaseCheckbox.tsx
Small fix so Checkbox, Radio and Switch renders the helpText bellow the input instead of on the side:
**Before**
**After**
=> fix(basecheckbox): update flex direction so helpText appears below input

packages/components/forms/examples/FormControlCharacterCountExample.tsx, packages/components/forms/src/Counter/Counter.styles.ts
=> fix: counter alignment

packages/components/button/src/ButtonGroup/ButtonGroup.styles.ts, packages/components/button/src/ToggleButton/ToggleButton.styles.ts
Fix issue with right border on grouped toggle button when hovering.
You can check it on the [preview](https://forma-36-git-fix-toggle-button-hover-border-contentful-apps.vercel.app/components/toggle-button#grouped) deploy, need to change the `useState(true)` to `useState(false)` on the example.
Fixes #1757
=> fix(togglebutton): fix border when hovering grouped toggle button

packages/website/components/Footer.tsx, packages/website/components/Layout.tsx, packages/website/components/Sidebar.tsx, packages/website/components/SidebarLink.tsx, packages/website/components/SidebarSection.tsx, packages/website/components/Topbar.tsx
First step:
- disable search
- align typography in the side nav to the design
- align columns for sidebar and topbar
In the next PR
- alphabetical order in the sidebar navigation
=> fix: disable search and align typography in the sidebar

packages/website/components/Layout.tsx, packages/website/components/LayoutFullSize.tsx, packages/website/components/SidebarLink.tsx, packages/website/components/TableOfContent.tsx, packages/website/components/Topbar.tsx
This is just a proposal to start a discussion on how we can align these states until @domarku designs the final version of them
I basically tried to align all the navigation links to follow our TextLink styles:
- hover: the link gets underlined
- active: the link gets bold and underline
=> [Proposal] feat: navigation links states

packages/website/components/DocSearch.tsx, packages/website/components/Sidebar.tsx, packages/website/components/SidebarLink.tsx, packages/website/components/SidebarSection.tsx
This PR:
- removes unnecessary list that was wrapping all other list of links in the sidebar
- aligns links in the sidebar to Forma 36's logo like in the designs by @domarku 
- removes padding around DocSearch that was increasing the size of the topbar
=> fix: align sidebar links to forma 36's logo

packages/components/button/src/Button/README.mdx, packages/components/button/src/ButtonGroup/README.mdx, packages/components/button/src/IconButton/README.mdx, packages/components/button/src/ToggleButton/README.mdx, packages/components/card/src/AssetCard/README.mdx, packages/components/card/src/EntryCard/README.mdx, packages/components/card/src/InlineEntryCard/README.mdx, packages/components/collapse/README.mdx, packages/components/copybutton/README.mdx, packages/components/datetime/src/DateTime/README.mdx, packages/components/drag-handle/README.mdx, packages/components/forms/src/Radio/README.mdx, packages/components/forms/src/TextInput/README.mdx, packages/components/forms/src/Textarea/README.mdx, packages/components/menu/README.mdx, packages/components/modal/src/ModalConfirm/README.mdx, packages/components/modal/src/README.mdx, packages/components/notification/README.mdx, packages/components/text-link/README.mdx, packages/components/typography/src/DisplayText/README.mdx, packages/components/typography/src/Heading/README.mdx, packages/components/typography/src/Paragraph/README.mdx, packages/components/typography/src/SectionHeading/README.mdx, packages/components/typography/src/Subheading/README.mdx, packages/components/typography/src/Text/README.mdx, packages/website/components/CustomHeading2.tsx, packages/website/components/MdxRenderer.tsx, packages/website/pages/[...slug].tsx, packages/website/types.ts, packages/website/utils/frontMatterContext.ts
- add a storybook link for Props Table heading
- return back all the components docs storybook links in front matter
=> docs: add storybook link

packages/components/button/src/Button/Button.styles.ts
Explicitly set a `color` on buttons. We need to do this for buttons rendered `as="a"`, because legacy styles are overriding `a:hover` 😕
=> fix(button): set color explicitly for hover state

packages/components/forms/src/BaseInput/types.ts
We were overwriting the default values for the `type` property of an input and because of that TS was complaining when you did something like `<TextInput type="date" />`
This will close https://github.com/contentful/forma-36/issues/1769
=> fix: allows all native HTML values to type prop of an input

packages/components/autocomplete/README.mdx, packages/components/autocomplete/examples/AutocompleteBasicUsageExample.tsx, packages/components/autocomplete/examples/AutocompleteFetchingAsyncDataExample.tsx, packages/components/autocomplete/examples/AutocompleteHighlightingExample.tsx, packages/components/autocomplete/examples/AutocompleteMultiSelectionExample.tsx, packages/components/autocomplete/examples/AutocompleteWithErrorValidationExample.tsx, packages/components/autocomplete/examples/AutocompleteWithGroupedItems.tsx, packages/components/autocomplete/examples/AutocompleteWithObjectsExample.tsx
- move examples to their own tsx files
- update examples to use "real" cases
=> docs: move autocomplete examples to tsx files

packages/components/note/src/Note.tsx
In the note component I want to be able to set other components next to the title. For example the badge component.
This required a simple typescript change.
=> feat: allow react nodes in title of note

packages/components/skeleton/examples/SkeletonContainerBasicExample.tsx, packages/components/skeleton/examples/SkeletonContainerDifferentSpeedExample.tsx, packages/components/skeleton/src/SkeletonContainer/README.mdx, scripts/plop-templates/package/v4ComponentDoc.mdx.hbs, yarn.lock
It updates `SkeletonContainer` docs
I ran `yarn install` and it updated yarn.lock
which means we forgot to commit yarn.lock changes after installing `react-icons`
Let's not forget to push changes to the lock file after installing dependencies in the future 🙏
=> docs: move skeleton container docs to new format

packages/website/components/Sidebar.tsx, packages/website/components/Topbar/Topbar.tsx, packages/website/hooks/useCurrentLocation.ts
Currently, if you go to a deprecated component documentation, the website renders the Introduction's sidebar and it marks "Introduction" as active in the topbar
This happens because the slug of a deprecated component is "/deprecated-components/dropdown"
=> fix: keep topbar and sidebar navigation for deprecated, utils and integrations

packages/components/collapse/src/Collapse.tsx
My former PR introduced a bug where the expanded region was not clickable after expanding for the first time. I'll now remove the `pointer-events` property properly.
=> fix(Collapse): make it clickable after first expansion

packages/website/components/DocSearch.tsx
I think that's the problem, but we can only test in production since we are already calling that function in non-production environments
=> fix: call window.location.assign in prod

packages/components/skeleton/examples/SkeletonDisplayTextBasicExample.tsx, packages/components/skeleton/examples/SkeletonDisplayTextCompositionExample.tsx, packages/components/skeleton/examples/SkeletonImageBasicExample.tsx, packages/components/skeleton/examples/SkeletonImageDimensionsExample.tsx, packages/components/skeleton/examples/SkeletonImageRoundExample.tsx, packages/components/skeleton/examples/SkeletonRowBasicExample.tsx, packages/components/skeleton/src/SkeletonBodyText/README.mdx, packages/components/skeleton/src/SkeletonDisplayText/README.mdx, packages/components/skeleton/src/SkeletonImage/README.mdx, packages/components/skeleton/src/SkeletonRow/README.mdx, scripts/plop-templates/package/v4ComponentDoc.mdx.hbs
This moves all the remaining skeleton components docs to the new format
=> docs: move skeleton components docs to new format

packages/components/popover/src/PopoverContent/PopoverContent.styles.ts
- reintroduce `Popover` content focus styles for Safari browser
=> fix: focus styles for Popover content in safari

packages/components/button/src/ButtonGroup/ButtonGroup.tsx
ButtonGroup currently doesn't pass given `className` to the group when `variant="spaced"`
=> fix(button-group): pass className prop to spaced group

packages/components/collapse/README.mdx, packages/website/components/Sidebar.tsx, packages/website/utils/sidebarLinks.json
=> fix: change collapse url and create animation components section

MIGRATION.md
The migrations docs seem to have the wrong package names listed for uninstallation.
=> docs: fix old package names in migration

packages/components/forms/examples/FormControlCharacterCountExample.tsx, packages/components/forms/src/TextInput/TextInput.tsx, packages/components/forms/src/Textarea/Textarea.tsx, packages/components/forms/stories/FormControl.stories.tsx
Make Counter work with initial values, if either `value` or `defaultValue` prop is passed to the inputs.
closes #1826
=> fix(counter): make counter work for initial values

packages/core/src/Primitive/Primitive.tsx
Disable `ExpandProps` on types, to avoid build errors while we investigate a proper solution for:
https://github.com/contentful/forma-36/issues/1834
=> fix(core): disable ExpandProps while we investigate a bug caused by it

packages/core/src/GlobalStyles/GlobalStyles.tsx
- Remove min-height from GlobalStyles. Because it breaks the auto resizer of our App SDK in the iframes.
=> fix: remove min-height from GlobalStyles

packages/components/button/src/Button/Button.styles.ts
Sets `color: ... !important`on buttons.
Yes, this is bad form, but currently buttons that are rendered `as="a"` are rendered with the wrong colours because of `a:link` and `a:hover` styling in our legacy CSS. This is a suggested temporary fix until we can get rid of legacy styles.
See also #1848 for a similar selector issue albeit with a different reason.
=> fix(button): enforce color properties with !important

packages/components/autocomplete/src/Autocomplete.tsx, packages/components/menu/src/Menu.test.tsx, packages/components/popover/src/Popover.test.tsx, packages/components/popover/src/Popover.tsx, packages/components/popover/src/PopoverContent/PopoverContent.tsx, packages/components/popover/src/PopoverContext.ts
- Rollback the logic when Popover is rendered in the DOM only when it's open and make it a default behavior. 
But with the option to turn it off.  Because there is a problem with our `Autocomplete` and Downshift library if the popover is not initially rendered. See the error below and more details in the [related PR](https://github.com/contentful/forma-36/pull/1355)
=> feat: by default render Popover only when it's open

packages/website/components/GlobalStyles.tsx, packages/website/components/LiveEditor/ComponentSource.tsx, packages/website/components/LiveEditor/StaticSource.tsx, packages/website/package.json, yarn.lock
In the next PR we will provide a custom template for examples, it will be a bit darker.
=> fix: improved collapsable examples

packages/components/menu/src/MenuItem/MenuItem.styles.ts
- Make Menu item `hover` state styles different from `focus` state.
@domarku pls take a look 🖼
=> fix: menu item focus styles

packages/website/content/migration-v3-to-v4.mdx
We are using the wrong space character between "issue" and "and":
=> docs: use correct space character

packages/components/card/examples/InlineEntryCard/BasicInlineEntryCardExample.tsx, packages/components/card/examples/InlineEntryCard/InlineEntryCardInTextExample.tsx, packages/components/card/examples/InlineEntryCard/InlineEntryCardWithActionsExample.tsx, packages/components/card/package.json, packages/components/card/src/EntryCard/EntryCard.types.ts, packages/components/card/src/InlineEntryCard/InlineEntryCard.tsx, packages/components/card/src/InlineEntryCard/README.mdx, packages/components/card/stories/InlineEntryCard.stories.tsx
We've made a mistake in the past. I think we assumed the `InlineEntryCard` only needed `title`, but because of that we created a bug in Rich Text editor where the title is being rendered as the content of the card:
The title was supposed to be a prop to just render the native HTML tooltip, so now I updated it to show our Tooltip (see first image)
This PR fixes the bug and updates the documentation
=> fix: allow children to be passed to InlineEntryCard

packages/components/badge/src/Badge/Badge.styles.ts, packages/components/badge/stories/Badge.stories.tsx
We have an example where there is not much space for the badge. Still, the text in the badge should never break the word for a new line.
=> fix(Badge): disable newlines

packages/components/button/src/ToggleButton/ToggleButton.test.tsx, packages/components/button/src/ToggleButton/ToggleButton.tsx, packages/components/button/stories/ToggleButton.stories.tsx
For some reason we implemented ToggleButton in a way that the component is managing its state of being active or not
This is a problem for a case where I need to manage this state in a parent or something. For example, when I have a group of toggle buttons and I want only one button active each time
This PR removes the state from the component (that should have not been there in the first place)
=> fix: remove state from ToggleButton

packages/components/card/src/BaseCard/DefaultCardHeader.tsx, packages/components/card/src/EntryCard/EntryCard.styles.ts, packages/components/card/src/EntryCard/EntryCard.tsx, packages/components/card/stories/EntryCard.stories.tsx, packages/components/typography/src/DisplayText/DisplayText.tsx, packages/components/typography/src/Heading/Heading.tsx, packages/components/typography/src/Paragraph/Paragraph.tsx, packages/components/typography/src/SectionHeading/SectionHeading.tsx, packages/components/typography/src/Subheading/Subheading.tsx, packages/components/typography/src/Text/Text.tsx
Introducing new prop to typography components to manage cases like this one:
WDYT?
=> feat: new property to typography components

packages/components/badge/src/Badge/Badge.styles.ts
=> fix: fix badge alignment

packages/forma-36-codemod/README.md, packages/forma-36-codemod/bin/cli.js, packages/forma-36-codemod/bin/inquirer-choices.js, packages/forma-36-codemod/transforms/v4-checkbox.js, packages/forma-36-codemod/transforms/v4-radio.js, packages/forma-36-codemod/transforms/v4-select.js, packages/forma-36-codemod/transforms/v4-text-field.js, packages/forma-36-codemod/utils/deleteProperty.js, packages/forma-36-codemod/utils/getChildren.js, packages/forma-36-codemod/utils/index.js
Fix issue when trying to get value from prop and turning into children.
This didn't work because if the prop  was set as `labelText={foo.bar}`, the `jsxExpressionContainer` would expect a `ExpressionMember` and not an `Identifier`.
```js
children: [
labelText.value.type === 'StringLiteral' ||
labelText.value.type === 'Literal'
? j.jsxText(labelText.value.value)
: j.jsxExpressionContainer(
j.identifier(labelText.value.expression.name),
),
],
```
With the `getChildren` function, if the value of the prop is a `JSXExpressionContainer` we just pass that value down to the children, and if it's a `Literal` we wrap with `JSXText`.
----
Also made the list of transformers alphabetically ordered and added missing transformers to the Readme
=> feat: improve codemod

packages/components/note/src/Note.styles.tsx, packages/components/note/src/Note.tsx
it fixes this case:
and this case:
This is what I achieved:
=> fix: close button alignment in Note component

.changeset/two-squids-fly.md, packages/components/menu/src/MenuItem/MenuItem.styles.ts
Makes MenuItem focus styling keyboard-only.
=> fix(menu-item): keyboard-only focus style

packages/website/components/LiveEditor/ComponentSource.tsx
Makes the button an anchor tag so it's possible to open the playground in a new tab
=> fix: playground button opens a new tab

packages/core/src/Grid/examples/BasicGridExample.tsx, packages/core/src/Grid/examples/ContentAlignmentGridExample.tsx, packages/core/src/Grid/examples/FrGridExample.tsx, packages/core/src/Grid/examples/RepeatNotationGridExample.tsx, packages/core/src/Grid/examples/SpanKeywordGridExample.tsx, packages/website/components/LiveEditor/ComponentSource.tsx
The grid examples were not showing up because they didn't have a `width`
=> fix: grid examples

packages/components/card/src/EntryCard/EntryCard.tsx
Fixing the issue with card description
Fix for https://contentful.atlassian.net/browse/ZEND-1898
=> fix: fix entry card description

packages/components/forms/src/BaseInput/BaseInput.styles.ts
Remove zIndex logic when input `isInvalid` or `isDisabled` to avoid tooltip being overlapped.
=> refactor(baseinput): Remove zIndex logic when input is disabled or invalid

packages/core/src/GlobalStyles/GlobalStyles.tsx
Removes `min-height` on `body` in our CSS reset. Necessary for app SDK resizing to work.
=> fix(global-styles): remove min-height on body

packages/components/workbench/src/Workbench.tsx
Follow-up to #1831.
Workbench is rendering null children which throws an error.
=> fix(workbench): don't render null children

.circleci/config.yml, CHANGELOG.md, package.json, packages/website/content/changelog.mdx
- Fix order when prettier is called on CI.
- Fix prettier issues on generated changelog.
=> ci(circleci): prettier should be executed after files are added

README.md, packages/website/content/contributing.mdx
Updating `Commits & Release` section on Readme and `Contributing Guide` as we now use changeset and only release new versions of packages that contain a changeset with the new version and notes
=> docs: add changesets usage to contributing guide

CHANGELOG.md, packages/website/components/Footer.tsx, packages/website/content/changelog.mdx, packages/website/utils/sidebarLinks.json
Add link on the Footer of documentation website to the `What's new` page.
The table of content is generated automatically, if will appear when we have a new entry on the file.
=> docs: add link to changelog page and rename changelog to what's new

packages/components/forms/src/BaseCheckbox/types.ts
This PR should allow passing HTML attributes to the checkbox input through `inputProps`. This is necessary to be able to set a `data-test-id`.
We could also use common props to allow setting `testId` prop, but I think this is overkill since we're dealing with the raw HTML element anyway.
=> fix(checkbox): allow passing HTML attributes to input

packages/components/autocomplete/src/Autocomplete.tsx
See [this comment](https://github.com/downshift-js/downshift/issues/1108#issuecomment-842407759). Downshift will always move the text cursor to the end of the input. Following the linked comment, we handle the change manually and thereby avoid the rerender (and cursor position change).
**Before:**
https://user-images.githubusercontent.com/9327071/159534013-6644ef0a-00a8-4ffd-8571-a34d2400a96d.mov
**After:**
https://user-images.githubusercontent.com/9327071/159534174-10d01c14-12bc-4ff5-a246-1ec15742f047.mov
I wrote a test but it always worked. The jumping cursor bug doesn't appear in the jsdom context.
=> fix(Autocomplete): dont put text cursor to the end on every change event

.changeset/wet-cats-visit.md, packages/components/forms/src/BaseCheckbox/types.ts
I can't get the types to allow `data-test-id` so this PR sets it explicitly.
=> fix(base-checkbox): explicitly allow data-test-id on HTML element

packages/components/accordion/examples/ControlledAccordion.tsx
Remove types from ControlledAccordion example. I wish we could add types but they are breaking the example 😅
=> docs(controlled-accordion): remove types

.changeset/chatty-tips-run.md, packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.tsx
The `WorkbenchHeader` doesn't require the `icon` prop, but the current implementation tries to render a JSX element from the prop even when it's undefined. This PR fixes it by explicitly checking for `undefined` first.
=> fix(workbench-header): support undefined icon prop

.prettierignore
Excludes generated changeset files from prettier so that they stop failing the CI pipeline
=> build: ignore generated changesets from prettier

.changeset/sharp-phones-check.md, packages/components/utils/package.json, packages/forma-36-react-components/package.json
`utils` and `react-components` did not include React 18 in their peer deps version range
Now, all peer dependencies are now consistent: `react: >= 16.8.0`
=> feat: add React 18 as peer dependencies

.changeset/breezy-buttons-grin.md, packages/components/asset/src/AssetIcon/AssetIcon.tsx, packages/components/typography/src/Typography.tsx
Same as https://github.com/contentful/forma-36/pull/2008 just for `AssetIcon` and `Typography`
Previously only types with `declare export namespace` were fixed. In these cases there is a comment between `declare` and  `export namespace`.
=> fix: broken types

packages/components/card/examples/Card/WithCustomDragHandle.tsx, packages/components/card/src/BaseCard/BaseCard.types.ts, packages/components/card/src/Card/Card.tsx, packages/components/card/src/Card/README.mdx, packages/components/card/src/InlineEntryCard/InlineEntryCard.tsx, packages/components/card/stories/Card.stories.tsx, packages/components/drag-handle/src/DragHandle.styles.ts, packages/components/drag-handle/src/DragHandle.tsx, packages/components/text-link/src/TextLink.tsx
Reinstates the `withDragHandle` boolean on `Card` component. This prop is required to be able to use `dragHandleRender`.
=> fix(card): don't omit withDragHandle type

packages/components/autocomplete/src/Autocomplete.styles.ts, packages/components/autocomplete/src/Autocomplete.tsx, packages/components/autocomplete/stories/Autocomplete.stories.tsx
This fixes the styling of the autocomplete input. 
- input placeholder and typed in text was flowing underneath the icon button
- the icon button was having too much spacing around and so it did not look as integrated part of the autocomplete input.
**Before**
Too much space around the button makes it look hovering weird and distached from the input field, instead of beeing part of it
Long input texts would overflow underneath the X button and look broken
long input texts would just dissapear undernath the button and be cut off.
**After**
Button is now tucked fitting into the input field with no visual space
Long selections and palceholders get overflown via ellipsis
Long input texts stop before the button
=> style: fix autocomplete input with button styling [HOMER-856]

packages/components/button/src/Button/Button.tsx, packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.styles.ts, packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.tsx
Align Workbench header icons properly
**Before**
**After**
=> fix: workbench header icon alignments

.changeset/plenty-moles-watch.md, .changeset/six-cameras-bow.md, packages/components/button/src/ButtonGroup/ButtonGroup.styles.ts, packages/components/forms/src/TextInput/input-group/InputGroup.styles.ts
- Add stacking context for the ButtonGroup and InputGroup components. It should fix the bug when the group elements are stacking not within the Group’s context, but within the context of the parent element (because the ButtonGroup/InputGroup itself didn't create a stacking context)
=> fix: add local zIndex scope for buttonGroup

.changeset/sharp-meals-brush.md, packages/forma-36-react-components/package.json
Fixes import issues in non-module environments by removing the `exports` key from `package.json`. This key currently makes build tools ignore all builds other than the `modern` one.
We're not using this key correctly so I've opted for removing it, but we can always add it back with a more robust configuration similar to this one, which I found in `acorn`:
```json
"exports": {
".": [
{
"import": "./dist/acorn.mjs",
"require": "./dist/acorn.js",
"default": "./dist/acorn.js"
},
"./dist/acorn.js"
],
"./package.json": "./package.json"
},
```
=> fix: remove exports key from package.json

.changeset/mean-stingrays-add.md, packages/components/popover/package.json, packages/components/popover/src/Popover.tsx, packages/components/tooltip/package.json, packages/components/tooltip/src/Tooltip.tsx, yarn.lock
* Bump version of popper to latest
* Update from `forceUpdate` to `update` to avoid flushSync errors
=> chore: bump popper version

packages/components/datepicker/stories/Calendar.stories.tsx, packages/components/datepicker/stories/Datepicker.stories.tsx
- Now Datepicker/Calendar Storybook stories shouldn't trigger a change on Chromatic every time they run.
=> chore: provide defaultMonth prop to Calendar stories [BAU-821]

packages/forma-36-react-components/src/components/Dropdown/Dropdown.tsx, packages/forma-36-react-components/src/components/Tooltip/Tooltip.tsx
Fix react error in `DropDown` and `ToolTip` component where we were still using `forceUpdate` from `popperjs`
=> fix: flash sync error in DropDown and Tooltip

packages/components/menu/README.mdx
`Menu` doesn't provide a prop for disabling `autoFocus`. It's made in such a way for a11y purposes. 
Only `Popover` component has it.
=> docs: fix Menu a11y section

packages/website/components/Playground/SandpackRenderer.tsx
=> fix: playground datepicker dependency version

.changeset/fifty-apples-suffer.md, packages/components/autocomplete/README.mdx, packages/components/autocomplete/examples/CustomIcon.tsx, packages/components/autocomplete/src/Autocomplete.tsx
Allow passing custom icons to Autocomplete component
=> feat: allow passing custom icons to autocomplete

.changeset/pre.json
Revert back to normal releases and move beta after merging to a new `beta` branch
=> chore: remove beta flag

packages/components/datetime/src/index.ts
We use `RelativeDateTime` component in our app, but for testing `formatRelativeDateTime` is useful, while not exported publicly
=> chore: export formatRelativeDateTime function from datetime package []

packages/components/datepicker/package.json, packages/website/components/Playground/SandpackRenderer.tsx, packages/website/package.json
bump datepicker version to `4.1.0-beta.3`
=> chore: bump datepicker version to `4.1.0-beta.3`

.changeset/shaggy-fireants-deliver.md, packages/components/notification/examples/NotificationIntentsExample.tsx, packages/components/notification/src/Notification.tsx, packages/components/notification/src/NotificationItem/NotificationItem.styles.ts, packages/components/notification/src/NotificationItem/NotificationItem.tsx, packages/components/notification/src/types.ts, packages/components/notification/stories/Notification.stories.tsx
We are looking to push a notification to users that simply elicits general information. The current Notification component only supports a success, warning, and error state at the moment.
This PR looks to resolve the issue brought up in proposal #2140
=> feat: Info variant for Notification

.github/workflows/stale.yml
The stale action hit the default operations-per-run before going through all issues and PRs, this increase is to be sure that it runs in all of them
=> chore: update operations-per-run on stale action

.changeset/tasty-cougars-sin.md, packages/components/icon/examples/IconSizesExample.tsx, packages/components/icon/src/Icon.tsx, packages/components/icon/stories/Icon.stories.tsx
In order to be able to provide xlarge size icon for ProductIcons,I would like to extend the Icon sizes, since we use it under the hood in experience-components package. WDYT?
=> feat: xlarge size for Icon

package.json, packages/components/accordion/src/Accordion.test.tsx, packages/components/modal/src/ModalConfirm/ModalConfirm.tsx, packages/components/tooltip/src/Tooltip.test.tsx, yarn.lock
Next.js expects TypeScript version 4.3.2 or above. This upgrade also gives us some cool features like `type` imports in named imports, so that we don't have to split component and type imports.
=> chore(deps): update typescript

.github/workflows/remove-stale.yml
Add action to remove stale label from PRs/issues when a new comment is created on it.
=> chore: add action to remove stale label when there is a new comment

packages/components/datepicker/README.mdx, packages/components/datepicker/src/Calendar/README.mdx, packages/website/components/PageContent/PageContentHeader.tsx
Add installation instructions to docs for beta packages:
- https://forma-36-git-docs-beta-package-install.colorfuldemo.com/components/calendar
- https://forma-36-git-docs-beta-package-install.colorfuldemo.com/components/datepicker
=> docs: add beta installation instructions

.changeset/wild-shrimps-confess.md, packages/components/modal/src/Modal.styles.ts, packages/components/modal/src/Modal.tsx
Add a way to style the Modal backdrop
This PR looks to resolve the issue brought up in proposal #2166
=> feat(modal): add 'overlayProps' to Modal component

packages/components/forms/src/BaseCheckbox/GhostCheckbox.styles.ts
As soon as the width of the component is limited and the description includes a line wrap, the switch input will be cut off.
Using the flex-shrink property, we tell the flexbox never to shrink this part but only the text block.
=> fix: avoid shrinking the switch input to not cut if off [HOMER-1216]

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/component-feedback.md, .github/ISSUE_TEMPLATE/proposal.md
Get rid of assignees from issue templates, I think it's clear we're not keeping them up to date and maybe we don't need them? 🙂
=> build: remove assignees from issue templates

package.json, scripts/.storybook/main.js, yarn.lock
I think this is necessary for #2187 because Storybook's Webpack v4 loader is causing issues.
- Upgrades to Webpack v5
- Upgrades Storybook to latest
Adds an explicit `webpack` dependency as well as a Yarn resolution for Storybook's use of Webpack. It looks like Webpack v5 will be the default in Storybook v7 (currently in alpha) so once we upgrade to that we can get probably get rid of these again.
I don't think there are any risks, we're not using Webpack as a direct dependency.
=> chore(deps): Webpack v5 in Storybook

.github/workflows/remove-stale.yml
Make the remove-stale action work on PRs and only run when the stale label is present
=> fix: make remove-stale run on PRs too

packages/components/typography/src/Text/Text.tsx
Fix text truncation styles
**Before**
**After**
=> fix(Text): truncated styles

packages/components/datepicker/package.json, packages/components/datepicker/src/Calendar/Calendar.styles.ts, yarn.lock
- update react-day-picker to fix some minor issues (for example before it was possible to focus disabled days with keyboard navigation )
- pin `react-day-picker` version to prevent breaking changes in styles
=> feat: update react-day-picker to fix some minor issues, pin the version

.changeset/few-schools-develop.md, tsup.config.ts
Target ES6 instead of ES2020 because react-scripts doesn't support nullish coalescing operator, even though all our targeted platforms do.
=> feat: build to es6

.changeset/config.json, RELEASES.md, package.json, scripts/prerelease.mjs, yarn.lock
Add script to make the handling of prereleases packages easier.
The script will handle:
* bumping the version according to the selected prerelease (alpha, beta)
* adding to the ignore field on changeset configuration
* publish to npm
PS: kept with the `--dry-run` flag for now for testing, will remove it before merging into `main`
=> chore: add script to make versioning and publishing prereleases easier

scripts/prerelease.mjs
Remove `--dry-run` flag from prerelease script
=> refactor: remove --dry-run flag from prerelease publishing

packages/components/datepicker/src/Calendar/README.mdx
Removes the beta installation instructions
=> docs(Calendar): remove beta package install instructions

.changeset/honest-teachers-smile.md, packages/core/src/GlobalStyles/GlobalStyles.tsx
Safari has a default margin set to `2` on buttons, we reset all buttons to have no margin, to fix issues with spacing
**Before:**
**After:**
=> fix: add button margin reset on GlobalStyles

packages/components/notification/examples/NotificationIntentsExample.tsx, packages/components/notification/src/NotificationItem/NotificationItem.styles.ts
- Long words in notifications bugs the component. hence, we introduce this change to break long words into new lines
- Fix Notifications triggers alignment in docs
**Before**
**After**
=> fix(Notification): break long words into new lines

.changeset/pretty-hotels-roll.md, packages/components/workbench/src/Workbench.styles.ts
Fix for the style bug in the Entry Editor when the page body is scrollable, which means that if users use that scroll, the page will look like this
- Too much space in the bottom
- Entry title and Content type disappear
You want to ask why `position: relative` because that's how it works in the prev Workbench version.
=> fix: workbench styles [BAU-944]

.changeset/config.json
- remove f36-workbench from changeset fixed arrays, since it's not part of `f36-components`
=> chore: remove f36-workbench from changeset fixed

packages/forma-36-codemod/transforms/__testfixtures__/v4/v4-select.output.js, packages/forma-36-codemod/transforms/v4-select.js
Select codemod was passing the name prop to the FormControl instead of to the Select.
=> fix(codemod): pass the name prop to the Select not FormControl

.changeset/smooth-students-watch.md, packages/components/forms/src/BaseInput/BaseInput.styles.ts, packages/components/forms/src/TextInput/input-group/InputGroup.styles.ts, packages/components/forms/stories/InputGroup.stories.tsx
Fixes handling of zIndex on TextInput.Group, by giving `invalid` and `disabled` inputs a higher value, but if an element inside the group is `hovered` or `focused`, it gets an higher z-index in case it has a tooltip, it's not overlapped by the input itself (refer to #1857)
closes #1978 
> ~~**Known issues**~~
> ~~since we are changing the z-index in multiple places, some overlaps may happen:~~
> ~~If the input is focused~~
> ~~<img width="355" alt="image" src="https://user-images.githubusercontent.com/1071799/191037429-75e3cfb7-3aee-4371-b197-69167ee2ee62.png">~~
> ~~And then the button with a tooltip is hovered, it will appear like this~~
> ~~<img width="355" alt="image" src="https://user-images.githubusercontent.com/1071799/191037533-9e71bc39-a265-4194-90fd-cb2d2684ceac.png">~~
>
> …
=> fix: handling of zIndex on TextInput.Group

packages/components/autocomplete/src/Autocomplete.styles.ts, packages/components/autocomplete/src/Autocomplete.test.tsx, packages/components/autocomplete/src/Autocomplete.tsx
Add prop to force showing the list when focused, even if empty and no search value is set.
Instead of not rendering, we render a empty hidden div to pass the ref to it to avoid downshift error messages, for more context see [here](https://github.com/downshift-js/downshift/issues/1167#issuecomment-1088022842)
=> refactor(autocomplete): add prop to force showing the empty list when focused

package.json, yarn.lock
Husky v4 is unmaintained. We can either upgrade to Husky v8, which honestly seems pretty cool but [has dropped support for autoinstalling](https://blog.typicode.com/husky-git-hooks-autoinstall/), or we can move to something similar to v4. I've looked at [simple-git-hooks](https://github.com/toplenboren/simple-git-hooks) which seems like a nice, small alternative. If it doesn't work for us we can always try the larger move to Husky v8.
=> build: switch to simple-git-hooks

.changeset/loud-birds-wave.md, package.json
Force build always building from source, not using cache, to prevent old versions being mistakenly published
=> chore: bump version to force publishing new version

.circleci/config.yml, scripts/changesets/generate-releases.js
Publishing to npm is failing on CI asking that the user should be logged into NPM.
We are adding a function to use NPM_TOKEN on the CI to avoid this problem
=> chore: add function to use NPM_TOKEN on CI

.changeset/tricky-shoes-sin.md, packages/components/tooltip/src/Tooltip.tsx
Add a `showDelay` property to Tooltip, which lets you control how long a trigger has to be hovered before you show the tooltip.
=> feat(tooltip): add showDelay

.changeset/thirty-crabs-poke.md, packages/forma-36-codemod/transforms/v4-select.js, packages/forma-36-codemod/transforms/v4-text-field.js
* Fix issue with transforming objet to prop when value was boolean
* Fix issue with validationMessage when using memberExpression like: `fields.name.error`
=> fix: codemod issues text field select

.changeset/great-houses-brake.md, packages/components/text-link/src/TextLink.styles.ts, packages/components/text-link/stories/TextLink.stories.tsx
Add vertical-align fix issue when icon was aligned to start.
Closes #2266
=> fix(text-link): fix vertical alignment when icon aligned to start

.changeset/eleven-turkeys-press.md, packages/components/button/examples/ButtonWithIconExample.tsx, packages/components/button/src/Button/Button.tsx, packages/components/button/src/Button/README.mdx, packages/components/datepicker/src/Datepicker.tsx
This PR allows you to set an icon variant for buttons with `variant="transparent"`.
It also fixes a bug with the icon button: We previously allowed setting `variant` for all icon buttons, even the other variants. This is now fixed to only allow `variant="transparent"` just like the regular button.
=> feat(button): allow icon variant for transparent buttons

.changeset/lucky-baboons-end.md, packages/components/accordion/src/AccordionHeader/AccordionHeader.styles.ts, packages/components/button/src/Button/Button.styles.ts, packages/components/card/src/BaseCard/BaseCard.styles.ts, packages/components/copybutton/src/CopyButton.styles.ts, packages/components/drag-handle/src/DragHandle.styles.ts, packages/components/entity-list/src/EntityListItem/EntityListItem.styles.ts, packages/components/text-link/src/TextLink.styles.ts
By default Safari adds `2px` margin to `button`
=> fix: remove default button margin in safari

.changeset/rotten-tables-nail.md, package-lock.json, packages/components/accordion/package.json, packages/components/asset/package.json, packages/components/autocomplete/package.json, packages/components/badge/package.json, packages/components/button/package.json, packages/components/card/package.json, packages/components/collapse/package.json, packages/components/copybutton/package.json, packages/components/datepicker/package.json, packages/components/datetime/package.json, packages/components/drag-handle/package.json, packages/components/entity-list/package.json, packages/components/forms/package.json, packages/components/icons/package.json, packages/components/menu/package.json, packages/components/note/package.json, packages/components/pill/package.json, packages/components/skeleton/package.json, packages/components/table/package.json, packages/components/tabs/package.json, packages/components/tooltip/package.json, packages/components/workbench/package.json, packages/core/package.json, packages/f36-docs-utils/package.json, scripts/plop-templates/package/package.json.hbs
Adds `"react-dom": ">=16.8"` as a peer dependency to our packages. We need this to be able to properly resolve peer dependencies of some libraries we use without conflicts emerging.
=> fix: specify react-dom as peer dependency

.changeset/afraid-singers-notice.md, packages/components/skeleton/src/SkeletonImage/SkeletonImage.tsx, packages/components/skeleton/src/SkeletonText/SkeletonText.tsx
* Adds default border radius of `4px` to Skeleton components
* Exposes `radiusX` and `radiusY` property to Skeleton components
=> feat(Skeleton): add and expose raduis properties

packages/components/entity-list/src/EntityListItem/EntityListItem.styles.ts
Related to https://github.com/contentful/forma-36/pull/2331, account for when there's no `description`
=> feat: account for when there is no entity card description

CHANGELOG.md, packages/components/workbench/package.json
- bump workbench and manually publish to have the correct latest version on npm
=> chore: bump workbench

.changeset/rotten-beds-pay.md, packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.styles.ts, packages/components/workbench/src/WorkbenchHeader/WorkbenchHeader.tsx, packages/components/workbench/stories/Workbench.stories.tsx
* Update WorkbenchHeader component to also accept description as a React Component as well as string.
* Update description text color
https://github.com/contentful/user_interface/pull/12598#discussion_r1024889006
=> feat(workbench): make WorkbenchHeader description accept ReactElement

packages/website/README.md
Replicate https://github.com/contentful/forma-36/pull/2323 since that one is failing on CI
=> docs: add Note to outside contributors for forma websites

.changeset/happy-zebras-help.md, packages/components/forms/examples/FormControlCheckboxGroupExample.tsx, packages/components/forms/examples/FormControlRadioGroupExample.tsx, packages/components/forms/src/BaseCheckbox/BaseCheckbox.tsx
Aligns checkbox label to `flex-start` to avoid it going above automatic width.
=> fix(base-check-box): align items to flex-start

package-lock.json, packages/website/package.json
This reverts commit e855da1457cfdee1456b9ae623ae9c39c24e5337.
Upgrade seems to have broken the styling of live previews for examples.
=> Revert "chore: bump react-live from 2.4.1 to 3.1.1 (#2353)"

.changeset/short-experts-punch.md, packages/components/multiselect/stories/Multiselect.stories.tsx
add changeset to trigger new version release of multiselect component
=> chore: changeset

packages/components/datetime/examples/FormatRelativeDateTimeExample.tsx, packages/components/datetime/src/utils/README.mdx
Our `formatRelativeDateTime` function was undocumented, this PR adds some docs and an example file.
I noticed a problem with the table of contents when doing this, the different `### Example` headings all get the same ID in the document structure, which means that the table of contents links all end up pointing to the first example heading. I tried some different things to work around this, but they didn't work with our ToC implementation.
Things I tried:
- using a custom ID in Markdown: `### Example {#custom-id}`
- tried it with https://github.com/Eyas/md-heading-id/
- using a JSX heading `<h3 id="custom-id">Example</h3>`
- using an anchor inside the heading with custom ID: `###<a id="custom-id"></a>Example`
The last idea is probably something we can get working if we change the …
=> docs(format-relative-date-time): add docs and example

.changeset/metal-suns-dream.md, packages/components/copybutton/src/CopyButton.tsx
Omit native `onCopy` prop from CopyButton
=> fix(copy-button): omit native HTML onCopy prop

.changeset/happy-chicken-notice.md, packages/components/icons/src/ArrowDownward.tsx, packages/components/icons/src/index.ts
Add the long-missing icon "ArrowDownward" ![Icon=ArrowDownward, Size=Tiny, Color=Secondary](https://user-images.githubusercontent.com/156505/215063240-fcc9e4e1-db34-4302-ae4e-5fdb1234f0a7.svg) to the set of icons.
=> feat: add downward icon [SDK-2498]

.changeset/happy-beers-sip.md, packages/components/utils/src/hexToRGBA/hexToRGBA.mdx, packages/components/utils/src/hexToRGBA/hexToRGBA.test.ts, packages/components/utils/src/hexToRGBA/hexToRGBA.ts, packages/components/utils/src/index.ts
Add `hexToRGBA` utility function to manipulate tokens opacity
=> feat: add hexToRGBA utility function

.circleci/config.yml, package-lock.json, package.json
Bump turbo to `1.7.4`
Move `--force` to circleci config to enable running commands per package using `--filter`
=> chore: upgrade turbo to 1.7.4

packages/components/asset/examples/ArchivedAssetExample.tsx, packages/components/asset/examples/AssetExample.tsx, packages/components/asset/examples/ImageAssetExample.tsx
Replace usage of placeimg with asset from Contentful's image service on Asset examples
=> fix: replace placeImg with static image on Asset examples

packages/website/components/LiveEditor/ComponentSource.tsx
Reason: [Skeleton](https://f36.contentful.com/components/skeleton#__next) isn't working on Safari
Currently we're using display flex on live preview wrapper to center all examples in the middle. This however sometimes breaks the default behaviour of components e.g. Skeletons works well when displayed in `div: block` but when within flex component the svg needs a fixed height.
IMO, we should display examples as it would be rendered in a normal div as a wrapper.
The cost here is that live examples won't be aligned to the center, which I believe is fine and even looks better to my eyes
=> fix(docs): remove flex styles from live preview wrapper

packages/website/components/MdxRenderer.tsx
Render `strong` elements with our `Text` component to get the right font weight.
=> fix(website): render `strong` as Text component

packages/components/badge/src/Badge/Badge.styles.ts, packages/components/badge/src/EntityStatusBadge/EntityStatusBadge.tsx
> I noticed that we (recently I believe) removed the uppercase conversion on the Badge element that we were previously doing, I assume intentionally.
One small unintended side effect is that it exposes inconsistent casing in the underlying text which never used to matter since it wasn't visibile. Case in point on the Forma 36 website itself:
Main section shows Title case, sidebar is lower case.
Sentence case is what we want to enforce
=> fix: badge letter casing

.changeset/bright-bugs-drum.md, packages/components/copybutton/src/CopyButton.tsx
Adds a fallback copy method for the async clipboard API to fix an issue where Chrome would not let the `CopyButton` copy in iframes without the `allow="clipboard-write"` attribute. We currently have a lot of these iframes since they render apps.
=> fix(copy-button): copy in environments without clipboard API permission

.changeset/twenty-ducks-confess.md, .eslintrc.js, packages/components/modal/examples/ModalAutoFocusExample.tsx, packages/components/modal/examples/ModalInitialFocusRefExample.tsx, packages/components/modal/src/Modal.test.tsx, packages/components/modal/src/Modal.tsx, packages/components/modal/src/README.mdx
- remove an arbitrary timeout before making initial focus
- check if the already focused element is a descendant of modal element (allows to use native `autoFocus` for initial focus)
=> fix(modal): remove modal initial focus timeout

.changeset/fast-colts-joke.md, packages/components/menu/src/Menu.tsx, packages/components/popover/src/Popover.tsx
- Improve `Popover` and `Menu` components `onBlur` logic.  So when a user clicks outside of the document or uses some browser features, like search (with `cmd/ctrl+F` combination) the dropdown is not collapsing. It's also handy for developers if they want to debug dropdown content.
I've tested it in Safari, Firefox & Chrome. And encourage you to do the same 🙂
=> fix: improve Menu & Popover onBlur handler

.changeset/beige-experts-hug.md, packages/components/badge/src/EntityStatusBadge/EntityStatusBadge.tsx
Changes Archived status from `negative` variant to `secondary`.
=> fix(entity-status-badge): use secondary variant for Archived

packages/website/components/SidebarLink.tsx
Fix badge also having underline when link is hovered on the sidebar
=> fix: remove underline from badge when hovered on sidebar

.changeset/cold-baboons-jog.md, packages/components/modal/src/Modal.styles.ts
When clicking outside the modal content, the modal should close.
When clicking close to the modal content edges, the modal doesn't close
https://user-images.githubusercontent.com/6163988/234340673-77ce3163-dfac-4f07-93aa-22177ce563bc.mov
=> fix: close modal when clicking outside closely

.changeset/large-mangos-do.md, packages/components/modal/examples/ModalBasicExample.tsx, packages/components/modal/src/Modal.tsx, packages/components/modal/src/ModalHeader/ModalHeader.tsx, packages/components/modal/stories/Modal.stories.tsx
=> feat: add subtitle prop to Modal

.changeset/metal-starfishes-provide.md, package-lock.json, packages/components/badge/examples/EntityStatusBadgeArchivedExample.tsx, packages/components/badge/examples/EntityStatusBadgeChangedExample.tsx, packages/components/badge/examples/EntityStatusBadgeDeletedExample.tsx, packages/components/badge/examples/EntityStatusBadgeDraftExample.tsx, packages/components/badge/examples/EntityStatusBadgeNewExample.tsx, packages/components/badge/examples/EntityStatusBadgePublishedExample.tsx, packages/components/badge/examples/EntityStatusBadgeScheduledExample.tsx, packages/components/badge/package.json, packages/components/badge/src/EntityStatusBadge/EntityStatusBadge.tsx, packages/components/badge/src/EntityStatusBadge/README.mdx, packages/components/badge/stories/EntityStatusBadge.stories.tsx
Add a prop to `EntityStatusBadge` that lets us mark entities as having a scheduled action. This will make the badge render our `ClockIcon`.
=> feat(entity-status-badge): add isScheduled prop

.changeset/stupid-readers-heal.md, packages/components/button/src/Button/Button.styles.ts
The transparent button should keep the background as `none` when focused, only difference should be the outline. Have a look at https://forma-36-git-fix-transparent-button-hover.colorfuldemo.com/components/button#variants
=> fix(button): retain transparent button focus background

packages/components/icon/src/Icon.tsx
Adding a `role` prop for image components adds a `aria-role` attribute, which not only increases the accessibility, but also allows us to use `findByRole` queries in tests to find image elements.
=> feat: add a 'role' prop for icon elements

.changeset/large-hotels-wait.md, packages/components/forms/src/Select/Select.styles.ts
Small Selects had incorrect padding, which was causing long text to overlap with the chevron
Before:
After:
=> fix: small Select padding

packages/components/avatar/README.mdx, packages/components/avatar/examples/AvatarColorBorderExamples.tsx, packages/components/avatar/examples/AvatarIconExamples.tsx, packages/components/avatar/examples/AvatarIsActiveExamples.tsx, packages/components/avatar/examples/AvatarIsPrimaryExamples.tsx, packages/components/avatar/examples/AvatarSizeExample.tsx, packages/components/avatar/src/Avatar.styles.ts, packages/components/avatar/src/Avatar.test.tsx, packages/components/avatar/src/Avatar.tsx, packages/components/avatar/src/index.ts, packages/components/avatar/stories/Avatar.stories.tsx, packages/website/components/LiveEditor/ComponentSource.tsx
This PR adds the following new properties to the `Avatar` component:
- showColorBorders
- isPrimary
- isActive
- icon
And replace enums for sizes and variants with simple string types
=> feat: Introduce new properties for the Avatar component [HOMER-2119]

.github/dependabot.yml
Set [dependabot versioning strategy](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy) to `widen`. This seems like the right move for libraries.
=> chore(dependabot): widen versions when possible

package-lock.json, packages/website/package.json
Upgrading `next-auth` should get rid of the "version not supported" error we're seeing for node 18.
=> chore(deps): bump next-auth

packages/components/avatar/package.json, packages/components/avatar/src/Avatar/Avatar.styles.ts, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/src/Avatar/examples/AvatarColorBorderExamples.tsx, packages/components/avatar/src/Avatar/index.ts, packages/components/avatar/src/Avatar/utils.ts, packages/components/avatar/src/index.ts, packages/components/avatar/stories/Avatar.stories.tsx, packages/components/avatar/stories/AvatarGroup.stories.tsx
For the Avatar component it will 
- introduce 3 custom colors
-  fix muted style (transparent stacked avatars where shining trough each other)
**before**
**after**
=> feat: update avatar colors [HOMER-2193]

package-lock.json, packages/components/avatar/package.json, packages/components/avatar/src/Avatar/Avatar.test.tsx, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/src/AvatarGroup/AvatarGroup.test.tsx, packages/components/avatar/src/AvatarGroup/AvatarGroup.tsx, packages/components/avatar/stories/Avatar.stories.tsx, packages/components/avatar/stories/AvatarGroup.stories.tsx
Add tooltip support for the Avatar and AvatarGroup components.
Renders the tooltip when configured:
Does not render the tooltip inside the dropdown for the AvatarGroup component:
=> feat: add tooltip support for avatar and avatar group components []

packages/components/avatar/package.json, packages/components/avatar/src/AvatarGroup/AvatarGroup.styles.ts, packages/components/avatar/stories/AvatarGroup.stories.tsx
When providing a tooltip for avatars, the style assignment with negative margins is lost, therefore attaching it to the wrapping container.
=> fix(avatar-group): position of stacked avatars when using tooltip

package-lock.json, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/stories/AvatarGroup.stories.tsx
When the tooltip was shown inside a stacked avatar group, the alignment was off, due to the negative margin on the elements. By leveraging the usePortal option, the tooltips are no longer influenced by the margin settings of their parents.
**before**
**after**
=> fix: tooltip position by using portal option 

.changeset/plenty-steaks-pretend.md, package-lock.json, packages/components/forms/src/Checkbox/README.mdx, packages/components/forms/src/Radio/README.mdx, packages/components/forms/src/Select/README.mdx, packages/components/forms/src/Textarea/README.mdx, packages/components/forms/stories/CheckboxGroup.stories.tsx, packages/components/forms/stories/RadioGroup.stories.tsx
This is an update for the documentation to further improve the accessibility guidelines and how to leverage `FormContro`l for semantic validation and error states.
Updated guidelines for following components:
- Checkbox and Checkbox.Group
- Radio and Radio.Group
- Select
- Textarea
=> chore(forms): update accessibility guidelines for inputs

packages/components/forms/examples/SelectSizes.tsx, packages/components/forms/examples/SelectWithLabelExample.tsx, packages/components/forms/examples/SelectWithValidationExample.tsx, packages/components/forms/src/Select/README.mdx
Updates the Documentation for Select component, adding examples for different sizes as well as updating the the correct FormControl usage
=> docs: update select examples

.changeset/khaki-suits-perform.md, packages/components/asset/src/Asset.styles.ts, packages/components/asset/src/Asset.tsx
Sets `width: 100%` on Asset root. This is a bug we somehow never got fixed in F36 itself, I think no one ever made a ticket.
Tested in the web app.
=> fix(asset): set full width

.changeset/mean-pigs-fail.md, packages/components/card/src/InlineEntryCard/InlineEntryCard.tsx
Remove the `size` prop from InlineEntryCard. This prop was never supported or used.
=> fix(inline-entry-card): remove size prop

.changeset/grumpy-bags-complain.md, packages/components/button/src/Button/Button.styles.ts, packages/components/button/src/ButtonGroup/ButtonGroup.styles.ts
ButtonGroup: add full height divider to Primary and Positive: 1px #FFFFFF at 20% opacity;
Button: Remove Primary/Positive button border color
https://github.com/contentful/forma-36/assets/22265863/fb1e4ddf-a8c7-46d6-8077-a7a2dd7ad3ac
=> chore: [F36-889] full height button group divider

.changeset/hot-ravens-play.md, packages/components/button/src/ToggleButton/ToggleButton.styles.ts
ToggleButton: remove blue border on hover state; change background color on hover
Before:
https://github.com/contentful/forma-36/assets/22265863/2ef635aa-543c-48f8-be9a-07f5cd49e4b6
After:
https://github.com/contentful/forma-36/assets/22265863/b98a46d0-c4cd-4571-976a-dd336a9331bb
=> chore: [F36-898] toggle button styles

.changeset/soft-queens-eat.md, packages/components/autocomplete/examples/AutocompleteMultiSelectionExample.tsx, packages/components/autocomplete/src/Autocomplete.test.tsx, packages/components/autocomplete/src/Autocomplete.tsx, packages/components/autocomplete/stories/Autocomplete.stories.tsx
What's changed:
- ❌ `clearAfterSelect` (`boolean`) replaced with 🆕 `textOnAfterSelect` (`'clear' | 'preserve' | 'replace'`) to be able to preserve the text input value when item selected
- 🆕 `inputValue` prop added to be able to clear the text input programmatically (e.g. on menu close)
- 🆕 `isOpen` prop added (and corresponding `onOpen`, `onClose` handlers) to be able to control menu state and subscribe to its change
https://github.com/contentful/forma-36/assets/22265863/65807b83-0400-422c-9a54-33ce439be045
=> feat(Autocomplete): add controllable isOpen, inputValue props; extend text behaviour on item select

packages/f36-docs-utils/src/PropsTable/PropsTable.tsx, packages/website/utils/propsMeta.ts
Add a clear way to mark props as deprecated in the docs.
Example: https://forma-36-git-feat-docsdeprecated.colorfuldemo.com/components/autocomplete#props-api-reference:~:text=the%20root%20element-,clearAfterSelect
Before:
After:
=> docs: show deprecated prop badge

packages/website/components/Playground/SandpackRenderer.tsx
The https://npmjs.com/package/@contentful/f36-core was missing from the playground dependencies.
| Before |
|--------|
| <img alt="before" src="https://github.com/contentful/forma-36/assets/103024358/2c1c53b6-b487-4564-b8f0-f63fa5422fa8"> |
| After |
|--------|
| <img alt="after" src="https://github.com/contentful/forma-36/assets/103024358/777c0821-25f4-410c-8e15-76bef681bf36"> |
=> fix: add 'f36-core' to playground dependencies

packages/components/navlist/README.mdx
Update `NavList` documentation
=> docs: update Navlist documentation

.changeset/spotty-insects-talk.md, packages/components/text-link/src/TextLink.styles.ts, packages/components/text-link/src/TextLink.tsx, packages/components/text-link/stories/TextLink.stories.tsx
TextLink text should be align to baseline, but Icon inside should be center aligned.
Before: 
After:
Related to https://github.com/contentful/forma-36/pull/2295
=> fix(TextLink): vertical alignment when used in list

.changeset/beige-guests-exercise.md, packages/components/button/src/Button/Button.tsx
Fix transparent Button loading icon color
Before:
After:
=> fix(Button): transparent variant loading icon color

.changeset/breezy-geese-hug.md, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/tooltip/README.mdx, packages/components/tooltip/src/Tooltip.test.tsx, packages/components/tooltip/src/Tooltip.tsx, packages/components/tooltip/src/index.ts, packages/components/tooltip/stories/Tooltip.stories.tsx, packages/forma-36-codemod/transforms/v4-tooltip.js
Support `ReactElement` as Content for `Tooltips`
=> feat(Tooltip): support ReactElement as content

.changeset/breezy-geese-hug.md
The previous changeset was causing the pipeline to break since it has a mixed of:
```
Found ignored packages: @contentful/f36-avatar
Found not ignored packages: @contentful/f36-tooltip
```
=> chore: remove previous changeset

.changeset/two-penguins-argue.md, packages/components/avatar/package.json, packages/components/tooltip/src/Tooltip.tsx
- fix: Make label optional to keep backward compatibility
- Some customers may already be providing react elements as content and this will break their implementation
- fix: Change TooltipProps back to an interface
- chore: Create new Avatar release
=> fix(Tooltip): Fix Tooltip type issues

.changeset/heavy-geese-lick.md, packages/components/text-link/src/TextLink.styles.ts, packages/components/text-link/src/TextLink.tsx, packages/components/text-link/stories/TextLink.stories.tsx
Fix TextLink vertical alignment when used within flexbox container.
When used within a flexbox container TextLink stretches to full height. It used to have `style="align-items: center"` so when it's stretched it still would look aligned. But with recent changes in  https://github.com/contentful/forma-36/pull/2574 it was changed to `style="align-items: baseline"` to align it when used within inline text elements.
With this PR I'd like to return previous behaviour back (when TextLink is stretched to full height, and its elements are centrally aligned), but at the same time keep text and icon aligned to baseline when used within other text.
🚨 But to make it work I had to add an extra DOM element.
<details>
<summary>Bug screenshots</summary>
</details>
=> fix(TextLink): vertical alignment when used within flexbox container

.changeset/tidy-bees-fry.md, packages/components/icon/package.json, packages/components/list/package.json, packages/components/multiselect/package.json, packages/components/pagination/package.json, packages/components/popover/package.json, packages/components/spinner/package.json, packages/components/text-link/package.json, packages/components/typography/package.json
Because the packages in question rely on `@contentful/f36-core` (and in one case, `react-popper`), which has `react-dom` in its `peerDependencies`, these packages need to have `react-dom` in their `peerDependencies` as well.
Fixes #2586
=> fix: fix missing peerDependency warnings

packages/components/datepicker/README.mdx, packages/components/datepicker/examples/Datepicker/DefaultOpen.tsx, packages/components/datepicker/examples/Datepicker/WithFormControl.tsx, packages/components/datepicker/examples/Datepicker/WithMinMaxDate.tsx, packages/components/datepicker/examples/Datepicker/WithMultipleMonths.tsx, packages/components/datepicker/stories/Datepicker.stories.tsx
This work takes care of updating our Documentation and Storybook based on the latest API changes.
**Documentation**
- Example of [setting a date range](https://forma-36-git-f36-809-date-picker-documentation-and-storybook.colorfuldemo.com/components/datepicker#limiting-the-date-range)
- Example of [setting multiple months in view](https://forma-36-git-f36-809-date-picker-documentation-and-storybook.colorfuldemo.com/components/datepicker#multiple-months)
**Storybook**
- Addition of the `weekStartsOn` prop to the [Controls](https://5fd1dda724cc620021ace8c5-cznuityhjx.chromatic.com/?path=/story/components-datepicker--basic)
- I had to define the arg types manually since Storybook is not inferring all the props from the component, even tho the `@storybook/addon-essentials` is installed and …
=> docs(Datepicker): update documentation + stories

packages/components/forms/examples/TextInputIconExample.tsx, packages/components/forms/examples/TextInputSizeExample.tsx, packages/components/forms/src/TextInput/README.mdx, packages/components/forms/stories/TextInput.stories.tsx
This work takes care of updating our Documentation and Storybook based on the latest API changes.
**Documentation**
- Example of [using an icon](https://forma-36-git-f36-805-text-input-documentation.colorfuldemo.com/components/text-input#using-an-icon)
- Example [with different sizes](https://forma-36-git-f36-805-text-input-documentation.colorfuldemo.com/components/text-input#with-different-sizes)
**Storybook**
- Addition of the icon and group examples to the [Overview](https://5fd1dda724cc620021ace8c5-loctfpjcvq.chromatic.com/?path=/story/form-elements-textinput--overview)
=> docs(TextInput): update documentation + stories

packages/components/multiselect/src/Multiselect.tsx
This pull request addresses a scrolling issue encountered when using the Multi Select component. By adding the `preventScroll: true` option, we ensure that the user's scroll position is maintained while the focus lock is active.
- Modified the FocusLock component in Multi Select to include focusOptions with `preventScroll: true`.
- Ensured the focus is returned after the FocusLock is deactivated using `returnFocus={true}`.
https://github.com/contentful/forma-36/assets/22968325/a8dd9161-5ff2-4517-9601-0d297d206180
https://github.com/contentful/forma-36/assets/22968325/3beb8ef4-9a3b-4b68-83c1-187961acb6f4
=> fix: focus lock multi select

packages/components/text-link/README.mdx
Fixing the broken link from the [CircleCI link check](https://app.circleci.com/pipelines/github/contentful/forma-36/10968/workflows/11fe9971-5313-43d2-adeb-22db7cb7ccc1/jobs/30405/parallel-runs/0/steps/0-113?invite=true#step-113-183689_50).
The previous link seems to redirect to a new domain, maybe this redirect was failing on the CLI 🤷
=> docs(TextLink): update link

.changeset/chilly-baboons-sip.md, .changeset/olive-starfishes-chew.md, packages/components/button/src/ButtonGroup/types.ts, packages/components/card/src/BaseCard/BaseCard.types.ts
- simplify `ButtonGroup` child prop type and `BaseCard` badge prop type
=> fix: simplify ButtonGroup child type

.changeset/pretty-drinks-buy.md, packages/components/autocomplete/src/Autocomplete.tsx
Add an additional `popoverTestId` prop to the `Autocomplete` component. When passed it replaces the default suggestion box popover test ID (`cf-autocomplete-container`).
Make elements inside the portal used for the suggestion box identifiable for tests.
=> feat(autocomplete): add separate test ID prop for suggestion box popover

.changeset/khaki-cows-divide.md, packages/components/button/src/IconButton/IconButton.tsx
- Fix `IconButton` size prop marked as deprecated. Leave it only as comment for size `large`.
Related PR: 
https://github.com/contentful/forma-36/pull/2576
=> fix: IconButton size type

packages/components/datepicker/examples/Calendar/CustomDayContent.tsx, packages/components/datepicker/src/Calendar/README.mdx
Adjusted the naming of Custom Day content example code to not reflect Indicator. Also Adjusted a typo.
The purpose of this PR is to align on the Calendar component naming - specifically the use of Indicator vs Custom Day content. We noticed that within the Custom Day content code example within the docs, it references an 'IndicatorExample', so we have adjusted this to be `CustomDayContentExample`. There also existed a small typo in the docs (Incators vs Indicators) so we have adjusted this. 
Note the main change here: 
We believed this to be the extent of the name alignment task, but also considered in the beginning that perhaps the Indicator and CustomDayContent examples are duplicative. We determined that each code example is reflecting differing implementation methods, even though the …
=> docs(calendar): align naming of Indicator vs Custom Day content examples

packages/components/datepicker/stories/Calendar.stories.tsx
Move Calendar component stories out of Datepicker in the Storybook navigation. Rename Default story to Basic.
This PR moves the Calendar component stories out from under the Date Picker in the Storybook navigation. It also renames the `Default` story to `Basic`.
=> docs(calendar): move calendar stories and rename Basic story

.changeset/khaki-books-change.md, package-lock.json, packages/forma-36-react-components/package.json
F36 currently has a pinned dependency on `@types/react` and `@types/react-dom`. When the consuming project of F36  installs a different version of the type packages, they might run into type issues/conflicts.
This PR moves `@types/react` and `@types/react-dom` to peer dependencies, marks them as optional and unpins them. That way the packages can be deduped which prevents type issues.
This matches how [@mui/material](https://github.com/mui/material-ui/blob/b7fea89bc232622546b6bc9675a818bfa95a8376/packages/mui-material/package.json#L90-L107) and [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap/blob/a58a0cd6e548c653cda23ed529f3cff69ec123cc/package.json#L147-L156) handle these dependencies.
=> fix: make `@types/react` & `@types/react-dom` peer dependencies

.changeset/lovely-steaks-rush.md, packages/components/collapse/examples/CollapseExample.tsx, packages/components/forms/src/BaseCheckbox/BaseCheckbox.styles.ts
This work fixes 2 issues:
When opening the `Collapse` playground from the documentation (https://f36.contentful.com/components/collapse), the playground crashes.
| <img width="1498" alt="collapse-before" src="https://github.com/contentful/forma-36/assets/103024358/8099f154-24c4-4adc-b6fe-b8db06b9fdad"> [Link](https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwHJNjSaBuAHQDtUMddhcAhAK7ZsENgBpcAYQgAbGUTQBnGBIAqMAB7YJAZWwkA1rgC+uClVoABSG2wxbZATID0ZAMwA2ALSR0o+9iKzOzsmlzkAmykSKJSsvJKMACiGkToMjAAFACUPOy4uDaKeADaSIopaERssFASytgAkhUaVTUwUAC6uAC8BAzYAHQCynpEdpnYmAIw2axsBfTYApgLmfkFuAA8Y2BGZBkaACJI9NGiPSzgsgIobFcAfBub24LCsaKSMkh7PcA5vQeuAazUq1VqmQAhOUwe0oNljA9VBAAOYojJbZxvERsJ4LF7baRyBTKXAw1rgjp-cltWqI54ErbqLR4gkEyQjEQoGCYRS4W …
=> fix: various quirks

.changeset/red-pots-trade.md, packages/components/button/src/Button/Button.styles.ts
Re-establish the correct (low-density) spacing for the Button's small size. 
The wrong spacing was introduced in #2620 and wrongly accepted as the baseline in Chromatic.
https://github.com/contentful/forma-36/pull/2620/files#diff-981a117f17abd2f26007fc35dae060ed779500d4a4fb62f4ef09969ac3ef96f9L119
| <img width="268" alt="Screenshot 2023-12-06 at 14 43 33" src="https://github.com/contentful/forma-36/assets/103024358/fd40e937-d3a1-42bc-b656-9b975a469c39"> | <img width="282" alt="Screenshot 2023-12-06 at 14 43 03" src="https://github.com/contentful/forma-36/assets/103024358/bc9cc57b-31f5-41d8-8983-3203b5014f88"> |
=> fix(Button): default padding for small size

packages/components/avatar/CHANGELOG.md, packages/components/density-container/CHANGELOG.md, packages/components/header/CHANGELOG.md, packages/components/image/CHANGELOG.md, packages/components/layout/CHANGELOG.md, packages/components/navlist/CHANGELOG.md
Follow-up #2629.
The prerelease script tries to access the CHANGELOG.md of each package but the `alpha` packages do not have such (because they aren't released).
=> chore: add changelog to alpha packages

.github/workflows/npm-package-publisher.yml
Follow-up of #2631 
The GitHub action is not able to access the action from the private package (even tho it is located in the same organization).
Checking out the repository and running the action locally should resolve it ([documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-an-action-inside-a-different-private-repository-than-the-workflow)).
=> chore: adjust `npm-package-publisher` action

.changeset/rotten-eggs-compare.md, packages/components/card/src/BaseCard/CardActions.styles.ts, packages/components/card/src/BaseCard/DefaultCardHeader.tsx
Fix entry card wrapping style for smaller sizes (like in Live Preview)
##Before
##After
=> fix: entry card wrapping [TOL-1721]

packages/components/density-container/README.mdx, packages/components/utils/src/useDensity/useDensity.mdx, packages/components/utils/src/useDensity/useDensity.test.tsx, packages/components/utils/src/useKeyboard/useKeyboard.mdx, packages/website/pages/[...slug].tsx, packages/website/types.ts, packages/website/utils/sidebarLinks.json
When this hook was introduced, its documentation + tests were missing.
I took the opportunity to add a new `hooks` section to the sidebar, moving the `useKeyboard` there too.
=> docs(useDensity): add documentation + test

packages/website/README.md, packages/website/content/tokens/border-radius.mdx, packages/website/mdx-components/BorderRadiusTable.tsx, packages/website/mdx-components/index.ts, packages/website/utils/sidebarLinks.json
To make border radius tokens publicly visible
Jira ticket: https://contentful.atlassian.net/browse/CFCX-1237
What changed:
- added the border radius section in tokens
- updated the website READE file about env variables
screenshot of the new section:
=> feat: [CFCX-1237] design system debt border radius tokens make publicly visible

.changeset/eighty-lobsters-cheat.md, packages/components/workbench/src/WorkbenchContent/WorkbenchContent.styles.ts, packages/components/workbench/src/WorkbenchSidebar/WorkbenchSidebar.styles.ts
Fix a glitch on Safari 17.x where the view gets corrupted on scroll.
=> fix(components): fix rendering glitch on Safari 17.x

.circleci/config.yml
The `semantic-release` template of the vault doesn't have the `READ` secret, only the `WRITE`
=> chore: fix secret name on changelog job []

.changeset/beige-olives-report.md, package-lock.json, packages/components/card/examples/EntryCard/EntryCardCustomBadgeExample.tsx, packages/components/card/src/EntryCard/EntryCard.tsx, packages/components/card/src/EntryCard/EntryCard.types.ts, packages/components/card/src/EntryCard/README.mdx, packages/components/card/stories/EntryCard.stories.tsx
In order to properly show the new ExternalResourceCards status badges, this PR aims to enable passing the new Badges as an option `badge` to the `EntryCard` component
=> feat: enable Badge option on EntryCard

.changeset/rotten-ways-drop.md, packages/components/multiselect/src/Multiselect.tsx, packages/website/content/changelog.mdx
MultiSelect: Forwards the `onClose` Popover-prop inside the MultiSelect component ensuring it's called.
=> feat(multi-select): forward popover onClose

.changeset/fair-impalas-beg.md, packages/components/modal/src/ModalConfirm/ModalConfirm.test.tsx, packages/components/modal/src/ModalConfirm/ModalConfirm.tsx, packages/components/modal/src/ModalHeader/ModalHeader.tsx
The `<ModalConfirm>` should always render a `x` close button in the modal header.
This is accomplished by passing the `onClose` prop from `<ModalConfirm>` to `<Modal.Header>` to ensure that the header will render an `x` to dismiss the modal.  [See conditional rendering of close button in ModalHeader](https://github.com/contentful/forma-36/blob/main/packages/components/modal/src/ModalHeader/ModalHeader.tsx#L51-L63)
=> ModalConfirm - render 'x' in ModalHeader

packages/components/datetime/src/utils/formatDateTimeUtils.test.ts, packages/components/datetime/src/utils/formatDateTimeUtils.ts
In the UI, we sometimes see mismatching times being rendered if you're not in the UTC timezone. That is because some datetime utils transform the time to the UTC timezone (`formatMachineReadableDateTime`) while others don't (`formatDateAndTime`). When we use both in the UI (e.g. for rendering scheduled actions), we get mismatching times from two different timezones (current vs. UTC).
I started this PR by first re-creating our use case to proof that this function is the root cause. Afterward, I adjusted the function and confirmed that the tests were successful.
=> fix: drop transform to UTC when creting machine readable datetime [SPA-1849]

.changeset/orange-rice-drop.md, package-lock.json, packages/forma-36-react-components/package.json
Currently `f36-components` still serves `@contentful/f36-navbar@4.1.0` and doesn't update to the latest version `4.1.1`
=> chore(f36-components): bump navbar package to latest

.changeset/thirty-comics-repair.md, packages/components/card/examples/EntryCard/EntryCardCustomActionButtonExample.tsx, packages/components/card/src/BaseCard/BaseCard.tsx, packages/components/card/src/BaseCard/BaseCard.types.ts, packages/components/card/src/BaseCard/DefaultCardHeader.tsx, packages/components/card/src/EntryCard/EntryCard.tsx, packages/components/card/src/EntryCard/README.mdx, packages/components/card/stories/EntryCard.stories.tsx
This PR enables consumers of Forma36 to provide their own React component as a replacement for the default `...` action menu.
If the custom component is provided, it takes precedence over default action menu. Otherwise the card renders as before with support for actions provided as Entry Card props.
**Default action menu:**
**Custom component:**
=> feat(entry card): entry card supports custom action button

.changeset/calm-eggs-lay.md, package-lock.json, packages/forma-36-codemod/bin/cli.mjs, packages/forma-36-codemod/bin/f36-codemod.js, packages/forma-36-codemod/bin/f36-codemod.mjs, packages/forma-36-codemod/bin/inquirer-choices.mjs, packages/forma-36-codemod/bin/packages-list.mjs, packages/forma-36-codemod/bin/updateDependencies.mjs, packages/forma-36-codemod/package.json
ESM codemod to unblock package upgrades.
=> feat(f36-codemod): ESM

package-lock.json, package.json
`changesets` still uses `@manypkg/get-packages@1.1.3`.
Updating this was causing the `changelog:gen` script to fail.
=> Revert "chore: bump @manypkg/get-packages from 1.1.3 to 2.2.1 (#2691)"

catalog-info.yaml
=> chore: change team from CX to Isotopes

packages/components/header/package.json, packages/components/header/src/Breadcrumb.styles.ts
Removes `max-width` from breadcrumb buttons.
=> fix(breadcrumb): remove max-width

.changeset/chatty-singers-cry.md, .changeset/chilly-kiwis-exercise.md, packages/components/badge/src/Badge/Badge.styles.ts, packages/components/badge/src/Badge/Badge.tsx
This adds a prop to the Badge component so as to not have to overwrite styles when using it with text that should remain consistently capitalized and not adhere to the Badge capitalization restrictions
=> feat(badge): add prop to skip CSS text transforms

.changeset/weak-buckets-stare.md, packages/components/badge/src/Badge/Badge.styles.ts, packages/components/badge/src/Badge/Badge.tsx
Recent Badge change included a default CSS `text-transform: capitalize`, but this is not the same as the default we had, where only the first word was capitalized. This fixes that, but still allows users to avoid the transform overall. Also aligns with our existing styling APIs where we pass arguments to the individual style keys rather than the overall function.
=> fix(badge): restore default text transform

packages/forma-36-codemod/package.json, packages/forma-36-codemod/transforms/__testfixtures__/v5/icons.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v5/icons.output.js, packages/forma-36-codemod/transforms/v5/icons.js, packages/forma-36-codemod/utils/updateTernaryValues.js
Icons v5 have updates props, we remove not supported props and update the values of the size prop.
=> feat: V5 icons codemod

.changeset/curvy-ladybugs-provide.md, packages/core/src/types.ts
We need this custom Omit utility type to support upcoming library updates where some extended-type properties get lost when using Omit.
- https://github.com/microsoft/TypeScript/issues/36981
- https://github.com/microsoft/TypeScript/issues/54451
=> feat: add custom omit utility type

.changeset/bright-kiwis-hear.md, packages/components/menu/src/MenuItem/MenuItem.tsx
- proxy 'isDisabled' prop as native 'disabled' prop to the underlying component
=> fix: proxy 'isDisabled' prop as native 'disabled' to underlying component [NONE]

packages/components/datepicker/src/Calendar/README.mdx
Their website update (https://github.com/gpbl/react-day-picker/pull/2112)
broke two links which makes CI fail
=> docs: update react-day-picker links

.changeset/silver-islands-try.md, packages/components/navbar/examples/WithAccountNotificationNavbarExample.tsx, packages/components/navbar/src/NavbarAccount/NavbarAccount.styles.ts, packages/components/navbar/src/NavbarAccount/NavbarAccount.tsx, packages/components/navbar/stories/Navbar.stories.tsx
-  Introduce a new notification 'info' variant for NavbarAccount component. We need it for the new **FPC** (feature preview center)
⚠️  Changes for the new Light Navbar:
https://github.com/contentful/forma-36/pull/2751
=> feat: new variant for navbar account notif

.changeset/config.json, .changeset/selfish-monkeys-beam.md
Add "@contentful/f36-navbar" to umbrella package as a fixed dependency
=> fix: Add "@contentful/f36-navbar" to umbrella package as a fixed dependency

packages/forma-36-codemod/transforms/__testfixtures__/v5/icons.input.js, packages/forma-36-codemod/transforms/__testfixtures__/v5/icons.output.js, packages/forma-36-codemod/transforms/v5/icons.js
- If icons had the size property as an expression, e.g. `{'large'}`, this was causing the codemod to throw an error and not update the code
=> fix: icons v5 codemod size with expression container []

packages/components/navbar/package.json, packages/components/navbar/src/Navbar.styles.ts, packages/components/navbar/src/Navbar.tsx, packages/components/navbar/stories/Navbar.stories.tsx
This enables controlling the size of the navbar content via a dedicated prop instead the need to handover specific width sizes.
=> feat: introduce size variants for light navbar

packages/components/icon/package.json, packages/components/icon/src/utils/wrapPhosphorIcon.tsx, packages/components/icons/package.json
We were passing the `testId` prop without renaming it, what would make tests that rely on the `data-test-id` to fail
=> fix: properly pass testId as data-test-id to components []

.changeset/config.json, .changeset/nasty-tomatoes-boil.md, .changeset/proud-kings-kneel.md, packages/components/avatar/package.json, packages/components/avatar/src/Avatar/README.mdx, packages/components/image/README.mdx, packages/components/image/package.json, packages/components/navbar/package.json, packages/forma-36-react-components/package.json, packages/forma-36-react-components/src/index.ts, packages/website/components/LiveEditor/ComponentSource.tsx, packages/website/components/Playground/SandpackRenderer.tsx, packages/website/package.json
This PR moves Avatar from the alpha package to the automatic release.
=> feat(changesets): move avatar from alpha package to automatic release [AHOY-3166]

packages/components/avatar/src/Avatar/README.mdx, packages/components/avatar/src/AvatarGroup/README.mdx, packages/components/image/README.mdx
Purpose of PR
Update website to remove `alpha` tag from Avatar, AvatarGroup and Image components.
Should we add the `new` tag?
=> docs: change status from alpha to stable of Avatar and Image []

.changeset/small-ways-kneel.md, packages/components/button/src/Button/Button.tsx
To enable usage of the Icons V5 alpha we need to pass the color prop from the Button to the Icons
=> refactor: pass color prop to icon from Button [CFISO-1471]

.changeset/config.json, .changeset/happy-beds-glow.md, packages/components/header/README.mdx, packages/components/header/package.json, packages/components/header/src/Header.styles.ts, packages/forma-36-react-components/package.json, packages/forma-36-react-components/src/index.ts, packages/website/components/LiveEditor/ComponentSource.tsx, packages/website/components/Playground/SandpackRenderer.tsx, packages/website/package.json
Left margin on Header’s title prop is no longer rendered when there’s no element to the left of the title
I updated the `noWrap` class styling so that the margin is only applied if the element is not first-child. This follows the existing approach we use for the `title` class
I had done something similar when working on the Updated Layout component, in [this commit](https://github.com/contentful/forma-36/pull/2747/commits/6576cdf2392465023ad282ecd9182ac07330d9fb).
Tickets: 
https://contentful.atlassian.net/browse/CFISO-1571
=> Header: Remove unwanted margin from title, release as stable component

packages/website/content/tokens/typography.mdx
The same line exists twice in the docs: 
https://f36.contentful.com/tokens/typography
=> docs(Typography): remove duplicate line in docs

.changeset/famous-doors-kiss.md, packages/components/modal/src/ModalLauncher/ModalLauncher.test.tsx, packages/components/modal/src/ModalLauncher/ModalLauncher.tsx, packages/components/modal/stories/ModalLauncher.stories.tsx
It's currently not possible to know when all Modal have been closed after `ModalLauncher.closeAll()`. Due to close delays and the async implementation, Modals may still be open after `ModalLauncher.closeAll()` is called.
This PR makes the function async and resolve when all Modals are closed. This changes the return type and could therefore cause typescript issues in projects using F36.
=> feat(ModalLauncher): wait for Modals to be closed

.changeset/polite-jobs-double.md, packages/components/card/examples/AssetCard/AssetCardCustomBadgeExample.tsx, packages/components/card/src/AssetCard/AssetCard.tsx, packages/components/card/src/AssetCard/README.mdx, packages/components/card/stories/AssetCard.stories.tsx
The `EntryCard` supports providing a custom badge, the `AssetCard` don't do that yet.
This PR introduces the custom badge for the AssetCard too, to have the same behaviour and experience.
=> feat(AssetCard): support for providing a custom badge

packages/components/datepicker/src/Calendar/README.mdx
React Day Picker changed its website to https://daypicker.dev/ – this PR updates our doc links.
=> docs: update react day picker links

packages/website/content/tokens/typography.mdx
Rename token headings in the typography docs to fix links. See the changes here: https://forma-36-git-docs-token-headings.colorfuldemo.com/tokens/typography
=> docs(typography): rename token headings

packages/components/progress-stepper/CHANGELOG.md
Similar to [this](https://github.com/contentful/forma-36/pull/2630) PR, since `ProgressStepper` is an `alpha` package, it does not have a `CHANGELOG.md`, yet the prelease script tries to access it, so I have added it here. 
This should resolve the build failure in the most recent commit to main.
=> chore: add CHANGELOG.md file to ProgressStepper alpha component

.changeset/great-masks-bake.md, package-lock.json, packages/components/entity-list/package.json, packages/components/entity-list/src/EntityListItem/EntityListItem.test.tsx, packages/components/entity-list/src/EntityListItem/EntityListItem.tsx, packages/components/entity-list/stories/EntityList.stories.tsx
Add support for Studio Experience entity type in `<EntityListItem>`
=> feat(entity-list-item): add support for Experience type entity

package.json
Removes the `postinstall` script, one can use the generic build command when needed.
This unblocks Netlify's dry-run build which tries to access `turbo` when it isn't installed yet.
**Alternative:** move Storybook's production build & deployment to Vercel.
=> build: remove postinstall script

.changeset/eighty-candles-change.md, packages/components/modal/src/ModalHeader/ModalHeader.styles.ts
Ensure design <-> code is aligned.
Our modal header border color is set to `gray/300` in the code vs `gray/200` in the design.
=> refactor(Modal): adjust header border-color to `gray/200`

packages/components/navbar/src/Navbar.tsx, packages/components/navbar/stories/Navbar.stories.tsx
For the purpose of adding the upgrade button as seen in [new design](https://www.figma.com/design/RBKfzEzcmiC974nFdtI2wK/Modern-%26-Scalable-%E2%80%93-2024-Webapp-Navigation?node-id=6351-23527&t=brDy0Gcl5MxlvqlD-0),  we want to create a new prop which would place itself in front of the switcher
=> feat: add promotions prop for promotions section in new nav bar

package-lock.json, packages/components/icons/package.json, packages/components/icons/src/index.ts, packages/components/icons/src/vendor/phosphor/BookOpenIcon.tsx
Adding a new icon: `BookOpen`
Storybook screenshot:
=> feat(icons): add `BookOpenIcon`

packages/website/components/Playground/SandpackRenderer.tsx
The new package was missing in the Sandpack Renderer (playground) dependency list resulting in an error.
Fixed playground URL: https://forma-36-git-fix-progress-stepper-playground-and-search.colorfuldemo.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwHJNjSaBuAHQDtUMddhcAFSgHN6AZxEBlbDDRoYmXAF9cFKrQACkNlK1kArgBsA9GQDMANgC0aIaJEWRUmXObt2MAB5c8sMkQPldNlIkCDZ+GxgxSWlZTAAJLCQAL1DsIn0AUXcidH0YAAoASh52XFx6bF1MMPzSstwAHgEIYUiJR1jcEmwkADcYaLQAXmAAJiUiTCQiABkiACMYfSGWEASplK103GsW21wHGLlVgD46+sbm1qiOuQA6QYO0qRXwKjQ8qVXcQzOwi8uERuR0wD0cTyIL1WkFyMC+IB+fwBgL2bUGsTB0ghUJA3T6MG+v3O9SaQPaIMxaERxLKpNRwKcoMeRP+tMMV1s6LkSNwhVYbAU7BACiAA
The Progress Stepper component was missing from the website search.
After some investigation, the Algolia crawler used for our website search has been blocked …
=> fix(playground): add `f36-progress-stepper` dependency

package-lock.json, packages/components/navbar/package.json, packages/components/navbar/src/Navbar.styles.ts, packages/components/navbar/src/NavbarItem/NavbarItem.styles.ts, packages/components/navbar/src/NavbarItem/NavbarItem.tsx, packages/components/navbar/src/NavbarItem/NavbarItemSkeleton.tsx, packages/components/navbar/src/NavbarSwitcher/NavbarSwitcherSkeleton.tsx, packages/components/navbar/stories/Navbar.stories.tsx
This PR makes the navbar more consistent, also changes the spacing/sizes to be closer to the designs.
General:
- All navbars have a height of 60px now
Regular navbar
- All items have a total height of 28px. (Avatar has 24px, but will have 28px with the planned border)
- Fixed padding-right for icon-items with menus
- Icon buttons are closer together in the designs. But wit the 44px click size, we can't bring them any closer
- Icon buttons are square now
Loading
- Increased skeleton text height
Mobile menu button:
- Reduced height to 36px
- Reduced horizontal padding
It's best to check chromatic for the detailed changes
=> feat(navbar): various navbar spacing tweaks

.changeset/rude-snakes-laugh.md, package-lock.json, packages/components/button/examples/IconButtonExample.tsx, packages/components/button/package.json, packages/components/button/src/IconButton/IconButton.tsx, packages/components/button/src/IconButton/README.mdx, packages/components/button/stories/IconButton.stories.tsx
This enables a built in tooltip for icon-buttons to enhance their user-experience. The IconButton will now accept `tooltipProps`, once it received this property, it will render a tooltip with a default showDelay of `600ms`
It is recommended to use the same content for the tooltip as the aria-label.
=> feat: enable built-in tooltip for icon buttons

packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.tsx, packages/components/navbar/stories/Navbar.stories.tsx
In some use cases we don't have space and environment, in those cases we pass a string that will appear on the switcher
=> refactor: enable children on navbar switcher

packages/components/navbar/package.json, packages/components/navbar/src/Navbar.styles.ts, packages/components/navbar/src/constants.ts, packages/components/navbar/src/index.ts
this pr is related to https://github.com/contentful/forma-36/pull/2859 it adds a fixed height to the light navbar and exports it, so it is useable in other components
=> fix: add fixed height to navbar

.changeset/fuzzy-rules-pump.md, .changeset/hot-ears-crash.md, packages/components/avatar/src/Avatar/Avatar.styles.ts, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/src/Avatar/utils.ts, packages/components/avatar/src/AvatarGroup/AvatarGroup.styles.ts, packages/components/avatar/stories/Avatar.stories.tsx
Fixes the Avatar's loading skeleton rendering.
We extend the size property to receive custom sizes. This should prevent people from using custom styling that does not deeply apply to the Avatar > Image > Skeleton loader component, see below:
**Current rendering with custom styling**
https://github.com/user-attachments/assets/2cfe3e24-d050-4745-a06d-739236e8bb25
> [!TIP]
> One can observe the loading skeleton before/after in the deployed Storybook by blocking the request to the avatar image:
> - In the Avatar stories
> - In the Navbar stories
**Before**
https://github.com/user-attachments/assets/1a4c6edc-870b-45c6-a7ff-a65fa9bdd64a
**After**
https://github.com/user-attachments/assets/fde616f5-b3e9-488c-b890-f0772b043c3d
- Add loading state to all `Loading` section
- Includes custom size …
=> fix(Avatar): avatar size and loading skeleton

.changeset/hot-ears-crash.md
In #2880 I added 2 changesets: one to reflect the `fix`, and the other to reflect the `feat`.
Using the changeset bot link, I manually edited the text from `patch` (added by default) to `feat` but it should have been `minor`.
This should fix the release on the CI.
=> chore: fix changeset to trigger release

packages/components/progress-stepper/src/ProgressStepper.tsx
[Form36 docs ](https://f36.contentful.com/components/progress-stepper) listed className as a prop for this component, but it wasn't being passed. I added it.
=> fix(ProgressStepper): add className prop

packages/components/progress-stepper/src/ProgressStepper.tsx
Reverts contentful/forma-36#2884
missed changset
=> Revert "fix(ProgressStepper): add className prop"

.changeset/chilled-shrimps-occur.md, .changeset/nasty-queens-laugh.md, packages/components/avatar/src/Avatar/Avatar.styles.ts, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/src/Avatar/utils.ts, packages/components/avatar/src/AvatarGroup/AvatarGroup.styles.ts
In the current version of the avatar component, the colored border overlaps with the image. The colored border is about 2 or 3px wide, so a total of 6px horizontal and vertical could be covered. With this PR, the size of the image is reduced to reduce overlaps.
The existing implementation was mixing size numbers with size strings. To shrink the image correctly, its size must be calculated. I, therefore, changed methods to always return numbers and to only add the `px` suffix at the very last moment. Imo, it's now way easier to understand when a variable is a number or a string.
Additionally, the overlay icon is round again.
=> fix(Avatar): don't overlap image with color border

.changeset/fluffy-files-matter.md, packages/components/header/src/Header.tsx
Render the `title` prop of `Header` as an `h1` heading by default.
=> feat(header): render title as h1

.changeset/fair-rockets-sing.md, packages/components/avatar/src/Avatar/Avatar.styles.ts, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/src/Avatar/types.ts, packages/components/avatar/src/Avatar/utils.ts
Increasing the inner white padding for app avatars
=> feat: increase white padding for app avatars

packages/cdn/README.md, packages/cdn/package.json
The CDN build currently inlines environment variables. This could be a security issue. This PR ensures that no environment variables (and therefore secrets) are inlined into the binary.
The issue was detected by the netlify secret scanner.
=> fix: stripe env variables from CDN build

packages/components/header/src/Header.styles.ts, packages/components/header/src/Header.tsx, packages/components/header/src/HeaderTitle.styles.ts, packages/components/header/src/HeaderTitle.tsx, packages/components/header/stories/Header.stories.tsx, packages/components/icon/stories/Icon.stories.tsx, packages/components/layout/src/Layout.styles.ts
- Move border from `Layout.Header` to `Header` component (so we can easily control it based on variant)
- Add `variant` prop to `Header`
- `breadcrumb` (default, current behaviour)
- new `title` variant. This variant renders the title with `DisplayText` and without the bottom border. This variant does not take breadcrumbs or allow for a backbutton.
=> feat: header variants

packages/components/navbar/src/NavbarSwitcher/NavbarEnvVariant.tsx
Following up on the switcher update from #2920, we want to use the rocket icon for all master environments, whether they are aliases or not.
Preview: https://5fd1dda724cc620021ace8c5-dzcsionulj.chromatic.com/?path=/story/components-navbar--with-different-environments
=> refactor(NavbarEnvVariant): update master env logic

packages/components/progress-stepper/README.mdx, packages/components/progress-stepper/examples/ProgressStepperHorizontalWidthLimitation.tsx
This PR adds to the website documentation for the ProgressStepper component by adding an example explaining the extra width that appears on the component when rendered in the horizontal orientation. We added a new example with borders to visually demonstrate this, as well as an explanation.
Screenshot of changes to the website:
=> docs(progress-stepper): add horizontal width limitation example

.changeset/neat-lizards-remember.md, .changeset/proud-files-punch.md, packages/components/multiselect/src/Multiselect.test.tsx, packages/components/multiselect/src/MultiselectOption.tsx
Handles two edge cases:
1. When the search value doesn't match the option text
E.g. when an option with the label `Apple` is rendered while the search value is `Lemon`. Currently, the multiselect item is rendered without any label - only the checkbox. With this PR, the option option label is rendered without any highlighting.
2. The search value has leading or trailing white space
Currently,  when an option has the label `Apple` and the search value is ` pp ` (not the white space) only the checkbox is rendered without any text. With the fix mentioned above, `Apple` is rendered without any highlighting. By internally trimming the search value, `Apple` is rendered with `pp` highlighted.
=> feat(multiselect): handle items without match & trim search value

packages/website/pages/[...slug].tsx
With some package update, typescript errors got interpreted as more strict. This implements the slug handling in a typesafe way with fallbacks.
=> fix: implement type safety fallback

.changeset/thick-dolphins-hang.md, packages/components/button/src/Button/Button.tsx, packages/components/button/src/IconButton/IconButton.tsx
- we don't need to hide `startIcon` when Button is in loading state.
=> fix: hide only endIcon when Button is in loading state

.changeset/witty-chefs-itch.md
In #2940, the generated changelog added the public website, which is excluded from releases.
This results in the IconButton components being blocked from being released.
=> fix: remove excluded package from changelog

.changeset/olive-bikes-pump.md, .changeset/rich-geckos-doubt.md, packages/components/typography/src/Caption/Caption.tsx, packages/components/typography/src/DisplayText/DisplayText.tsx, packages/components/typography/src/Heading/Heading.tsx, packages/components/typography/src/Paragraph/Paragraph.tsx, packages/components/typography/src/SectionHeading/SectionHeading.tsx, packages/components/typography/src/Subheading/Subheading.tsx, packages/components/typography/src/Text/Text.tsx
The components
- Caption
- DisplayText
- Heading
- Paragraph
- SectionHeading
- Subheading
Where all having an type issue, when using the spread operator. This fixes this issue, stemming from the "as" property. It also allows now to overwrite `fontColor` and `marginBottom` to allow for easier variations of these components.
=> feat: extend props and fix spread operator for typography components

.changeset/loud-numbers-report.md, packages/components/avatar/src/Avatar/utils.ts
Changes the color of the default Avatar Border from `gray400` to `gray500` for better contrast ratio
**Before**:
**After**
=> fix: use gray500 instead of gray400

.changeset/dull-brooms-begin.md, packages/components/copybutton/src/CopyButton.tsx, packages/components/copybutton/stories/CopyButton.stories.tsx
We want to prevent hardcoded strings for our components to be fully dynamic.
I replaced the hardcoded `aria-label` strings with the `tooltipCopiedText` and `tooltipText` values, it made sense to reuse them to keep values in sync and prevent introducing more properties.
But, I also discovered there is a `label` prop in this component API which sets the `aria-label` value on the initial state (`Copy to clipboard`). In the current proposal, the `tooltipCopiedText` would be applied only if no `label` value is set.
- Deprecate the `label` property and solely rely on the tooltip props values.
- Be explicit about setting `aria-label` values and add another property for the copied state.
I am favorable of the first option but if we want to be explicit about how these values are set we could lean …
=> chore(CopyButton): enable dynamic `aria-label` values

packages/components/icons/package.json, packages/components/icons/src/index.ts, packages/components/icons/src/vendor/phosphor/CalendarDotsIcon.tsx
Adding the calendar dots icon from Phosphor
=> feat(calendar-dots-icon): adding calendar dots icon []

.changeset/pretty-bats-reflect.md, packages/components/menu/src/Menu.test.tsx, packages/components/menu/src/Menu.tsx
Fix #2924 by focusing on the menu list when all items are disabled and add regression tests.
=> fix(menu): fix menu not closing on blur when items are disabled

.changeset/seven-mails-kiss.md, packages/components/menu/src/Menu.tsx
Fix edge case where a menu is opened and removed from the DOM at the same time before we can focus it in the next tick.
=> fix(menu): don’t focus menu if menu has just been removed

packages/components/navbar/package.json, packages/components/navbar/src/NavbarSwitcher/NavbarEnvVariant.tsx, packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.styles.ts, packages/components/navbar/src/NavbarSwitcher/NavbarSwitcher.tsx, packages/components/navbar/stories/Navbar.stories.tsx
As part of the Studio Trials work, we are adding a new purple "trial" variant to the navbar switcher:
Normal state:
Hover state:
=> feat(navbar): add purple variant to navbar switcher for trial spaces [ALT-1511]

.changeset/proud-bottles-cover.md, README.md, packages/cdn/public/fonts/geist-license.txt, packages/core/README.md, packages/core/src/GlobalStyles/GlobalStyles.tsx, packages/forma-36-tokens/src/tokens/typography/font-stack.js, packages/website/content/tokens/typography.mdx
Add Geist as new default font to both the primary and monospace font stacks.
=> feat: set Geist as default font

packages/components/avatar/src/Avatar/Avatar.test.tsx, packages/components/avatar/src/Avatar/Avatar.tsx, packages/components/avatar/src/AvatarGroup/AvatarGroup.test.tsx, packages/components/tooltip/src/Tooltip.test.tsx, packages/components/tooltip/src/Tooltip.tsx
Increases the delay to show the tooltip to prevent accidental triggers.
=> chore(Tooltip): update default delay

.changeset/lazy-bees-clap.md, packages/components/autocomplete/src/Autocomplete.tsx
We want to prevent hardcoded strings so that our components are fully dynamic.
=> chore(Autocomplete): enable dynamic `aria-label` value

.changeset/metal-teachers-repair.md, packages/components/header/src/BackButton.tsx, packages/components/header/stories/Header.stories.tsx
this change enables a dynamic variable for the aria-label in the back button, which was hardcoded before.
=> feat: enable i18n support for back button in header component [UFO-1300]

.changeset/great-files-shave.md, package-lock.json, packages/components/progress-stepper/README.mdx, packages/components/progress-stepper/examples/ProgressStepperClickableExample.tsx, packages/components/progress-stepper/package.json, packages/components/progress-stepper/src/CompoundProgressStepper.test.tsx, packages/components/progress-stepper/src/ProgressStepper.tsx, packages/components/progress-stepper/src/Step/Step.styles.ts, packages/components/progress-stepper/src/Step/Step.test.tsx, packages/components/progress-stepper/src/Step/Step.tsx, packages/components/progress-stepper/stories/ProgressStepper.stories.tsx
feat: Add onClick optional property to `ProgressStepper`
=> feat: Add onClick optional property to ProgressStepper

package-lock.json, packages/components/progress-stepper/README.mdx, packages/components/progress-stepper/examples/ProgressStepperOnlyPreviousStepsClickableExample.tsx, packages/components/progress-stepper/package.json, packages/components/progress-stepper/src/CompoundProgressStepper.test.tsx, packages/components/progress-stepper/src/ProgressStepper.tsx, packages/website/components/Playground/SandpackRenderer.tsx, packages/website/package.json
To allow client to use the `onClick` functionality with a bit more of flexibility, I am forwarding now all props from child component to the cloned Step. 
In this way, now it is possible to instead of adding a global `onClick` to have it on `Step` level, allowing us to control for example that **only previous steps are clickable**.
=> feat: Allow overriding onClick of ProgressStepper on child Steps

packages/components/asset/examples/ArchivedAssetExample.tsx, packages/components/asset/examples/AssetExample.tsx, packages/components/asset/examples/ImageAssetExample.tsx, packages/components/asset/src/Asset.test.tsx, packages/components/asset/stories/Asset.stories.tsx, packages/components/avatar/src/Avatar/examples/AvatarColorBorderExamples.tsx, packages/components/avatar/src/Avatar/examples/AvatarIconExamples.tsx, packages/components/avatar/src/Avatar/examples/AvatarMutedExamples.tsx, packages/components/avatar/src/Avatar/examples/AvatarSizeExample.tsx, packages/components/avatar/src/Avatar/examples/AvatarVariantExample.tsx, packages/components/avatar/src/AvatarGroup/examples/AvatarGroupSizeExample.tsx, packages/components/avatar/src/AvatarGroup/examples/AvatarGroupVariantExample.tsx, packages/components/avatar/stories/Avatar.stories.tsx, packages/components/avatar/stories/AvatarGroup.stories.tsx, packages/components/card/stories/AssetCard.stories.tsx, packages/components/entity-list/stories/EntityListItem.stories.tsx, packages/components/image/examples/ImageBasicExample.tsx, packages/components/image/stories/Image.stories.tsx, packages/components/navbar/examples/BasicNavbarExample.tsx, packages/components/navbar/examples/CompleteNavbarExample.tsx, packages/components/navbar/examples/WithAccountNotificationNavbarExample.tsx, packages/components/navbar/examples/WithDifferentEnviromnmentsNavbarExample.tsx, packages/components/navbar/stories/Navbar.stories.tsx, packages/website/content/deprecated-components/empty-state.mdx
The asset used in our stories started to get false positives in Chromatic, this is due to anti-aliasing and very likely to complex areas in the asset (areas with a lot of complexity, colors, or shadows).
---
This is an attempt to use an asset with less noise which should decrease the false-positives.
Note: I explored the `diffThreshold` [property](https://www.chromatic.com/docs/threshold) used to control the accuracy but its default value (`.063`) is already optimized (`0` is the most accurate, `1` is less accurate).
| <img src="https://github.com/user-attachments/assets/4ed38b5b-af89-437e-ae45-67f675b7e062" height="200" /> | <img src="https://github.com/user-attachments/assets/106d08b4-22fe-46c7-9f65-fc5b93b35655" height="200" /> |
=> refactor: replace the Storybook asset

packages/components/button/stories/ToggleButton.stories.tsx
Fixes the `ToggleButton` component story controls.
https://github.com/contentful/forma-36/assets/103024358/47f8b763-87b6-4e3b-b3f7-a9155f1133f1
=> chore(ToggleButton): story controls

.changeset/wicked-chefs-doubt.md, packages/components/entity-list/src/EntityListItem/EntityListItem.styles.ts, packages/components/entity-list/src/EntityListItem/EntityListItem.tsx, packages/components/entity-list/stories/EntityList.stories.tsx
Fixes issues with the EntityListItem component where:
- The skeleton loader height would be too big
- The drag handle would shrink when texts are too long
- The badge and the action menu were cut off when texts were too long
| - | Before | After |
|--------|--------|--------|
| Action menu (missing) | <img width="428" alt="basic-wrap-before" src="https://github.com/user-attachments/assets/85537c9c-a977-4c54-bdb6-e044b25ca71c" /> | <img width="426" alt="basic-wrap-after" src="https://github.com/user-attachments/assets/073a3138-310e-4bc2-9500-259ed126674a" /> |
| Skeleton, badge, drag handle | <img width="623" alt="drag-wrap-before" src="https://github.com/user-attachments/assets/4218a477-7413-43e6-b6e1-377dcf131759" /> | <img width="423" alt="drag-wrap-after" …
=> fix(EntityListItem): skeleton loader height, drag handle, and card wrapping

.changeset/kind-sheep-punch.md, packages/components/typography/stories/Paragraph.stories.tsx, packages/core/src/GlobalStyles/GlobalStyles.tsx
Improves lowercase L (l) and uppercase i (I) readability.
See the Paragraph story: https://5fd1dda724cc620021ace8c5-bvjnlbvdkg.chromatic.com/?path=/story/typography-paragraph--basic
| ![Screenshot 2025-02-14 at 13 55 58](https://github.com/user-attachments/assets/f08df7d3-c1ea-47d3-8711-1cf27107df01) | ![Screenshot 2025-02-14 at 13 56 17](https://github.com/user-attachments/assets/1171a8fe-2864-4d11-a48e-5376bbf2e11d) |
=> feat(GlobalStyles): improve lowercase L (l) and uppercase i (I) readability

.github/workflows/deploy-cdn.yml
Because Dependabot can't access the `FASTLY_API_TOKEN` secret, the workflow fails on all Dependabot merges to `main` and creates a lot of noise in our ci alerting channel.
=> chore: filter out Dependabot from CDN deploy workflow

.github/workflows/remove-stale.yml
This is an attempt to fix our failing `remove_stale` action.
`failed to run git: fatal: not a git repository (or any of the parent directories): .git`
=> fix: checkout repo before running gh

.changeset/itchy-rice-kneel.md, packages/components/menu/src/Submenu/Submenu.tsx, packages/components/menu/stories/Menu.stories.tsx
When rendering a `<Submenu>` close to the border of the window, it might render out of bounds as it's currently forced to not auto align itself.
https://github.com/user-attachments/assets/644133cd-abcc-4578-9441-212f05a72336
https://github.com/user-attachments/assets/b711559c-2868-48c3-b73f-ed6b51f7c8b8
=> fix: auto reposition submenu when out of viewport [SPA-2627]

.changeset/seven-impalas-fly.md, packages/components/typography/src/SectionHeading/SectionHeading.tsx, packages/components/typography/stories/SectionHeading.stories.tsx
For translation purposes it is important that text can contain upper and lower cases. By enforcing lower case for the whole headline, we would end up with wrong upper cases as a language like german uses uppercase for all nouns.
=> fix: don't enforce text case transform

package-lock.json, packages/website/package.json
I updated `next` [last time](https://github.com/contentful/forma-36/pull/3026) but `next-auth` still uses the old version. This PR updates `next-auth` as well to dedupe `next` again.
=> chore(website): update next-auth to match next

.changeset/some-colts-invite.md, packages/components/pill/src/Pill.tsx, packages/components/pill/stories/Pill.stories.tsx
This enables the full localization of the Pill component by handing over the new optional prop `closeButtonAriaLabel` the default of the aria-label is 'Close'
No visual differences.
=> feat: enable i18n for Pill component [UFO-1301]

.changeset/selfish-pots-unite.md, packages/components/notification/src/NotificationItem/NotificationItem.tsx, packages/components/notification/stories/Notification.stories.tsx
This enables the full localization of the `NotificationItem` component by handing over the new optional prop `closeButtonAriaLabel`, with the 'Dismiss' default value.
No visual differences.
=> feat(NotificationItem): enable localization

.changeset/spotty-points-study.md, packages/components/table/src/TableCell/TableCell.tsx, packages/components/table/stories/Table.stories.tsx
Enable localization of sortable table cells by adding an optional `sortButtonAriaLabel` property that overwrites the default English label.
PS: It may look weird that I’m adding a single static prop to replace a computed value but the `sortDirection` is controlled from the outside anyway and the column name is available there as well so whoever has control over the table cell can easily implement logic similar to what the table cell does internally for the default value.
=> feat(table): enable localization of sortable table cell

.changeset/petite-radios-speak.md, packages/components/multiselect/src/Multiselect.tsx, packages/components/multiselect/src/SelectAllOption.tsx, packages/components/multiselect/stories/Multiselect.stories.tsx
Enables localisation of the Multiselect Component by offering new optional properties.
For Multiselect Component
```
clearButtonProps = {
/**
* Aria label for the clear button
* @default 'Clear selection'
*/
ariaLabel?: string;
/**
* Tooltip for the clear button
* @default 'Clear selection'
*/
tooltip?: string;
};
/**
* Aria label for toggle button that opens the list
*/
toggleButtonAriaLabel?: string;
```
For Multiselect.SelectAllOption
```
selectAllOptionLabel? = {
/**
* Label for the select all option when it is checked
* @default 'Deselect all'
*/
checked: string;
/**
* Label for the select all option when it is unchecked
* @default 'Select all'
*/
unchecked: string;
};
```
No visual differences
=> feat: enable i18n for Multiselect Component [UFO-1750]

.changeset/slimy-states-double.md, package-lock.json
updates dependencies to babel-runtime to fix a vulnerability issue 
https://security.snyk.io/package/npm/%40babel%2Fruntime/7.22.15
=> chore: fix vulnerability in babel runtime 

packages/components/accordion/src/AccordionHeader/AccordionHeader.styles.ts
When toggling an `AccordionHeader`, it has no `hover` style until I click away once.
Apparently, the CSS rules for `&:focus` and `&:focus-visible` have a higher specificity. By including those cases in the hover rule specification, they also have a regular hover effect when clicking them.
https://github.com/user-attachments/assets/0b96d1a6-4788-4636-81df-f793d383795a
=> fix: show hover styles also when button was just clicked and has focus [SPA-2867]

.changeset/config.json, package-lock.json, packages/f36-i18n-utils/package.json, scripts/changesets/changelog-generate.js
we currently do not want the i18n-utils package to be automatically released as it is still considered alpha. Therefore we have to set the package to private.
=> chore: fix release step

packages/components/icons/package.json, packages/components/icons/src/index.ts, packages/components/icons/src/vendor/phosphor/CloudArrowDownIcon.tsx
- Adds `https://phosphoricons.com/?q=CloudArrowdown` from Phosphor to replace `ApisIcon` custom product icon
=> chore: [UFO-1740] Add Icon from Phosphor Icons to replace custom Product Icon

packages/components/navbar/README.mdx
Navbar is no longer importable via the `f36-components` package
=> docs: navbar import documentation

.changeset/healthy-beds-study.md, package-lock.json, packages/components/icon/package.json, packages/components/icons/package.json
Pin the version of Phosphor react package to the first version of the package that implements the new export names with the `Icon` suffix. This version is also the latest version that has a working CJS and ESM build so rather than allowing versions above `2.1.8` I pinned it.
=> fix(icons): pin phosphor to version with new names and working ESM build

.circleci/config.yml
Excludes the website from the link-checker CI job.
While the link is valid and reachable, it is facing too many requests and ultimately fails the job.
=> chore(CI): exclude website from link-checker
